### ISSUE TITLE
W/JsonHttpRH: onSuccess(int, Header[], JSONObject) was not overriden, but callback was received

### ISSUE THREAD

**Issue by whmsysu** [loopj/android-async-http#1007]
I integrated the android -async-http to the app successfully, but every time I ran the app, it shows a message like this. I am pretty sure that I override the same function. Here is my code:
RequestHandle requestHandle = HttpUtil.getInstance(activity).get(this.activity, url, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                super.onSuccess(statusCode, headers, response);
.......
Can anyone help me with it? Thanks.

**Comment by lubaochuan** [comment]
JsonHttpResponseHandler.onSuccess may accept an array of a different Header class than the Header class imported in this class: cz.msebera.android.httpclient.Header is used in 1.4.9 release.

**Comment by smarek** [comment]
I don't see any message, closing until you provide more info.

**Comment by derwaldgeist** [comment]
I have the same problem and definitely have overridden the right method.

**Comment by derwaldgeist** [comment]
Ok, I found out what the problem was: I used 1.4.9 of this library in the grade build, but 1.4.8 as a JAR (since 1.4.9 is not in the releases section). And strange enough, between 1.4.8 the HTTP has been switched from Apache to another library. Which is totally unexpected in a minor-minor release.
