### ISSUE TITLE
import cz.msebera.android.httpclient.Header

### ISSUE THREAD

**Issue by lubaochuan** [loopj/android-async-http#1012]
For the first example at https://loopj.com/android-async-http/ to work. The following class needs to be imported: cz.msebera.android.httpclient.Header

**Comment by teymoori** [comment]
Hi
When i`v added import cz.msebera.android.httpclient.Header to current project i received "Unable to execute dx error"
it seems some methods and classes are same in both libraries.

please help me to solve that.

**Comment by lubaochuan** [comment]
In your app/build.gradle file you need to add the following:
dependencies {
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'cz.msebera.android:httpclient:4.3.6'
}

**Comment by teymoori** [comment]
thanks but i dont used gradle.
i`v added both library by jar file

**Comment by teymoori** [comment]
it seems the jar file does not included CZ library.

**Comment by lubaochuan** [comment]
The link to download the CZ library is included in the following post: http://stackoverflow.com/questions/32939819/android-import-android-async-http-master-have-error

**Comment by mkiisoft** [comment]
There is a lack of information with 1.4.9... the compile import cz.msebera.android.httpclient.Header; is nowhere but here. I've been hours looking for the solution.

**Comment by AmirAzizi** [comment]
hi,
i have same problem :(
so I'm waiting your solution :)
please help ....

**Comment by teymoori** [comment]
is it solved ?
my problem persists.
