### ISSUE TITLE
passing raw StringEntity in 1.4.9

### ISSUE THREAD

**Issue by asystat** [loopj/android-async-http#1015]
Nice work guys I fucking love this lib.
After the 1.4.9 release, I am having problems here:

StringEntity se = new StringEntity(raw, "UTF-8");
return client.get(MainApplication.context, getAbsoluteUrl(url), se, "application/json", responseHandler);

Now StringEntity is deprecated and the method client.get receives a HttpEntity instead..
How can I do the same with this version?
thanx

**Comment by smarek** [comment]
Use the StringEntity as you used to, with 1.4 branch the library is not fully migrated to newer HttpClient APIs so we have to stick to deprecated classes for now.
