### ISSUE TITLE
Is it possible to get redirect URL using TextHttpResponseHandler?

### ISSUE THREAD

**Issue by airowe** [loopj/android-async-http#1016]
I'm using the TextHttpResponseHandler in conjunction with the SyncHttpClient and I'm not seeing the "Location" Header in the array returned in the onSuccess method. Should this be returned when using this handler or do I need to use a different one?

**Comment by smarek** [comment]
Redirects can be handled automatically, see the interface method `AsyncHttpClient.setEnableRedirects(final boolean enableRedirects, final boolean enableRelativeRedirects, final boolean enableCircularRedirects)`
