### ISSUE TITLE
setSSLSocketFactory in AsyncHttpClient takes a deprecated SSLSocketFactory parameter

### ISSUE THREAD

**Issue by tobiaselindberg** [loopj/android-async-http#1017]
The SSLSocketFactory that the method [setSSLSocketFactory](https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L753) in AsyncHttpClient takes as a parameter has a depricated flag on it. Any plans to change the AsyncHttpClient to take a none depricated ssl socket factory instead?

**Comment by smarek** [comment]
Yes, Use the deprecated classes as you used to, with 1.4 branch the library is not fully migrated to newer HttpClient APIs so we have to stick to deprecated classes for now.

With 1.5 branch we should be migrated to newer APIs so that deprecation problems don't appear anymore.

**Comment by FloridaStream** [comment]
Same problem for cloudflare SSL on free plan.
