### ISSUE TITLE
Can't use Fiddler to catch the network request data in version 1.4.9

### ISSUE THREAD

**Issue by yisizhu520** [loopj/android-async-http#1019]
I often use Fiddler to analyse network data and it goes well with the version 1.4.6. Is it because you switched library from using org.apache.http to use cz.msebera.android.httpclient? Thanks a lot!

**Comment by Borhan10** [comment]
So what is the solution to catch the requests by fiddler on the new version , because its hidden ?

**Comment by yisizhu520** [comment]
The fiddler doesn't show any interaction on the new version. But I caught the requests with WireShark successfully. As you know, WireShark can't show the requests and responses with pretty format.

**Comment by Borhan10** [comment]
So there is no solution to solve this problem on fiddler ?

**Comment by yisizhu520** [comment]
I haven't got a solution to solve this problem on the new version. I just replaced the 1.4.9 version with 1.4.8 and added 'org.apache.http.legacy.jar' to libs folder. It is an acceptable way.

**Comment by smarek** [comment]
Duplicate of #971
