### ISSUE TITLE
Token renewal

### ISSUE THREAD

**Issue by matteinn** [loopj/android-async-http#1022]
Hi there!
I'm trying to figure out if this library is somehow suited for handling token renewal.
It seems that extending AsyncHttpResponseHandler solves the problem of handling a 401 response in one place, handling the new response on the "onPreProcessResponse" method and parsing the new token, but how could I retry the same request then?

Many thanks in advance

**Comment by smarek** [comment]
Request not about library problems but about your integration model or similar place in different place, such as stackoverflow.com
