### ISSUE TITLE
Can't parse JSON using 1.4.9 and HttpClient 4.3.3

### ISSUE THREAD

**Issue by monowar1993** [loopj/android-async-http#1023]
Hi,
Having a weird problem. I cant parse data when i am using POST method in JsonHttpResponseHandler() in 1.4.9. Even i am not getting the JSON response. But when i am using 1.4.6. It works fine. Also GET method works fine with 1.4.9. I dont have any clue. Please help me to solve. Here is my code http://pastebin.com/8P3f9429 . Please please help me.
Thanks.

**Comment by monowar1993** [comment]
@smarek plz have a look into this. Sorry for mentioning. But i need to know whats going wrong with the code. Thanks.

**Comment by smarek** [comment]
We have plenty of examples of using this library together with handling Json request/response.
See the sample project sources

We're not here to fix your code, unless you can say it's problem of library, and You haven't provided any StackTrace from which we could say where the problem in library is. 

Closing as `on hold` unless you provide more info

**Comment by monowar1993** [comment]
solved the problem. The problem was 1.4.6 was redirecting automatically. But in 1.4.9 i need to setEnableRedirect(true). That was the problem. Thanks. :)

**Comment by smarek** [comment]
:) Cool, thanks for info
