### ISSUE TITLE
Android 2.3.6 not installing

### ISSUE THREAD

**Issue by lucianprobyte** [loopj/android-async-http#1025]
Hi, 
I have a problem with this library, I can't install my app on android 2.3.6 with Android Studio. I have to remove this line from gradle to install it on 2.3.6:

dependencies {
  compile 'com.loopj.android:android-async-http:1.4.9'
}

On newer Android, it installs well.

**Comment by smarek** [comment]
We currently have minimum sdk version of **8**, Android 2.3.6 shouldn't be any problem.
What error is given on install?
