### ISSUE TITLE
Using friendly URLs (without a question mark)

### ISSUE THREAD

**Issue by vipulyaara** [loopj/android-async-http#1027]
Hi.
On the backend, I am using friendly URLs (like www.google.com/id=1) and not query ones  (www.google.com/?id=1).
But when I use base url with params in asyn http, it makes the latter url. And thus, shows an error as it is not my url. Is there an option to switch to the URLs without question mark operator?

**Comment by smarek** [comment]
It's not sincerely, arguments from RequestParams class are either appended to URL with the question mark or are put into as form/json entity to POST/PUT/... requests. So you can either generate the url manually or using the RequestParams you'd have to reimplement `AsyncHttpClient.getUrlWithQueryString`, see current implementation here: https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L338
