### ISSUE TITLE
Upload big File in separated chunks to show progress

### ISSUE THREAD

**Issue by BenGroot** [loopj/android-async-http#1028]
I'm uploading files to a backend and experience issues while showing the progress. 
When a file gets too big the backend requires me to send the files in chunks of 5MB. Therefor I read these into memory and send them using the ByteArrayInputStream. Showing progress for byte[] apparently doesn't work yet in this library. Progress while uploading File objects does work though.

Is there any way to show the progress using the big file directly? For instance by specifying a range of bytes to use from a File object.

**Comment by smarek** [comment]
There is no progress implementation for out-going traffic so far, it's tracked in issue #711
Chunking the uploads is very specific, and I'm not willing to implement this as feature, so it'd have to be provided in pull request. Closing in favor of #711 as duplicate
