### ISSUE TITLE
HTTP Caching

### ISSUE THREAD

**Issue by soyangel** [loopj/android-async-http#103]
Does anybody know if  it's possible to enable HTTP caching?

If there was this library would be perfect :)

**Comment by 79144876** [comment]
I have fix it.https://github.com/79144876/android-async-http-loopj-with-cache
Use ormlite,gson and loopj.

**Comment by smarek** [comment]
@79144876 nice work, but you haven't fixed it, because we are talking about http protocol cache, not about caching specific data (thus all work with ormlite, json/gson, etc... is wrong, in the same way as it is wrong to store whole large json objects within database). still might inspire someone, but it's not implementation or workaround for http caching feature.

**Comment by 79144876** [comment]
oh , i got it. maybe you can  use CachingHttpClient for it. but i have not test it.

**Comment by smarek** [comment]
@79144876 that is indeed correct suggestion, however, as of now, library depends on system provided version of DefaultHttpClient, which is ofc wrong, and will be dealt with.

**Comment by 79144876** [comment]
Yeah.your library depends on system provided version of DefaultHttpClient.if you want to update it to CachingHttpClient,  it's not easy work (may be you can do this on other branch.we will stand by.)
Good luck.
Thanks.

**Comment by panxw** [comment]
My implements version: https://github.com/panxw/android-async-http-cached

**Comment by smarek** [comment]
Well, to give you update, currently with 1.4.9 we adopted upstream AFS HttpClient v4.3.3, with HttpClient-Cache bundled within. So upstream provided Caching workflows should be now available, see the upstream documentation: https://hc.apache.org/httpcomponents-client-ga/tutorial/html/caching.html

**Comment by FreakTheMighty** [comment]
@smarek can you please provide more information about how this works with `AsyncHttpClient`?

**Comment by FreakTheMighty** [comment]
To be a bit more specific, I'm confused how this exposed through this library. Based on the linked documents, it would appear that I would need a way to override the `httpClient` in this library with a configured `CloseableHttpClient`.

**Comment by smarek** [comment]
Well, to explain.
Library in 1.4.9+ version uses DefaultHttpClient from 4.3.6 upstream version of HttpComponents HttpClient, which extends AbstractHttpClient, which extends CloseableHttpClient.

Also the library `cz.msebera.android:httpclient:4.3.6` already contains HttpClient-Cache, HttpMime (see the release notes: https://github.com/smarek/httpclient-android/releases/tag/v4.3.6 )

Which means, only thing you have to do is follow upstream instructions on how to use HttpClient-Cache https://hc.apache.org/httpcomponents-client-ga/tutorial/html/caching.html to configure the library.

In version 1.5.0 (which is currently in development) I'll provide library API to configure caching, with version < 1.5.0 you have to do this manually.

**Comment by FreakTheMighty** [comment]
Hi @smarek, sorry for the delayed response, I'm just returning from family leave. Any chance you might have a snapshot of `1.5.0`?

**Comment by smarek** [comment]
Hi @FreakTheMighty, in fact we've migrated over to using upstream HttpClient 4.3.X with android-async-http branch 1.4.9, so if you want to test caching, it's possible with latest production version of library. 1.5.0 will only rewrite implementation of interfaces and will use more upstream code for implementing its functions.

**Comment by FreakTheMighty** [comment]
@smarek I see that 1.4.9 has the new client, but the apache tutorial appears to indicate that configuration needs to happen as part of a chain of factory methods. That is, it doesn't looks like the configuration of a client can be updated after its been initialized.

If the client configuration cannot be updated after being initialized, then I'd like to set android-async-http with a configured client. This doesn't seem possible because there is only a getter for the http client. My currently plan is to modify the android-async-http source and rebuild.

 I would be happy (and not surprised) if I'm missing something.

**Comment by smarek** [comment]
Sadly you're not missing anything, there is no setter for HttpClient so far, however you can get to override used HttpClient via subclassing AsyncHttpClient class and overriding `newAsyncHttpRequest` method, where you can use your own HttpClient instance.

There is HttpClient configuration class coming up with next release, so unless that will be available, this is nice way to implement desired function. Simple subclass example can be found here: https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/SampleParentActivity.java#L76

**Comment by FreakTheMighty** [comment]
@smarek thanks for taking the time to look into this. The new builder is giving me a bunch of trouble. My subclass of `AsyncHttpClient` looks like so:

```java
public class CachedAsyncHttpClient extends AsyncHttpClient {


    @Override
    protected AsyncHttpRequest newAsyncHttpRequest(DefaultHttpClient client, HttpContext httpContext,
                                                   HttpUriRequest uriRequest, String contentType,
                                                   ResponseHandlerInterface responseHandler,
                                                   Context context) {

        CacheConfig cacheConfig = CacheConfig.custom()
                .setMaxCacheEntries(1000)
                .setMaxObjectSize(8192)
                .build();

        CloseableHttpClient cachingClient = CachingHttpClients.custom()
                .setCacheConfig(cacheConfig)
                .build();

        return new AsyncHttpRequest(cachingClient, httpContext, uriRequest, responseHandler);
    }

}
```

What I'm finding, however, is that it's not possible to build or cast to a subclass of `AbstractHttpClient`, so the above code violates the `AsyncHttpRequest` interface.

**Comment by smarek** [comment]
Use the variable not with `CloseableHttpClient` type, but with `HttpClient` type

**Comment by FreakTheMighty** [comment]
I think the issue lies in `AsyncHttpRequest`, it expects a subclass of `AbstractHttpClient`, but `HttpClient` is not.

**Comment by FreakTheMighty** [comment]
The `AbstractHttpClient` extends `CloseableHttpClient` which implements `HttpClient`. With the factory creating a `CloseableHttpClient`, I simply don't see a way to pass `AsyncHttpRequest` a `AbstractHttpClient`.

**Comment by mikylucky** [comment]
@FreakTheMighty have you solved the problem? I'm facing the same issue
@smarek have you a release date for 1.5.0?

**Comment by Ismail-AlJubbah** [comment]
@smarek the case closed, Can I contribute to resolve it ?
