### ISSUE TITLE
how to handle multiple request Response in one callback method

### ISSUE THREAD

**Issue by dhavaljivani** [loopj/android-async-http#1030]
Hello,
Using this library how i can handle response from multiple request in one callback method.

Example : 
I have called 5 network call at a time so how can i find which network call response get in callback method.? Callback method is common for all network call.
Thanks

**Comment by smarek** [comment]
Just assign the callback to some function-local or class-global field and provide this field when calling `AsyncHttpClient.get/post/head/...` functions, basic programming

**Comment by Sushil21** [comment]
@smarek i have same issue of handle multiple response in single callback so can you explain solution more.
