### ISSUE TITLE
Suggestion: use Apache httpclient-android

### ISSUE THREAD

**Issue by kjkrum** [loopj/android-async-http#1031]
After you did all that work porting stand-alone Apache HTTP to Android, now Apache has come out with [their own version](https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html).  If it's easy to change the dependency to this, I'm sure it would be less maintenance going forward.

**Comment by smarek** [comment]
@kjkrum not right, 4.3.x port was available before, I was able to get 4.4.x for Android to work, which is officially documented by Apache here: https://hc.apache.org/httpcomponents-client-4.5.x/android-port.html
