### ISSUE TITLE
Posting json params containing Chinese characters to php server causes garbled characters 

### ISSUE THREAD

**Issue by Uphie** [loopj/android-async-http#1043]
## Garbled characters ##

 I'm using this library to post json params which may contain Chinese characters, and php server get garbled characters if params contains Chinese characters, English characters are ok.
The version is 1.4.9,and  ide encoding, project encoding are all utf8, if I switch to another libraty such as ok-http ,all is ok.
>  private static final String CONTENT_TYPE_JSON = "application/json";
>     public static void postByJson(String url, String json, TextHttpResponseHandler 
>     textHttpResponseHandler) {
>            try {
>                asyncHttpClient.post(context, url, new StringEntity(json), CONTENT_TYPE_JSON, 
>               textHttpResponseHandler);
>              } catch (UnsupportedEncodingException e) {
>                  e.printStackTrace();
>           }
>        }

**Comment by ysy950803** [comment]
Hi, I want to know how to post json params. I use RequestParams to new params then post to server which shows error that the params is not type of json. So how to new params of json type?

**Comment by Uphie** [comment]
@ysy950803 Are my codes working for your project?

**Comment by ysy950803** [comment]
@Uphie Oh, my test server is off, so I have not a test of your code yet. But you can check the sample which teaches how to use it.
https://github.com/loopj/android-async-http/tree/1.4.9/sample/src/main/java/com/loopj/android/http/sample

**Comment by Uphie** [comment]
@ysy950803 Try: http://weixin.tianyilm.cn/app/test.php , {"name":"Uphie","sex":"male"}

**Comment by ysy950803** [comment]
I also use php server and find the same problem with yours, and the params of Chinese characters become "???" but English has no problem. But after I clean up all my data of server then restart it, the problem goes away(This kind of error is always caused by the server instead of client code). And my version is 1.4.8 that you can have a try.

**Comment by Uphie** [comment]
I forget that my codes showed above were wrong then. This article may help you, http://m.blog.csdn.net/article/details?id=50250123

**Comment by ysy950803** [comment]
@Uphie Thanks!
