### ISSUE TITLE
Does this only support Marshmallow and greater?

### ISSUE THREAD

**Issue by SamuelMarks** [loopj/android-async-http#1064]
This looks like a pretty good library, well-supported + utilised, and around since Feb 2011.

Did I misread the docs that said it's only compatible with API ≥ 23?

If not—and assuming I want to support more than 1% of the current Android market—should I use some old [android-async-http version](https://github.com/loopj/android-async-http/releases), or look-around for another similarly good library? - If the latter, any recommendations?

EDIT: Looking through other issues here; https://github.com/loopj/android-async-http/issues/830#issuecomment-138341521; came across this => [httpclient-android](https://github.com/smarek/httpclient-android). Maybe that's the new recommended way of targeting multiple Android versions?

**Comment by wawlian** [comment]
We use this library in our apps which support API >= 14, it works well. The most recent release version (1.4.9) can support Marshmallow as well as the old platforms.

**Comment by SamuelMarks** [comment]
@wawlian phew, I sure was surprised when I went to http://loopj.com/android-async-http/ and saw:
>Compatible with Android API 23 and higher

Thanks for alleviating my fears :+1:
