### ISSUE TITLE
ssl Trust anchor for certification path not found. 

### ISSUE THREAD

**Issue by JimRoid** [loopj/android-async-http#1071]
i use this code TLS 1.2
```
KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
                trustStore.load(null, null);
MySSLSocketFactory sf = new MySSLSocketFactory(trustStore);
                sf.setHostnameVerifier(MySSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

asyncHttpClient.setSSLSocketFactory(sf);
```
but exception show log
```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:412)
at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
...
```
why?

device htc one m7

**Comment by dev01-adroitinfosol** [comment]
Here is the solution for you, This can be applied when you are using server for development purpose.

public SSLContext getSslContext() {

    TrustManager[] byPassTrustManagers = new TrustManager[] { new X509TrustManager() {
        public X509Certificate[] getAcceptedIssuers() {
            return new X509Certificate[0];
        }

        public void checkClientTrusted(X509Certificate[] chain, String authType) {
        }

        public void checkServerTrusted(X509Certificate[] chain, String authType) {
        }
    } };

    SSLContext sslContext=null;

    try {
        sslContext = SSLContext.getInstance("TLS");
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
    try {
        sslContext.init(null, byPassTrustManagers, new SecureRandom());
    } catch (KeyManagementException e) {
        e.printStackTrace();
    }

    return sslContext;

}

 AsyncHttpClient client = new AsyncHttpClient();

 client.setSSLSocketFactory(
            new SSLSocketFactory(getSslContext(),
            SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER));

**Comment by tusharuit25** [comment]
Great Solution ! If developer is using loopj library then at one spot he will face this issue for sure

**Comment by MSBilgin** [comment]
Work like a charm

**Comment by RapidNetInf** [comment]
SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER) is deprecated, and I faced error.
