### ISSUE TITLE
`cz.msebera.android:httpclient:4.3.6`  methods count:5935

### ISSUE THREAD

**Issue by cikichen** [loopj/android-async-http#1095]
That is not a good idea! I met a 65k limit.

**Comment by mdalikazi** [comment]
Thats still much less than Google play services which comes to more than 20,000. Android Studio handles it without trouble. Add `multiDexEnabled true` to your gradle.

```
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.1'

    defaultConfig {
        .
        .
        **multiDexEnabled true**
    }
```
