### ISSUE TITLE
Unsafe implementation of TrustManager

### ISSUE THREAD

**Issue by saragracia** [loopj/android-async-http#1107]
Hi!
I received this warning from google play related to the implementation of the interface X509TrustManager :S 
https://support.google.com/faqs/answer/6346016

**Comment by jjvargas** [comment]
Me too, any possible fix on this?

**Comment by djKooks** [comment]
It looks like custom implementation needs to be removed, or implement exception codes inside custom TrustManager.

**Comment by jjvargas** [comment]
Has anyone tried already some fix?

**Comment by fivefeet5** [comment]
Me too, wating...

**Comment by saragracia** [comment]
Hi! Sorry for the false alarm, this warning was due to another library, I received an email from google (went to my spam folder) that specifies which class is wrong implemented, this way I discovered which library was the problem. 
I close this issue, sorry for the disturbing
