### ISSUE TITLE
Header.java file missing in the library

### ISSUE THREAD

**Issue by Vespira** [loopj/android-async-http#1215]
I tryed out versions 1.4.9 or 1.4.8, resolving depencies with Gradle in my Android project.

A very weird issue is that on your source code on Github, or from the jar I have retrieved, there is no Header object available ! 

So I can't override the ResponseHandler methods. Is it just me or is something wrong ?

**Comment by Vespira** [comment]
It seems to be simply the package import into AsyncHttpHandler interface, which is still referencing to the Header file from the library. But you seems to now wants to use Header from 'cz.msebera.android:httpclient:4.3.6'.

So you can just add in your Gradle : compile 'cz.msebera.android:httpclient:4.3.6'.

**Comment by sparksterz** [comment]
I had the same issue, thanks for documenting this.
