### ISSUE TITLE
Post Multipart and json

### ISSUE THREAD

**Issue by samirae** [loopj/android-async-http#1217]
Hi
im trying to post a file and along with json like this fiddler request:

`---------------------------acebdf13572468
Content-Disposition: form-data; name="fieldNameHere"; filename="3.jpg"
Content-Type: image/jpeg

<@INCLUDE *C:\Users\user0.1\Pictures\3.jpg*@>
---------------------------acebdf13572468
Content-Disposition: form-data; name="model"; filename=""
Content-Type: application/json

{"ptid":1004,"i":null,"id":0,"bo":null,"t":"rev pink 5","hc":"hello","vs":1,"vi":"http://dornian.COM","hi":false,"iw":0,"ih":0,"po":["55555","hhhhh","iiiii","vvvvv","aaaaa"],"co":["aaaaa","vvvvv","iiiii","22222","11111"]}
---------------------------acebdf13572468--`

but i keep getting this error:
` {"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at System.Web.Http.ApiController.<InvokeActionWithExceptionFilters>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__0.MoveNext()"}`

can you help me?

**Comment by azizimusa** [comment]
post your code

**Comment by samirae** [comment]
i fixed it, thanks anyway

**Comment by samirae** [comment]
for anyone who's wondering how

`      RequestParams params = new RequestParams();
        params.put("model", new ByteArrayInputStream(jsonObject.toString().getBytes()), "", "application/json");
        if (imagePath != null)
            params.put("image.jpg", new File(imagePath), "image/jpeg", "image.jpg");
        params.setForceMultipartEntityContentType(true);
        client.post(url, params, handler);`
