### ISSUE TITLE
What is your License?

### ISSUE THREAD

**Issue by philiad** [loopj/android-async-http#1228]
There is LICENSE.TXT file, and it says you use Apache License 2.0
But there are not any copyright years, and name of copyright owner.

I want to use this s/w but I don't know your information.

For example, google-gson

![image](https://cloud.githubusercontent.com/assets/13360238/20965831/e72d8150-bcba-11e6-94d1-cadcc927d7c3.png)
https://github.com/google/gson

Usually they have year(s), name of copyright owner.
And of course I know who you are, and when the project is going on,
but I can't write this on my own for I don't have any rights. 
It's a legal problem.

So.. can you check this information please?

**Comment by leonardoxh** [comment]
It's on WEBSITE... On readme...

https://loopj.com/android-async-http/

**Comment by smarek** [comment]
Project (declared per file in header comment) is published under "Apache License, Version 2.0"
Contributors (with respective years) and license is listed in about page

http://loopj.com/android-async-http/

If you feel we need LICENSE(.txt) file in repository, feel free to PR
