### ISSUE TITLE
Google Play Blocker: Unsafe SSL TrustManager Defined

### ISSUE THREAD

**Issue by BahadirBulduk** [loopj/android-async-http#1260]
Hi,

I saw you are using custom TrustManager in your library. Google says, "Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager". I searched on stackoverflow and I found the solution. 
`public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
                try {
                    chain[0].checkValidity();
                } catch (Exception e) {
                    throw new CertificateException("Certificate not valid or trusted.");
                }
  }`.
Also, This is the solution from apache cordova plugin. You can check issue and fixed commits.

Issue : https://github.com/apache/cordova-plugin-file-transfer/pull/179
Commit : https://github.com/apache/cordova-plugin-file-transfer/pull/179/commits/0503664bd14319414630b7c704310b8c49c142d6

Can you check it and fix the issue?

**Comment by jehad-suliman** [comment]
Is there any update on this?

**Comment by BahadirBulduk** [comment]
No. There is no answer :(

**Comment by smarek** [comment]
Closing by merging #1261
