### ISSUE TITLE
onFailure(int, Header[], String, Throwable) was not overriden, but callback was received

### ISSUE THREAD

**Issue by Mr-LYF** [loopj/android-async-http#1288]
code show as below：
JSONObject jsonObject = new JSONObject();
 AsyncHttpClient httpClient = new AsyncHttpClient();
            String uri = JsonURL.INQUIRE_PAY_SERVICE_FEE_INFORMATION;
            RequestParams params = new RequestParams();
            params.put("json",jsonObject);
            httpClient.post(uri, params, new JsonHttpResponseHandler(){
               @SuppressLint("ApplySharedPref")
                @Override
                public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                     
                }
               @Override
                public void onSuccess(int statusCode, Header[] headers, JSONArray timeline) {

                }
          });

**Comment by vl25** [comment]
open your eyes
onFailure(int, Header[], String, Throwable)

you need use in your project
onFailure(int code, Header[] headers, String s, Throwable t)
