### ISSUE TITLE
No SNI support

### ISSUE THREAD

**Issue by viernullvier** [loopj/android-async-http#224]
At the moment AsyncHttpClient does not support SSL connections that use SNI ([Server Name Identification](http://en.wikipedia.org/wiki/Server_Name_Indication)). It's a technique that allows servers to return different SSL certificates depending on the requested host name, which allows using SSL in shared hosting scenarios. However, AsyncHttpClient only fetches the default certificate, therefore every request fails - most of the time even without an exception. It would be nice if SNI support could be added to this project.

**Comment by alexblack** [comment]
Any update on this?  It doesn't look like SNI support is available yet.

**Comment by georgbachmann** [comment]
I moved to retrofit and it solved my problems...

**Comment by alexblack** [comment]
Retrofit?  Sorry I'm not sure what you mean

**Comment by georgbachmann** [comment]
http://square.github.io/retrofit/

**Comment by svakulenko** [comment]
Its shame that SNI feature ( supported by java 1.7 which is integrated in Android studio) cant be used & in same moment, its ready to use, de facto.
Im moving to Volley.

**Comment by Xoib** [comment]
I am also leaving this lib because of this particular reason. My 2 cents.

**Comment by Zapnologica** [comment]
SNI support would be great. I enjoy this library and moving away from it would be a serious change just to support SNI.

**Comment by smarek** [comment]
SNI support is added in **1.4.9**, by using upstream HttpClient version **4.3.3**, which already supports SNI according to this JIRA ticket https://issues.apache.org/jira/browse/HTTPCLIENT-1119

1.4.9 will be released as soon as possible.

**Comment by Saren-Arterius** [comment]
I guess sni support is now complete yet? Try GET https://na.cx

**Comment by Saren-Arterius** [comment]
add this to build.gradle and sni cert works lol
compile "cz.msebera.android:httpclient:4.4.1.1"

**Comment by kamilwlf** [comment]
Does SNI work?

**Comment by MIkeeJY** [comment]
already work！！！

**Comment by nicpro85** [comment]
not working on the 1.4.9

**Comment by AdamMiltonBarker** [comment]
Any news on this ? It is not working on 1.4.9 it is fetching the incorrect certificate

**Comment by MIkeeJY** [comment]
@AdamMiltonBarker  maybe you should try okhttp instead of this lib
