### ISSUE TITLE
Which request callback

### ISSUE THREAD

**Issue by AAverin** [loopj/android-async-http#552]
More like a question then an issue.

If I fire 3 identical requests with same callbacks, in onSuccess or onFailure, any way to know which request callback it is?
I though of saving RequestHandle somewhere and checking it in onSuccess, can I get current RequestHandle in onSuccess somehow?

**Comment by smarek** [comment]
I've extended solution for #754 by placing the TAG directly within ResponseHandlerInterface implementation as WeakReference to given TAG Object, this TAG can be retrieved from callback methods, thus can serve as identification to request. See the linked implementation and sample commits

**Comment by smarek** [comment]
Also included in latest snapshot uploaded to snapshot repository
