### ISSUE TITLE
Sometime throws  "Request Timed Out"

### ISSUE THREAD

**Issue by yoojia** [loopj/android-async-http#685]
Long time (Several minutes or just seconds) after app without network requests, call a HTTP request will throws `org.apache.http.client.HttpResponseException: Request Timed Out`, but try again, it works.

I  consider it caused by ThreadPool, so I try `client.setThreadPool(Executors.newFixedThreadPool(4));`,
 but not work.

**Exception detail:**
```
org.apache.http.client.HttpResponseException: Request Timed Out
com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:376)
at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:101)
at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:112)
at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:68)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
We have experienced this issue with our application running in a test group of 25+ people. To verify that it is a bug the the library or the apache stack we had a second program running in the background that pinged the host.

The ping program showed no interruptions but the main application using this library has several timeout issues as shown by these log lines:

`02-12 09:52:40.699  22797-11903/com.example.app W/System.err? org.apache.http.conn.ConnectTimeoutException: Connect to /*.*.*.*:80 timed out
02-12 09:52:40.702  22797-11903/com.example.app W/System.err? at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
02-12 09:52:40.702  22797-11903/com.example.app W/System.err? at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
02-12 09:52:40.702  22797-11903/com.example.app W/System.err? at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
02-12 09:52:40.702  22797-11903/com.example.app W/System.err? at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
02-12 09:52:40.702  22797-11903/com.example.app W/System.err? at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
02-12 09:52:40.703  22797-11903/com.example.app W/System.err? at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
02-12 09:52:40.703  22797-11903/com.example.app W/System.err? at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
02-12 09:52:40.703  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
02-12 09:52:40.703  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
02-12 09:52:40.703  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
02-12 09:52:40.704  22797-11903/com.example.app W/System.err? at com.loopj.android.http.SyncHttpClient.sendRequest(SyncHttpClient.java:95)
02-12 09:52:40.704  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:942)
02-12 09:52:40.704  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:925)
02-12 09:52:40.704  22797-11903/com.example.app W/System.err? at com.example.app.connection.WaakConnection.post(WaakConnection.java:46)
02-12 09:52:40.704  22797-11903/com.example.app W/System.err? at com.example.app.tasks.doNotificationFetch.execute(doNotificationFetch.java:29)
02-12 09:52:40.704  22797-11903/com.example.app W/System.err? at com.example.app.services.NotificationService.fetchNotifications(NotificationService.java:117)
02-12 09:52:40.705  22797-11903/com.example.app W/System.err? at com.example.app.services.NotificationService.startService(NotificationService.java:78)
02-12 09:52:40.705  22797-11903/com.example.app W/System.err? at com.example.app.services.NotificationService.onHandleIntent(NotificationService.java:124)
02-12 09:52:40.705  22797-11903/com.example.app W/System.err? at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
02-12 09:52:40.705  22797-11903/com.example.app W/System.err? at android.os.Handler.dispatchMessage(Handler.java:102)
02-12 09:52:40.705  22797-11903/com.example.app W/System.err? at android.os.Looper.loop(Looper.java:135)
02-12 09:52:40.705  22797-11903/com.example.app W/System.err? at android.os.HandlerThread.run(HandlerThread.java:61)
02-12 09:52:40.706  22797-11903/com.example.app V/JsonHttpResponseHandler? response body is null, calling onFailure(Throwable, JSONObject)
02-12 09:52:40.732  22797-11903/com.example.app W/System.err? org.apache.http.conn.ConnectTimeoutException: Connect to /*.*.*.*:80 timed out
02-12 09:52:40.732  22797-11903/com.example.app W/System.err? at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
02-12 09:52:40.733  22797-11903/com.example.app W/System.err? at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
02-12 09:52:40.733  22797-11903/com.example.app W/System.err? at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
02-12 09:52:40.733  22797-11903/com.example.app W/System.err? at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
02-12 09:52:40.733  22797-11903/com.example.app W/System.err? at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
02-12 09:55:34.057  22797-11903/com.example.app W/System.err? at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
02-12 09:55:34.057  22797-11903/com.example.app W/System.err? at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
02-12 09:55:34.057  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
02-12 09:55:34.057  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
02-12 09:55:34.057  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.loopj.android.http.SyncHttpClient.sendRequest(SyncHttpClient.java:95)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:942)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:925)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.example.app.connection.WaakConnection.post(WaakConnection.java:46)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.example.app.tasks.doNotificationFetch.execute(doNotificationFetch.java:29)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.example.app.services.NotificationService.fetchNotifications(NotificationService.java:117)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.example.app.services.NotificationService.startService(NotificationService.java:78)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at com.example.app.services.NotificationService.onHandleIntent(NotificationService.java:124)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at android.os.Handler.dispatchMessage(Handler.java:102)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at android.os.Looper.loop(Looper.java:135)
02-12 09:55:34.058  22797-11903/com.example.app W/System.err? at android.os.HandlerThread.run(HandlerThread.java:61)`

We are investigating further and are looking into switching to a different library until this issue has been addressed. I would strongly advise to consider removing the 'on hold' label on this issue and actively search (perhaps even together with others above) for a fix. On another forum I have read this bug has been introduced in v1.4.4.

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
I pulled the latest changes and I have not been able to reproduce this issue with that version yet. (manifest displays v1.4.7)

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
I have found the problem to be related to net.ipv4.tcp_timestamp serverside. Disabling this parameter fixes this issue. Of course most web admins want to have this option enabled though I doubt this library will implement or even find a workaround for this issue in any way.

**Comment by smarek** [comment]
Thank you for the solution, closing up.

**Comment by david-pureal** [comment]
thanks, RaymondBakkerMoonlightMultimedia.
