### ISSUE TITLE
Clients doesn't call back sometimes

### ISSUE THREAD

**Issue by AndyDengGeGe** [loopj/android-async-http#717]
I have a ViewPager that contains three fragment. And have a request data method in onCreateView() in every Fragment.Sometimes,when the network is bad, The first fragment can get the data ,But another two fragments cannot call back.They seems to be pausd after call the method onStart() of HttpClient.  What should i do ?

**Comment by wxlfight** [comment]
I have a smilar problem. when there is a 302 redirect, the server response successfully, but the client can not get any response ,it seems asynchttp didn't call onSuccess()  method ,i don't know why? and this problem occur sometimes, not always.

@smarek can you help me?

**Comment by smarek** [comment]
@wxlfight can you trace the response handler, what methods are called ? But breakpoints in processing of `AsyncHttpRequest.java` method `run()`
