### ISSUE TITLE
Maybe a Dirty Reads thread bug in AsyncHttpClient

### ISSUE THREAD

**Issue by Bai-Jie** [loopj/android-async-http#730]
I'm inexperienced on thread, but maybe this is a Dirty Reads bug.
line 1187 in `com.loopj.android.http.AsyncHttpClient.sendRequest(DefaultHttpClient client, HttpContext httpContext, HttpUriRequest uriRequest, String contentType, ResponseHandlerInterface responseHandler, Context context)`:
```java
if (context != null) {
    // Add request to request map
    List<RequestHandle> requestList = requestMap.get(context);
    synchronized (requestMap) {
        if (requestList == null) {
            requestList = Collections.synchronizedList(new LinkedList<RequestHandle>());
            requestMap.put(context, requestList);
        }
    }

    requestList.add(requestHandle);

    ...
}
```

After this sequence:

Thread A | Thread B
------------ | -------------
map.get(x)==null   | 
                             | map.get(x)==null
                              | map.put(x, listB)
 map.put(x, listA) |  
                              |  listB.add(sth2)
listA.add(sth1) |  

listB and sth2 are lost.

I think `requestMap = Collections.synchronizedMap()` only insure `requestMap.get` **finished before** next operation on it, but can't prevent this Dirty Reads probability.
Should `List<RequestHandle> requestList = requestMap.get(context);` be in `synchronized (requestMap) { ... }`? I'm not sure about it so I didn't pull request. Is there anyone skilled about it?

ADD: Maybe this is a sample, http://en.wikipedia.org/wiki/Singleton_pattern#Lazy_initialization

**Comment by smarek** [comment]
Thank you, fixed
