### ISSUE TITLE
SSL handshake aborted

### ISSUE THREAD

**Issue by luissilvaos** [loopj/android-async-http#746]
Hi guys,

I'm getting this error when I'm trying to do a HTTP Post request:

```
11-27 13:40:57.595    W/System.err﹕ javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8cea070: Failure in SSL library, usually a protocol error
11-27 13:40:57.595   W/System.err﹕ error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x970a2926:0x00000000)
11-27 13:40:57.595   W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
```

Can anyone help me with this?

Thanks

**Comment by dev01-adroitinfosol** [comment]
Here is the solution for you, This can be applied when you are using server for development purpose.

public SSLContext getSslContext() {

    TrustManager[] byPassTrustManagers = new TrustManager[] { new X509TrustManager() {
        public X509Certificate[] getAcceptedIssuers() {
            return new X509Certificate[0];
        }

        public void checkClientTrusted(X509Certificate[] chain, String authType) {
        }

        public void checkServerTrusted(X509Certificate[] chain, String authType) {
        }
    } };

    SSLContext sslContext=null;

    try {
        sslContext = SSLContext.getInstance("TLS");
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
    try {
        sslContext.init(null, byPassTrustManagers, new SecureRandom());
    } catch (KeyManagementException e) {
        e.printStackTrace();
    }

    return sslContext;

}

 AsyncHttpClient client = new AsyncHttpClient();

 client.setSSLSocketFactory(
            new SSLSocketFactory(getSslContext(),
            SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER));

**Comment by wslaimin** [comment]
Did you solved the problem?

**Comment by wslaimin** [comment]
@luissilvaos 
Did you solved the problem?I get the same situation,but I can not solve it.if you have a solution,please tell me .Thank you!

**Comment by mzhs-git** [comment]
The above code still does not solve my problem.
Exception info:
SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
sslsocketfactory set:
asynclient.setSSLSocketFactory(MySSLSocketFactory.getFixedSocketFactory());

server only support tls1.2
andorid 4.4.4

when I add
HttpsURLConnection.setDefaultSSLSocketFactory(new NoSSLv3Factory());
before
AsyncHttpClient client = new AsyncHttpClient();
and remove
asynclient.setSSLSocketFactory(MySSLSocketFactory.getFixedSocketFactory());
Exception info:
no peer cer..

Both codes are added，Exception info:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Can anyone help me with this?

Thanks

**Comment by mzhs-git** [comment]
> Did you solved the problem?

你把这个问题解决了吗？

**Comment by mzhs-git** [comment]
@wslaimin 这个问题你后来解决了吗？
