### ISSUE TITLE
Retry on SocketTimeoutException

### ISSUE THREAD

**Issue by stream101** [loopj/android-async-http#749]
It is a good practice to automatically retry on SocketTimeoutException, just as google's Volley library does:
```
 try {
       //issue http request ...
      } catch (SocketTimeoutException e) {
           attemptRetryOnException("socket", request, new TimeoutError());
      } catch (ConnectTimeoutException e) {
           attemptRetryOnException("connection", request, new TimeoutError());
     }
```
It helps enhancing the reliability when the network is poor. I understand that I can manually add it to whitelist using RetryHandler.addClassToWhitelist(SocketTimeoutException.class). But could you please explain the reason why InterruptedIOException is in the blacklist by default ? An inexperienced programmer (like me) may not examine the source code and change the default settings until encountering the RTE. So I strongly suggest to enable the retry on SocketTimeoutException by default.

**Comment by smarek** [comment]
To solve, just use `RetryHandler.addClassToWhitelist(SocketTimeoutException.class)`, library won't have this by default.

**Comment by stream101** [comment]
@smarek , could you please give some examples of non-repeatable http requests ? It will be very helpful !
