### ISSUE TITLE
Cancel request by TAG

### ISSUE THREAD

**Issue by eGorets** [loopj/android-async-http#754]
I think it would be a good feature for manage queries workflow. Just like in picasso project.

**Comment by andrewchen5678** [comment]
OkHttp and Volley all has this feature but not here.

**Comment by smarek** [comment]
Provided, can you please review ? @andrewchen5678 @eGorets 
Will be released with version 1.4.8 

Implementation: https://github.com/loopj/android-async-http/commit/8b1243cfaab1822cb27bd475715c9af1a9d14454
Sample usage: [CancelRequestByTagSample.java](https://github.com/loopj/android-async-http/blob/90b69cf30f17b9af0d2a185e0f36b197354f0f40/sample/src/main/java/com/loopj/android/http/sample/CancelRequestByTagSample.java)

**Comment by smarek** [comment]
Also included in latest snapshot uploaded to snapshot repository

**Comment by eGorets** [comment]
@smarek cool, thanks, but in some case I think it would be better to set 'Object' as a TAG, for example, in activity we can use 'setTag(this)' and 'cancelQueriesByTag(this)' in lifecycle methods without String tags.

**Comment by smarek** [comment]
@eGorets that's what the purpose of Context as first param of every `AsyncHttpClient` call is. You pass the context, and then you can cancel requests for context using `cancelRequests(final Context context, final boolean mayInterruptIfRunning)` (here: https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L760 )

**Comment by eGorets** [comment]
@smarek oh, sorry, you are right. This is a really good job.
