### ISSUE TITLE
CancelAllRequests sometimes leads to Exception

### ISSUE THREAD

**Issue by della-90** [loopj/android-async-http#758]
### Problem
If you make an async request and then you cancel it with `asyncClientObject.cancelAllRequests(true)` then sometimes when the request times out it is thrown the following Exception:

### LogCat:
(1st column = logging level, 2nd column = message)

	D	Request got cancelled
	E	wrappedEntity consume
	E	java.net.SocketException: Bad file number
	E		at org.apache.harmony.luni.platform.OSNetworkSystem.readSocketImpl(Native Method)
	E		at org.apache.harmony.luni.platform.OSNetworkSystem.read(OSNetworkSystem.java:358)
	E		at org.apache.harmony.luni.net.PlainSocketImpl.read(PlainSocketImpl.java:561)
	E		at org.apache.harmony.luni.net.SocketInputStream.read(SocketInputStream.java:88)
	E		at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
	E		at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:134)
	E		at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:174)
	E		at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:188)
	E		at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:121)
	E		at org.apache.http.entity.BasicHttpEntity.consumeContent(BasicHttpEntity.java:142)
	E		at com.loopj.android.http.AsyncHttpClient.endEntityViaReflection(AsyncHttpClient.java:1363)
	E		at com.loopj.android.http.AsyncHttpResponseHandler.getResponseData(AsyncHttpResponseHandler.java:442)
	E		at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:400)
	E		at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:161)
	E		at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
	E		at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
	E		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	E		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	E		at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	E		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
	E		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
	E		at java.lang.Thread.run(Thread.java:1096)

**Comment by smarek** [comment]
Yes, this can occur on low-level of network implementation. This error is throwed in https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L1512

So in fact the request gets canceled correctly, but this error is thrown lower in the stack, which is nothing we can do about.
