### ISSUE TITLE
onProgress totalSize always = 1

### ISSUE THREAD

**Issue by kamilwlf** [loopj/android-async-http#767]
is this normal?

V/AsyncHttpResponseHandler﹕ Progress 15 from 1 (1500%) 
 ```
@Override
public void onProgress(int bytesWritten, int totalSize) {
        super.onProgress(bytesWritten, totalSize);
 }

@Override
public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
```

**Comment by smarek** [comment]
What version of library do you use? Because this issue is something we already fixed, it is related to problem getting real size of compressed streams, which are reported as of length -1.

**Comment by jendib** [comment]
I also get this issue on 1.4.6.
My `InputStream` is created from:
```java
InputStream is = getContentResolver().openInputStream(uri);
```

**Comment by kamilwlf** [comment]
i use 1.4.6

**Comment by smarek** [comment]
Oh, streaming upload, it's not possible by default to know what size the InputStream has, so the reporting goes with number of bytes uploaded. InputStream has no method to report the content size. Method `available()` is not reliable in the case.

**Comment by jendib** [comment]
So sad :( So I should grab the total size elsewhere I guess. Thanks

**Comment by wayne0215** [comment]
onProgress() not work when upload inputstream.Couldn't fix this problem?
InputStream in = cr.openInputStream(uri);uri is file path.
