### ISSUE TITLE
RequestHandle:cancel() cause RangeFileAsyncHttpResponseHandler call onSuccess()

### ISSUE THREAD

**Issue by honghui** [loopj/android-async-http#772]
```java
AsyncHttpClient httpClient = ...;

RequestHandle handler = httpClient.get(url, new RangeFileAsyncHttpResponseHandler( new File(saveTo)) {
...
    public void onSuccess(int statusCode, Header[] headers, File file) {
        // if file damaged, redownload it
    }
...
}
```
when I use the following code:
```java
handler.cancel(true);
```
`onSuccess()` will be called, then call `onCancel()`.

It's a critical bug for developers who want to redownload the file when the downloaded file is damaged!
Cancel download will download again.

**Comment by smarek** [comment]
You should always check file size and/or checksum after downloading, RangeFileAsyncHttpResponseHandler will only ensure, that if the file already exists, it will be downloaded from last byte on to end of file.
