### ISSUE TITLE
Synchronous mode with AsyncHttpClient

### ISSUE THREAD

**Issue by gsteigert** [loopj/android-async-http#781]
Is there a way to handle responses synchronously with AsyncHttpClient? My handler is created within the main thread, which has a message looper as required, but it still cannot be used with AsyncHttpClient in synchronous mode.

If the only way is to use the SyncHttpClient, then I don't understand why there is a "setUseSynchronousMode" method in AsyncHttpResponseHandler - the response handling strategy could simply be infered by the client instance being used.

What I'd really like is to always use AsyncHttpClient and take advantage of the handler's "SynchronousMode" flag to configure on which thread the response handling will occur.

Does that make any sense?

**Comment by smarek** [comment]
`setUseSynchronousMode` purpose is to allow single implementation of AsyncHttpResponseHandler for both sync and async use-cases, you can see that in usages of the method

This is already handled on per-request basis, so if you provide ResponseHandler instance with `useSynchronousMode` set to `true` to `AsyncHttpClient`, it will be handled synchronously, `SyncHttpClient` is just simplification of the process.
