### ISSUE TITLE
Question: are retries supported when POSTing?

### ISSUE THREAD

**Issue by alexblack** [loopj/android-async-http#783]
I'm not seeing retries happening, and I'm not sure its not supports vs I'm doing it wrong.

Code snippet:

    AsyncHttpClient client = new AsyncHttpClient();
    client.setMaxRetriesAndTimeout(5, 5000);
    client.post(url, params, new AsyncHttpResponseHandler() {
        @Override
        public void onRetry(int retryNo) {
          Log.d(TAG, "Retry: " + retryNo);
        }

**Comment by smarek** [comment]
Not by default, if you have params, you have to set `.setHttpEntityIsRepeatable(boolean)` on RequestParams, see https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/RequestParams.java#L416

**Comment by alexblack** [comment]
I tried setting that param with no luck. It still doesn't retry. Are there
any scenarios where it won't retry?

**Comment by smarek** [comment]
Is there anything in LogCat?
