### ISSUE TITLE
 Network blocked during uploading

### ISSUE THREAD

**Issue by kufufu9** [loopj/android-async-http#784]
hi.I use your library,but I encountered a  problem,
during uploading large files(about 10MB), the network is blocked which means no other  net request of same application can be responsed quickly.The response takes very long time.  
The uploding is run in an service.
Do you have encountered such problems and are there any solutions to it?Such as set request priority etc.
thank you.

**Comment by smarek** [comment]
I don't think this is problem of library, more like issue of underlying HttpClient, used ThreadPool (ExecutorService) or ability of network/server to server parallel requests. Please discuss this on stackoverflow.com and return back if you find out this is problem of library.
