### ISSUE TITLE
Is there  a way to upload files using Multipart to only one parameter?

### ISSUE THREAD

**Issue by Chenng** [loopj/android-async-http#785]
Is there  a way to upload files using Multipart to only one parameter? I have read the document like  ``params.put("profile_picture", myFile);``  that can only set one file in one parameter. Is there any way to set files array to a parameter like multipart form? Thank you very much.

**Comment by smarek** [comment]
This is common question, this can be done the same way HTML forms do that. Each file is assigned under name `key[array_index]`, eg.

```
params.put("pictures[0]", firstFile);
params.put("pictures[1]", secondFile);
params.put("pictures[2]", thirdFile);
```

**Comment by Chenng** [comment]
Thanks a lot !

As I usually want to use a custom method to simplify the upload progress, I think it is a little strange to upload file as this way.
```java
    public static void uploadFiles(String url, List<NameValuePair> paramsList, String fileParams, File[] files, AsyncHttpResponseHandler responseHandler){
...
        params.put(fileParams+"["+i+"]", files[i]);
...
}
```
