### ISSUE TITLE
When receiving a string response on success the library give out exception

### ISSUE THREAD

**Issue by saurabytes** [loopj/android-async-http#786]
The success string response has been handled incorrectly and is mapped to a failure with `onFailure(int, Header[], String, Throwable) was not overriden, but callback was received`
Culprit code seems to be https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/JsonHttpResponseHandler.java#L130
```
else if (jsonResponse instanceof String) {
                                    onFailure(statusCode, headers, (String) jsonResponse, new JSONException("Response cannot be parsed as JSON data"));
                                } 
```
instead it should be 
```
                                    onSuccess(statusCode, headers, (String) jsonResponse);
```

**Comment by smarek** [comment]
Warning is correct, you've overrided wrong callback method. onFailure indicates that HTTP error code was returned along with the string or that the response is not JSON as it should be in JsonHttpResponseHandler, if you're receiving String response from API, you should use TextAsyncHttpResponseHandler or AsyncHttpResponseHandler directly.

If your API returns sometimes String and sometimes JSON, it is clearly to me wrong design decision.
