### ISSUE TITLE
Success empty JSON string problem

### ISSUE THREAD

**Issue by NameX44** [loopj/android-async-http#787]
Hi, first of all, good job for this library.

I have a response from server which is empty and an application/json content type. 

the returned body is empty. So the method : 
```java
 protected Object parseResponse(byte[] responseBody) throws JSONException
```
it gives an empty String which is send to onFailure callback. Is there a reason why we couldn't create an empty JSONObject if jsonString is null ? 
Isn't it a valide JSON ?

If I add "{}" to my empty string, it will work and will be parse into JSONObject.

PS : I want to know what you think about that before post a PR.

Thank you,

**Comment by smarek** [comment]
Hi, thanks.

To your question, If the ResponseHandler expects response in JSON, null is not valid JSON object, it should response with empty JSON object or JSON array (`[]`, `{}`)

What do you think @fineswap ?

**Comment by fineswap** [comment]
Well, a JSON is not only an array or object. So technically speaking, if the server sends back a string containing "null", "true" or "false", they are correct JSON responses.

**Comment by rockyoung** [comment]
@fineswap please check this http://json.org/

**Comment by fineswap** [comment]
@rockyoung 
```javascript
var r;
JSON.stringify(r = null);
JSON.stringify(r = true);
JSON.stringify(r = false);
JSON.stringify(r = 100);
```

**Comment by NameX44** [comment]
So there are another thing that we have to correct, maybe in another issue.
if server response is :
"astring" without any brace or bracket.

Do you need a PR ?

**Comment by fineswap** [comment]
@NameX44 
If you have the time and will for a PR, we'd be very happy for your help :+1:

**Comment by fineswap** [comment]
@NameX44 
Also, `JSON.stringify(r = "astring")` will give you `"astring"` as the JSON value, so the PR needs to support all these: numerics, booleans, strings and nulls.

**Comment by NameX44** [comment]
Np,

There isn't JSON.stringify() function in org.json.*. 

Should I create a new onSuccess callback which allows String response ? Then user has to handle every type ? Or a onSuccess callback by type ? Or do you have another idea ?

**Comment by smarek** [comment]
I think we'd break backwards compatibility. Til now handling the response was strongly validated, if the response type was not "application/json" it failed, and if the returned string was not JSON, it failed.

JSON.stringify / JSON.parse are Javascript functions (ECMA script json implementation).

However there is no way to represent primitives (string, int, boolean) as JSONObject or JSONArray in Java. We could probably add one more callback to handle single JSON value, but that would be essentially same to returning plain string if it cannot be parsed, which is incorrect in my opinion.

**Comment by smarek** [comment]
As of http://json.org definition

>JSON is built on two structures:
A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.

Also JSON RFC4627 (http://www.ietf.org/rfc/rfc4627.txt), paragraph 2, says:

>A JSON text is a sequence of tokens.  The set of tokens includes six
   structural characters, strings, numbers, and three literal names.

>   A JSON text is a serialized object or array.

 >    JSON-text = object / array

Which means top level have to be either `{}` (object) or `[]` (array)
Fact, that javascript will parse and return single value, is in my opinion not obligatory to our situation.

**Comment by NameX44** [comment]
So if we follow these definition, we shouldn't change anything ? right ?

**Comment by smarek** [comment]
Yes, that is correct. I'm closing this issue.

**Comment by NameX44** [comment]
You should read this one by the way. This is an upgrade of your previous definition, making yours obsolete : 
 https://tools.ietf.org/html/rfc7159

**Comment by NameX44** [comment]
And making single value allowed.

**Comment by smarek** [comment]
@NameX44 that's correct, you've got me. Also see: https://stackoverflow.com/questions/18419428/what-is-the-minimum-valid-json/22361229#22361229

In that case, we can start working (and I'd be really glad for your pull-requests) to bring RC7159 compatibility within `JsonAsyncHttpResponseHandler` and `JsonStreamerEntity`

**Comment by NameX44** [comment]
I don't know how to link my pull request to this issue. If you could tell me how to do it :)

**Comment by smarek** [comment]
@NameX44 it's enought to mention the issue in the pull request (in form #ID_OF_ISSUE ), or otherwise, mention the pull request id in the comment here.

**Comment by smarek** [comment]
Closing as the PR #796 is merged
