### ISSUE TITLE
how to implement long-link or half-long-link by android-async-http?

### ISSUE THREAD

**Issue by LittlePanpc** [loopj/android-async-http#789]
I have encountered an urgent situation where I need to check the state of an order. But the remote server wouldn't return the response soon because it would cast a relatively long time. So somebody recommended me to use long-link or half-long-link of HttpClient. but I never run into such an unknown situation for me. So I wanted to know how implemented it. Does somebody have some good ideas?

**Comment by smarek** [comment]
Closing in favor of duplicate SO QA, https://stackoverflow.com/questions/27961498/how-to-implement-long-link-or-half-long-link-by-httpclient

**Comment by LittlePanpc** [comment]
@smarek
This url is linked to my question, Sir. I want help ASAP badly. So I ask this question here.

**Comment by smarek** [comment]
1) You do not want, but need the hel asap badly
2) github issues is only for library problems only or features proposal
3) we are not here to do your work for you

**Comment by LittlePanpc** [comment]
My apologies, Sir. I didn't mean it. I'm a loyal supporter of android-async-http, confused about the long-link question in my mind. Sorry about misunderstandings.

**Comment by smarek** [comment]
It's ok, no offense taken.
