### ISSUE TITLE
302 redirect abnormal

### ISSUE THREAD

**Issue by wxlfight** [loopj/android-async-http#790]
![screen shot 2015-01-16 at 10 35 00 am](https://cloud.githubusercontent.com/assets/5794010/5770796/ea6a2e6a-9d6b-11e4-89d0-af932f4c8fa0.png)

I don't know why async-http get the response of 302, but request the origin host instead of the redirect url, after several request like this, async-http get timeout. As a matter of fact, the redirect finally can finish successfully.

This is my code:
```java

AsyncHttpClient client = new AsyncHttpClient();
client.setConnectTimeout(60*1000);  //default 60s
client.setResponseTimeout(60*1000);

```

Mybe this is not the problem of async-http but can @smarek give me some advice?

**Comment by fineswap** [comment]
@wxlfight
HTTP 302 status code is sent by the server, so you need to check why this is happening. For starters, you might want to POST the data (as you do now) to http://httpbin.org/post and check what you're getting. Is this what you're expecting?

**Comment by wxlfight** [comment]
I'm sorry for my poor English, I try to describe these process:
-->192.168.253.9 post data to 115.238.155.105
-->115.238.155.105 response to 192.168.253.9 with 302 redirect which redirect url is http://a.json (just for example)
then async-http should request to http://a.json, but it didn't. async-http request 192.168.253.9 again and again, just like the picture says, i don't know why this happend ? 

BTW, this problem is happend sometimes, not always

**Comment by smarek** [comment]
@wxlfight try set up correct values in `setEnableRedirects(final boolean enableRedirects, final boolean enableRelativeRedirects, final boolean enableCircularRedirects)` in `AsyncHttpClient`

**Comment by wxlfight** [comment]
I have add this code:

```java
client.setEnableRedirects(true);
client.getHttpClient().getParams().setParameter(ClientPNames.MAX_REDIRECTS, 3);
```

i will have a try and see if this problem would happen again
