### ISSUE TITLE
JsonHttpResponseHandler ParseResponse function has redundant code

### ISSUE THREAD

**Issue by ASCE1885** [loopj/android-async-http#791]
Function ParseResponse in class JsonHttpResponseHandler has redundant code, getResponseString in the parent class has process the UTF-8 BOM prefix,there is no need to do it again in ParseResponse,the function can be simplified as below:

    protected Object parseResponse(byte[] responseBody) throws JSONException {
        if (null == responseBody)
            return null;
        Object result = null;
        //trim the string to prevent start with blank, and test if the string is valid JSON, because the parser don't do this :(. If JSON is not valid this will return null
        String jsonString = getResponseString(responseBody, getCharset());
        if (jsonString != null) {
            jsonString = jsonString.trim();	
            if (jsonString.startsWith("{") || jsonString.startsWith("[")) {
                result = new JSONTokener(jsonString).nextValue();
            }
        }
        if (result == null) {
            result = jsonString;
        }
        return result;
    }

**Comment by smarek** [comment]
That's correct, thank you for noticing. I've fixed that in fccf6f22e7dd20556c868e420d16b2eb83d9bfbe

**Comment by pswami** [comment]
How do you use parseResponse to get JSONObject? What goes in the parameter for byte[] responseBody?
