### ISSUE TITLE
Is there a way to monitor connexion ?

### ISSUE THREAD

**Issue by NameX44** [loopj/android-async-http#798]
Hey, 

is there a way to monitor connexion loss/re-establish. (without sending a request)

Thank you,

**Comment by smarek** [comment]
You mean network state? Eg. getting info when you lose wireless, cellular-data, or both, and when you regain them?

**Comment by NameX44** [comment]
yes !

**Comment by smarek** [comment]
That's not question of this library, use the official way, documented here: 
https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

**Comment by NameX44** [comment]
Oops sorry, didn't know that we could check it by broadcast receiver ! Thank you !

**Comment by smarek** [comment]
You're welcome :)
