### ISSUE TITLE
HTTPS requests 

### ISSUE THREAD

**Issue by SuperHich** [loopj/android-async-http#804]
Hi,

Does it supports HTTPS requests, for downloading secured files ?

Thx in adavance.

**Comment by fineswap** [comment]
@SuperHich 

Yes, of course it does. Also custom certification. See [here](https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/CustomCASample.java) for an example.
You can always clone and run the examples.

**Comment by SuperHich** [comment]
Many thanks :+1:  
I confirm that this library support HTTPS too
