### ISSUE TITLE
Uploading 16 images

### ISSUE THREAD

**Issue by nove1398** [loopj/android-async-http#805]
After attempting to upload 16 images + 16 other text data keys as a RequestParams object, the receiving back end PHP implementation fails to detect a param that was posted as "operation"
$_REQUEST['operation'] <<< this value is not being seen to the script.

Is the RequestParams object I created too large to be processed this way? Maybe timeout is in play here which cuts the process?

**Comment by smarek** [comment]
This is not question regarding the library, but PHP processing of the request. Use stackoverflow.com for such questions.
