### ISSUE TITLE
Is this possible to handle twitter API?

### ISSUE THREAD

**Issue by FrancisSimon** [loopj/android-async-http#811]
i am trying to call the twitter api with the help of async httpclient .i don't know how to form the Headers, can you please help me to sort out this problem

**Comment by KeizerDev** [comment]
Have you looked at this https://github.com/loopj/android-async-http/issues/761

**Comment by smarek** [comment]
This is out of scope question, use stackoverflow.com for such questions.

**Comment by FrancisSimon** [comment]
sorry guys i hadn't used Retrofit so that's why i asked this question now i used the retrofit to fix the issue
