### ISSUE TITLE
Crash in com.loopj.android.http.TextHttpResponseHandler

### ISSUE THREAD

**Issue by abdullahumer** [loopj/android-async-http#812]
Hi, I faced a crash in v1.4.6.

I did not face this crash in older versions.

```java
java.lang.OutOfMemoryError
       at java.lang.String.<init>(String.java:265)
       at java.lang.String.<init>(String.java:238)
       at com.loopj.android.http.TextHttpResponseHandler.getResponseString(TextHttpResponseHandler.java:117)
       at com.loopj.android.http.JsonHttpResponseHandler.parseResponse(JsonHttpResponseHandler.java:217)
       at com.loopj.android.http.JsonHttpResponseHandler$1.run(JsonHttpResponseHandler.java:121)
       at java.lang.Thread.run(Thread.java:856)

**Comment by fineswap** [comment]
@abdullahumer 

Thanks for your issue. However, it's not sufficient to find a solution as the problem may arise from so many factors, especially from code in your app. From the looks of, it could be due to a large data set returned by the server.

Do you know how big the data set returned by the server is?
Does this happen immediately after starting the app or after some time? (app eating memory?)
Could you do a memory analysis and see if your app leaks memory?

**Comment by smarek** [comment]
@abdullahumer if you run into OutOfMemoryError, you should save the response into file first (eg. through FileAsyncHttpResponseHandler) and then parse it, because otherwise both the data (server response) and parsing results are stored in memory, which can cause the original OOM error

**Comment by abdullahumer** [comment]
I could not find the exact reason for the crash for now.

@smarek To me it seems as if the crash is in the JsonHttpResponseHandler. When it tries to parse the response, it crashes with OutOfMemoryError before coming into the callback in my code.

The data size from server seems not to be the issue because the same server APIs are being used in our iOS app and are working fine. We never faced this crash in iOS app.

@fineswap Reply to your questions:
Do you know how big the data set returned by the server is?
==> Nop.

Does this happen immediately after starting the app or after some time? (app eating memory?)
==> This does not seem to be happening on startup because average session time of users on app is around 8 minutes. App eating memory? Can't say for sure.

Could you do a memory analysis and see if your app leaks memory?
==> I'm new in Android development and for now don't know how to do that. I will try some googling. Any help from you regarding this will be highly appreciated.

Thanks!

**Comment by smarek** [comment]
`The data size from server seems not to be the issue because the same server APIs are being used in our iOS app and are working fine. We never faced this crash in iOS app.` how is it used in iOS?

Again, the advice, store the response first, then parse it into JSON

**Comment by abdullahumer** [comment]
in iOS, we did not store the response. We are using AFNetworking library. Upon receiving the responseString, it is then parsed into JSON.

I will try the FileAsyncHttpResponseHandler(). After releasing an update, we can know the results.

**Comment by smarek** [comment]
@abdullahumer we're not going to debug your problem of usage, memory requirements and usage is different on different devices and using different code. It's not that directly comparable.

**Comment by abdullahumer** [comment]
That is the reason I cannot find the exact reason for the crash. I'm getting around 20 crashes per day with 25k daily active users.

Not that critical issue but I posted it here because the trace was in JsonHttpResponseHandler.

I checked and some newer devices with 2GB ram were also affected.

Thanks!

**Comment by smarek** [comment]
Size of RAM is not important, important is size of your application memory heap, which can be 8, 16, 32, 64m or with largeHeap set in manifest it can go higher

**Comment by abdullahumer** [comment]
I have set `android:largeHeap="true"` in app Manifest.

**Comment by smarek** [comment]
Before or after the crash? If after, does crash still happen?

**Comment by abdullahumer** [comment]
It was set long before the crash.

I also did some memory testing using Memory Monitor on my Nexus 5 device. The total allocated memory fluctuates between 120MB-140MB. When the allocated memory reaches 120MB, it then starts releasing older cached images/objects.

Does this mean that my app is working fine regarding memory management?

**Comment by smarek** [comment]
Can't say, and that is really out of scope of this support forum.
On different devices the largeHeap will allow you to allocate different amount of memory.
When you look into memory monitor, see where the allocations are placed, and to be sure, try writing simple `test-case` where you'd have no graphics and no other processing than AAH library.

Also you're using `JsonHttpResponseHandler` which uses default Android version of JSON implementation, you could try switching to `BaseJsonHttpResponseHandler` and use JacksonJSON library instead. See the sample: https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/JsonSample.java

I'm closing this issue, and if you will create simple test case (such as downloading the JSON from github and crashing the application on Nexus 5 which I do have to test with) I'll reopen it.
Until then, go with stackoverflow.com forum or just try to debug the issue on your application side.

We've never had problems with memory allocations, and library for does not contain any memory leaks (from what we know). Also you could try to save the response first and then parse it from cache directory or so, that should help you get rid of it.
