### ISSUE TITLE
Why not RequestParams.put() method not support  boolean value but not throw Error？

### ISSUE THREAD

**Issue by wwwjiandan** [loopj/android-async-http#813]
Why not RequestParams.put() method not support  boolean value but not throw Error？
the loopj version I used is 1.4.4

when I use looj post http request,I need post many params.One time I use requestParams.put(String,boolean)，Eclipse never throw any code error,but when I Log.i(TAG,requestParams.toString()),the boolean values's params never be contains.I want to know why?

**Comment by smarek** [comment]
please test with 1.4.6, we don't support old versions

**Comment by wwwjiandan** [comment]
OK.
