### ISSUE TITLE
MalformedURLException during the get request

### ISSUE THREAD

**Issue by ahmtbrk** [loopj/android-async-http#815]
<b>mClient.get(mContext, getAbsoluteUrlForBase(homePhotoUrl), asyncResponseHandler);</b>
that I tried the get request on the postman plugin,i haven't problem.But tried with async-http 1.4.6,client returned these errors;
<b>java.net.MalformedURLException: No valid URI scheme was provided
at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:144)</b>
please help me.good works

**Comment by ahmtbrk** [comment]
i found the problem.
if AsyncHttpClient setURLEncodingEnabled true,this situation is disturbing url.
that i setted false value,the problem fixed.

**Comment by fineswap** [comment]
Great, good to know, @ahmtbrk.

**Comment by backListed** [comment]
it wasn't worked in my case
