### ISSUE TITLE
CustomCASample apparently does not verify host names

### ISSUE THREAD

**Issue by nullEuro** [loopj/android-async-http#816]
Hello,

I wanted to use a self-signed certificate with this library. I found the CustomCASample, followed the instructions and get the HTTP requests working. However, I noticed that the hostname is not verified. 
The `SecureSocketFactory` delegates `createSocket` to another factory without calling the hostname verifier.

Maybe am I overlooking something, comments are appreciated!

**Comment by fineswap** [comment]
@nullEuro 

That part of the verification is already embedded into the Android subsystem. However, if Android is having trouble verifying a hostname (no support for SNI, for example), you could weave a verifier yourself.

Take a look here for more information: https://developer.android.com/training/articles/security-ssl.html#CommonHostnameProbs

**Comment by nullEuro** [comment]
Thanks for the comment, but I had the opposite problem: host names are *not* verified. The sample uses
`setHostnameVerifier(SSLSocketFactory.STRICT_HOSTNAME_VERIFIER);` but that has no effect, *every* host name is accepted.

**Comment by fineswap** [comment]
@nullEuro 
That sounds strange to me. Could you make a test such that the server sends a different certificate than the hostname it's installed on? At least Android should not accept that.

**Comment by nullEuro** [comment]
> At least Android should not accept that.

Not necessarily. As stated in the [docs](https://developer.android.com/training/articles/security-ssl.html#WarningsSslSocket) you linked earlier, using raw SSLSockets surpasses the verification.
The sample `SecureSocketFactory` extends `org.apache.http.conn.ssl.SSLSocketFactory` and overrides the `createSocket()` methods. If you look at the [source code](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpclient/4.0/org/apache/http/conn/ssl/SSLSocketFactory.java#399) of the original method you can see that it calls the hostnameVerifier itself because internally raw sockets are used. The method is overridden without calling the verifier.

**Comment by fineswap** [comment]
@nullEuro 
You might be on to something there. Would you like to submit a pull request which addresses and fixes this problem?

**Comment by nullEuro** [comment]
Sure!
