### ISSUE TITLE
Open next activity when Asynchronous task is done.

### ISSUE THREAD

**Issue by KeizerDev** [loopj/android-async-http#817]
Hi,

I'm busy with an app where is want to have a loader screen and a main screen. When everything is loaded and put in the database I want to start the MainActivity.
```
            login("", username, password);
            startActivity(mainIntent);
            finish();
```
But when I run this code, it opens the MainActivity and in my LogCat I see it's still downloading things. How do i fix this?

Thanks.

**Comment by fineswap** [comment]
@KeizerDev 
Sorry, but this is beyond the scope of this library. You can ask on StackOverflow, for example.
