### ISSUE TITLE
URL domain might be REPLACED by another one during sending http request

### ISSUE THREAD

**Issue by liumingkong** [loopj/android-async-http#818]
for example,  I met a req flow like below:
AsyncHttpClient.get("http://www.a.com/test1");
AsyncHttpClient.get("http://www.b.com/test2");
AsyncHttpClient.get("http://www.b.com/test2");
AsyncHttpClient.get("http://www.a.com/test1");

sometimes, I found 
in www.a.com server, it received: http://www.a.com/test2
in www.a.com server , it received: http://www.b.com/test1

version 1.4.5 

plz HELP  HELP  HELP!!!:)

**Comment by smarek** [comment]
Can you provide us sample code, which will trigger the error? What you described is flow in your application, and URL is not manipulated through the library at all, so I presume this is problem with your code.

**Comment by liumingkong** [comment]
Thanks your reply,this is my code ：

private AsyncHttpClient httpClient;

httpClient = new AsyncHttpClient();
httpClient.setEnableRedirects(false);
httpClient.setMaxConnections(20);
httpClient.setTimeout(10000);

this is a req flow: （After starting the app, the code is called）

RestClient.INSTANCE.httpClient.get(applicationContext, "http://www.a.com/api/users/show", requestParams,  new UsersShowHandler());
RestClient.INSTANCE.httpClient.post(applicationContext, "http://www.a.com/api/users/photowall", requestParams,  new UsersShowHandler());
RestClient.INSTANCE.httpClient.post(applicationContext, "http://www.a.com/api/signup/type", requestParams,  new UsersShowHandler());
RestClient.INSTANCE.httpClient.get(applicationContext, "http://www.b.com/endpoint.json", requestParams,  new UsersShowHandler());
RestClient.INSTANCE.httpClient.get(applicationContext, "http://www.b.com/sticker.json", requestParams,  new UsersShowHandler());

I hide our app domain.

Then came the phenomenon described above：Sometimes:
ngnix www.a.com receive: "http://www.a.com/endpoint.json or http://www.a.com/sticker.json like this
ngnix www.b.com receive:"http://www.b.com/api/users/photowall or http://www.b.com/api/users/show or... 

The vast majority are correct，the amount of error is small.

I in the test is no way to reproduce this problem， but truly happened..... 
Both servers no association， In fact, the earliest we have three domains, the same problem occurred... 

Thanks so great open source project, gave us great help. Thank you very much！
And plz HELP ：-)

**Comment by ff0o0** [comment]
I have the same question, have you solved? @liumingkong

**Comment by smarek** [comment]
As I already said, we couldn't reproduce the problem, and it's not happening for us.
If anybody will be able to reproduce the problem and give out instructions on how to reliably reproduce it, we can look into it again and fix it, until then we can do nothing about this problem.
