### ISSUE TITLE
org.apache.http.conn.ConnectTimeoutException not caught in onFailure

### ISSUE THREAD

**Issue by Jdruwe** [loopj/android-async-http#826]
I am experiencing the following issue:

- Wifi enabled
- Server down
- Version 1.4.6
- org.apache.http.conn.ConnectTimeoutException: Connect to MY_SERVER_IP timed out
 - Response not caught in on onFailure method

I found multiple post around this topic but they all suggest to implement a specific onFailure:

```
@Override
public void onFailure(Throwable error, String content) {
     if ( error.getCause() instanceof ConnectTimeoutException ) {
         System.out.println("Connection timeout !");
     }
}
```

Only the following onFailure methods are availble and neither one of them get called when a ConnectTimeoutException is raised.

![onfailuremethods](https://cloud.githubusercontent.com/assets/4804496/6634837/88fe6a3c-c95e-11e4-8d26-8311c31436ec.PNG)

Console output:

```
D/OpenGLRenderer﹕ Enabling debug mode 0
I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@4265de00 time:57322873
W/System.err﹕ org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.50.205:3000 timed out
W/System.err﹕ at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
V/JsonHttpResponseHandler﹕ response body is null, calling onFailure(Throwable, JSONObject)
```

**Comment by Jdruwe** [comment]
It gets caught in:

public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {

Please close this issue!

**Comment by Akshitha789** [comment]
Hi All,

I have tried through com.loopj.asynchttpclient 1.4.4 and 1.4.6 .. works well on Emulator.. But does throws Connect Timeout error from device - HTC Android 4.4.2 API 19. Any help will be greatly appreciated. Thanks in advance.

org.apache.http.conn.ConnectTimeoutException: Connect to /192.164.1.18:8080 timed out
W/System.err: at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
W/System.err: at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
W/System.err: at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/System.err: at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/System.err: at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:367)
W/System.err: at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
W/System.err: at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:519)
W/System.err: at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
W/System.err: at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
W/System.err: at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
W/System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err: at java.lang.Thread.run(Thread.java:864)
