### ISSUE TITLE
callback hell

### ISSUE THREAD

**Issue by kingaza** [loopj/android-async-http#829]
I am using this library and love it. 
Now I am facing a problem, that my app is based on OAuth, which means, if the token is expired, any request will return a 401 error. Then I have to reflesh the token, and send the request again.
So, I want to know, if there is a better way (like RxJava) than this nested callbacks?
Thanks a lot.

**Comment by kingaza** [comment]
This issue looks identical to another issue #408, however, I want to modify the token value which is used in the latter request. So, there is only one way of callback function...

**Comment by abhip** [comment]
Did you take a look at refresh token in OAuth 2 ? Using refresh token you can void requesting a new token again. - More info https://developers.google.com/accounts/docs/OAuth2WebServer#refresh

**Comment by smarek** [comment]
This is not a direct library issue, please use stackoverflow.com for such questions, as those are out-of-scope in here. Thank you
