### ISSUE TITLE
Bad Request 502 only on certain phones when using mobile carrier connection

### ISSUE THREAD

**Issue by the-bham** [loopj/android-async-http#831]
When sending post requests I receive a Bad Request 502 response only when using mobile carrier connection. When on wifi the post works fine. This issue only happens on certain phones for exampple works fine regardless of connection on galaxy nexus, but doesnt work when only on mobile connection on a note 4/nexus 5.

**Comment by smarek** [comment]
Can you add more info? How large request, against which backend, any more debug info from LogCat, used version of library, etc...

If it's only certain phones and certain use-cases, we'll have to be able to reproduce the issue in our dev environment, or there is no way for us to fix it.

**Comment by the-bham** [comment]
so the problem was that ipv6 was not properly configured on my server.

it appears that the newers phones use ipv6 when connecting to my server when on mobile connection, but used ipv4 over wifi. the older phones used ipv4 on both types of connections.

once i configured ipv6 on my server properly, the mobile connection would work on the newer phones.

**Comment by smarek** [comment]
Ok, thank you for follow up.
Can you please share what was wrong with IPv6 configuration on backend for others to know?
Closing this issue, as resolved on your side.
