### ISSUE TITLE
How to download files with range?

### ISSUE THREAD

**Issue by luohaohaha** [loopj/android-async-http#832]
Like title

**Comment by abhip** [comment]
Using range header fields. Set the range in these header fields while making the request 
More info - http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.12

**Comment by smarek** [comment]
Already implemented, see the Sample here:
https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/RangeResponseSample.java
