### ISSUE TITLE
PATCH in 1.4.7?

### ISSUE THREAD

**Issue by dkozel** [loopj/android-async-http#835]
Hello,

1.4.7-SNAPSHOT did not include the PATCH code merged in 305aa67b576d9418aa811acfa868492f33854f37. Will the 1.4.7 release include it? Are you basing the release on the current master HEAD or an older revision?

Thank you for the very useful library.

**Comment by smarek** [comment]
Hi, yes, PATCH was implemented after GIT TAG 1.3.6, thus will be released in TAG 1.3.7.
Snapshots are based on current master HEAD, releases on GIT tags.

I've just updated Snapshots, but to release we're missing few tickets to resolve.
https://oss.sonatype.org/content/repositories/snapshots/com/loopj/android/android-async-http/1.4.7-SNAPSHOT/
