### ISSUE TITLE
Content_Type Error when using HttpEntity

### ISSUE THREAD

**Issue by wayhap** [loopj/android-async-http#838]
this update:
https://github.com/loopj/android-async-http/commit/8f396c883d63d5c0db6ec4f36a063c21f635690f

这个修改会导致：如果用户没有设置HttpEntity的ContentType,最终请求中就没有ContentType,从而出错。
请改成：
i'm sorry about my English. If user didn't set ContentType in HttpEntity,this update will cause no ContentType in HttpRequest Header. please fix it like this:
```java
if (contentType != null) {
            if (uriRequest instanceof HttpEntityEnclosingRequestBase && ((HttpEntityEnclosingRequestBase) uriRequest).getEntity() != null&&uriRequest.containsHeader(HEADER_CONTENT_TYPE)) {
                Log.w(LOG_TAG, "Passed contentType will be ignored because HttpEntity sets content type");
            } else {
                uriRequest.setHeader(HEADER_CONTENT_TYPE, contentType);
            }
        }
```

**Comment by smarek** [comment]
Thank you, indeed nice suggestion. I'll try to push it forward in a matter of days.
