### ISSUE TITLE
How to trace the percentage of data uploaded

### ISSUE THREAD

**Issue by brxren** [loopj/android-async-http#839]
When I use AsyncHttpClient to post an image to the server, I want to know how many bytes have been uploaded. Is there a way that helps me?

**Comment by brxren** [comment]
After I read the source code, I find it might not be implemented. And after I search among the issues, I confirm that it's not supported yet.

**Comment by smarek** [comment]
If you do use RequestParam to fill the HttpEntity in, it is possible to listen in `onProgress()` method in callback, that's provided. Listening to progress of custom entities is currently not supported.
I shall add an example to Sample application, so it's more obvious.
