### ISSUE TITLE
Unable to request any site over HTTPS

### ISSUE THREAD

**Issue by zachrattner** [loopj/android-async-http#841]
I get an SSLPeerUnverifiedException exception with every HTTPS site I've tried. The site I'm working with has an A+ score on Qualys's SSL test, and I tried some common sites (github.com, instagram.com) too. Shouldn't HTTPS "just work" on sites with complete certificate chains?

Test code:

    try
    {
      KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
      trustStore.load(null, null);
      MySSLSocketFactory socketFactory = new MySSLSocketFactory(trustStore);
      socketFactory.setHostnameVerifier(MySSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
      AsyncHttpClient client = new AsyncHttpClient();
      client.setTimeout(30*1000);
      client.setSSLSocketFactory(socketFactory);
      client.get("https://www.github.com", new AsyncHttpResponseHandler() {
          @Override
          public void onFailure(int arg0, Header[] arg1, byte[] arg2,
              Throwable arg3)
          {
            Log.e(TAG, "FAILED");
          }

          @Override
          public void onSuccess(int arg0, Header[] arg1, byte[] arg2)
          {
            Log.e(TAG, "SUCCESS");
            
          }
      });
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }

Exception:

    W/System.err(21382): javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
    W/System.err(21382): 	at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
    W/System.err(21382): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
    W/System.err(21382): 	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
    W/System.err(21382): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:214)
    W/System.err(21382): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:167)
    W/System.err(21382): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
    W/System.err(21382): 	at org.apache.http.impl.client.DefaultRequestDirector.executeSB(DefaultRequestDirector.java:831)
    W/System.err(21382): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:697)
    W/System.err(21382): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
    W/System.err(21382): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
    W/System.err(21382): 	at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
    W/System.err(21382): 	at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
    W/System.err(21382): 	at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
    W/System.err(21382): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    W/System.err(21382): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    W/System.err(21382): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    W/System.err(21382): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    W/System.err(21382): 	at java.lang.Thread.run(Thread.java:818)

**Comment by smarek** [comment]
This error comes from another place, than this library. If server certificate (ie. StartCom) isn't in device trusted SSL roots, this issue will pop up.
You can provide your own SSLSocketFactory, which will validate against your certificates bundle, which will give you certainity about SSL certificate validation.

SSL requests work by default with this library, it's usually device configuration / network path problem, we have to deal with.

**Comment by zachrattner** [comment]
Is there any chance loopj is built on top of the Apache HTTP libraries? If so, I think the issue is because my server was using SNI because it didn't have a unique IP. Once I updated the server to have a unique IP, the client code started working. 

More details on my SO post: http://stackoverflow.com/questions/29763500/how-to-support-comodo-ssl-cert-in-loopj-on-android

Long story short, perhaps loopj should support SNI?

**Comment by smarek** [comment]
Yes, this is plan for 1.5 branch, which is currently under development, to build on top of HttpClient 4.3.X which is specifically repackaged for Android to be used with. See i.e. #775 for reference, and all the tickets marked up for 1.5.0 milestone ( https://github.com/loopj/android-async-http/issues?utf8=%E2%9C%93&q=milestone%3A1.5.0+ )

**Comment by KSas** [comment]
Can you give an example how to use SNI with this library??

**Comment by smarek** [comment]
SNI support was added in upstream HttpClient in version 4.3.2 (see https://issues.apache.org/jira/browse/HTTPCLIENT-1119 )
So if you're using 1.4.9 version of this library, which uses upstream HttpClient 4.3.6, there is nothing special you need to do to get SNI working.

**Comment by KSas** [comment]
I try this with 1.4.9 but the LogCat says:

```javascript
09-25 13:05:04.432    3299-3555/de.test.debug W/System.err﹕ javax.net.ssl.SSLException: hostname in certificate didn't match: <apps.mydomain.de> != <www.othermydomain.de> OR <www.othermydomain.de>
09-25 13:05:04.432    3299-3555/de.test.debug W/System.err﹕ at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:233)

**Comment by smarek** [comment]
Which means your SSL certificate is probably invalid? Try running ssllabs.com test against your subdomain

**Comment by KSas** [comment]
SSLLabs says:

[...]
Overall Rating: B
This site works only in browsers with SNI support.
Trusted: yes
[...]

**Comment by JuhaniLehtimaeki** [comment]
I'm rung into this same issue. It looks to me that SSL wildcards are not handled correctly in this library.
