### ISSUE TITLE
 Needs a more precise logcat

### ISSUE THREAD

**Issue by kamilwlf** [loopj/android-async-http#843]
I have a strange question. Needs trick and tips.

Got the message:
``` / com./ JsonHttpResponseHandler: onSuccess (int, Header [], JSONObject) was not overriden, but you received callback```

I have implemented about 20 different request to the server. How can I find the lines of code from which it was called?

**Comment by smarek** [comment]
Hi, it's hard to have more specific log message, unless, we'd provide way to supply your own LogCat TAG, which is of course an option.
If you know, what the message means, you should check all your JsonHttpResponseHandler callbacks implementations (and subclasses) if they have overidden this specific method, or not.

Log comes from here: https://github.com/loopj/android-async-http/blob/1.4.6/library/src/main/java/com/loopj/android/http/JsonHttpResponseHandler.java#L66

**Comment by kamilwlf** [comment]
thank you for your response,

``` we'd provide way to supply your own LogCat TAG, which is of course an option.```

what do you mean? Can you provide a link on how to do it?

Can I add my own tag , directly to your?

**Comment by smarek** [comment]
Not yet, it's just an idea, we can add to track as future added feature.

**Comment by kamilwlf** [comment]
Ok.
Thank you once more for your help in this matter.
