### ISSUE TITLE
JsonHttpResponseHandler never calls onSuccess or onFailure

### ISSUE THREAD

**Issue by QuentinGuillout** [loopj/android-async-http#844]
# The app code

```
public static void init() {

		client = new AsyncHttpClient();

		client.setMaxConnections(50);
		client.setMaxRetriesAndTimeout(10, AsyncHttpClient.DEFAULT_SOCKET_TIMEOUT*10);
		client.setThreadPool((ThreadPoolExecutor)Executors.newCachedThreadPool());

	}
```

```
public static void get(String url, RequestParams params, AsyncHttpResponseHandler responseHandler) {

		// BUGGY
		//client.setBasicAuth(BASE_USER, BASE_PWD);
		checkIfClientIsNull();
		//		init();
		addAuthToClient();
		client.get(getAbsoluteUrl(url), params, responseHandler);
	}
```
```
public static void checkIfClientIsNull() {
		if (client == null) {
			init();
		}
	}
```

```
public static void addAuthToClient() {
		client.removeAllHeaders();
		client.addHeader(
				"Authorization",
				"Basic " + Base64.encodeToString(
						(BASE_USER+":"+BASE_PWD).getBytes(),Base64.NO_WRAP)
				);
	}
```

```
public static void updateUserNotificationsAndDoActions(final Context context) {

		get("MY_URL", null, new JsonHttpResponseHandler(){
			@Override
			public void onSuccess(int statusCode, Header[] headers,
					JSONObject response) {

				LogGM.e("RELOAD NOTIFICATIONS SUCCESS 1");
                super.onSuccess(statusCode, headers, response);
			}

			@Override
			public void onSuccess(int statusCode, Header[] headers,
					JSONArray response) {
				LogGM.e("RELOAD NOTIFICATIONS SUCCESS 2");
				super.onSuccess(statusCode, headers, response);
			}

			@Override
			public void onSuccess(int statusCode, Header[] headers,
					String responseString) {
				LogGM.e("RELOAD NOTIFICATIONS SUCCESS 3");
				super.onSuccess(statusCode, headers, responseString);
			}

			@Override
			public void onPostProcessResponse(
					ResponseHandlerInterface instance, HttpResponse response) {
				LogGM.e("RELOAD NOTIFICATIONS POSTPROCESS");
				super.onPostProcessResponse(instance, response);
			}

			@Override
			public void onPreProcessResponse(ResponseHandlerInterface instance,
					HttpResponse response) {
				LogGM.e("RELOAD NOTIFICATIONS PREPROCESS");
				super.onPreProcessResponse(instance, response);
			}

			public void onProgress(int bytesWritten, int totalSize) {
				LogGM.e("RELOAD NOTIFICATIONS PROGRESS");
			};

			@Override
			public void onRetry(int retryNo) {
				LogGM.e("RELOAD NOTIFICATIONS RETRY");
				super.onRetry(retryNo);
			}

			@Override
			public void onStart() {
				LogGM.e("RELOAD NOTIFICATIONS START");
				super.onStart();
			}

			@Override
			public void onCancel() {
				LogGM.e("RELOAD NOTIFICATIONS CANCEL");
				super.onCancel();
			}

			@Override
			public void onFailure(int statusCode, Header[] headers,
					String responseString, Throwable throwable) {
				LogGM.e("RELOAD NOTIFICATIONS FAILURE 1");
				super.onFailure(statusCode, headers, responseString, throwable);
			}

			@Override
			public void onFailure(int statusCode, Header[] headers,
					Throwable throwable, JSONArray errorResponse) {
				LogGM.e("RELOAD NOTIFICATIONS FAILURE 2");
				super.onFailure(statusCode, headers, throwable, errorResponse);
			}

			@Override
			public void onFailure(int statusCode, Header[] headers,
					Throwable throwable, JSONObject errorResponse) {
				LogGM.e("RELOAD NOTIFICATIONS FAILURE 3");
				super.onFailure(statusCode, headers, throwable, errorResponse);
			}

			@Override
			public void onFinish() {
				LogGM.e("RELOAD NOTIFICATIONS FINISH");
				super.onFinish();
			}

			@Override
			protected Message obtainMessage(int responseMessageId,
					Object responseMessageData) {
				LogGM.e("OBTAIN MESSAGE "+responseMessageId);
				return super.obtainMessage(responseMessageId, responseMessageData);
			}

			@Override
			protected Object parseResponse(byte[] responseBody)
					throws JSONException {
				LogGM.e("PARSE RESPONSE");
				return super.parseResponse(responseBody);
			}

			@Override
			protected void handleMessage(Message msg) {
				LogGM.e("HANDLE MESSAGE "+msg.toString());
				super.handleMessage(msg);
			}

			@Override
			public void sendResponseMessage(HttpResponse httpResponse)
					throws IOException {
				LogGM.e("SEND RESPONSE MESSAGE "+httpResponse.getStatusLine());
				super.sendResponseMessage(httpResponse);
			}

			@Override
			protected void sendMessage(Message msg) {
				LogGM.e("SEND MESSAGE "+msg.toString());
				super.sendMessage(msg);
			}

		});


	}
```

# The logs
```
OBTAIN MESSAGE 2
SEND MESSAGE { when=-3d6h30m43s588ms what=2 target=com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler }
HANDLE MESSAGE { when=-18ms what=2 target=com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler }
RELOAD NOTIFICATIONS START
RELOAD NOTIFICATIONS PREPROCESS
SEND RESPONSE MESSAGE HTTP/1.1 200 OK
OBTAIN MESSAGE 4
SEND MESSAGE { when=-3d6h30m43s714ms what=4 obj=[Ljava.lang.Object;@42cae398 target=com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler }
OBTAIN MESSAGE 0
SEND MESSAGE { when=-3d6h30m43s729ms what=0 obj=[Ljava.lang.Object;@42b79d90 target=com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler }
RELOAD NOTIFICATIONS POSTPROCESS
OBTAIN MESSAGE 3
SEND MESSAGE { when=-3d6h30m43s732ms what=3 target=com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler }
```

# The "MY_URL" response (in a navigator)
I can't give you the url I'm using for this request but I can tell you that it starts with "http://", it works in a navigator and the response is this :
```
{"error":"4"} 
```

As you can see **it never goes in onSuccess or onFailure no matter how long I wait**.

The weird thing is that **my app is doing the exact same request at the launch of the app and it works** (with the same response as above).

What I have tried with no more success :
- Launching this request multiple times (50 or so)
- Commenting the lines under "client = new AsyncHttpClient();" in "init()" function
- Reinitializing the client for each get request
- Not doing the first working request with this url at the start of the app

# Useful (or not) informations
- I use Eclipse, I compile with Android API 21 (and tried as well with API 22)
- I use android-async-http-1.4.6.jar (and I have tried with android-async-http-1.4.5.jar)
- I use Facebook SDK
- I use the same client for every request in the app and quite successfully until now
- I tried this on Galaxy S4 and LG G2 Mini with the same results

This is a very serious problem for my app and I thank you very much in advance for any help given.

**Comment by smarek** [comment]
Wow, very nice report, thank you for that.
Could you please, just for test, use the 1.4.7 snapshot 4 from here: https://oss.sonatype.org/content/repositories/snapshots/com/loopj/android/android-async-http/1.4.7-SNAPSHOT/android-async-http-1.4.7-20150403.133103-4.jar (see the folder, or add to Maven as dependency source, it's listed in README.md)

Also, from the report you've got messages in this order `2, 4, 0, 3` which translates to `START, PROGRESS, SUCCESS, FINISH` (see the head of implementation `AsyncHttpResponseHandler`)

Which means, there should be either onSuccess callback you haven't overriden (these logs were added in 1.4.6 so you should see them), or onFailure callback, if the response couldn't be parsed.

You could also attach debugger to JsonHttpResponseHandler `parseResponse` method, and see what processing the method does with response data (and what response data those are).

For better idea, about what is going on, see the tagged version of this repository (tags do exist for 1.4.5 and 1.4.6 versions)

Three more things:
  - Try running our Sample application (see repository root, folder sample) against your HTTP server, and see if JSON GET sample works correctly (which usually means, there is another problem in your current application)
  - If you could provide us with test environment (http endpoint) and code which can simulate the bug, I could test it directly
  - Try running the same code (which is nice processing debug, we could add to library itself), against https://httpbin.org/get which also returns valid JSON message, the library will parse it correctly
  - If the application runs against your endpoint fine once, but not second time, is it possible the response is different, or your AAH library usage is different? (i.e. different context, thread, callback context, ...)

**Comment by QuentinGuillout** [comment]
You're welcome ! Thank you for your very detailed and quick answer.


I have tried the .jar but it didn't make any change but your answer made me reconsider what could be the cause of this problem and I finally found the problem :


It turns out I was calling my `updateUserNotificationsAndDoActions(final Context context)` function from the `onHandleIntent(Intent intent)` function of an `IntentService` (this intent service was called upon receiving a push notification) and the solution was to send a broadcast and then receiving the broadcast in a `BroadcastReceiver` located in the `Application` class of my Android app (because I need this to be received from any place in the app) and then call my function from this `BroadcastReceiver`.


Problem solved ! Thank you again for your quick and useful help and to any other person reading this thread **do not do a request with this library in an `IntentService`, use a `BroadcastReceiver` and do it from an `Activity` or `Application` class.**

**Comment by smarek** [comment]
Great, thank you for feedback, this is known use-case, where you should use synchronous requests, see for reference this example: 
https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/IntentServiceSample.java
along with IntentService implementation https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/services/ExampleIntentService.java

I'm closing as solved
