### ISSUE TITLE
Did android-async-http support PUT and DELETE method

### ISSUE THREAD

**Issue by csrgxtu** [loopj/android-async-http#845]
I am wondering did android-async-http support PUT and DELETE HTTP method? also, support PUT and DELETE parameters in android?

I have used the Apache HttpClient in pure Java, all methods works fine, but when used in the Android, got Runtime Exceptions.

**Comment by onurkoncaoglu** [comment]
it's already support them.

**Comment by smarek** [comment]
We do support PUT and DELETE methods, just look at the AsyncHttpClient class public methods and examples in repository.
