### ISSUE TITLE
post json error

### ISSUE THREAD

**Issue by zjc** [loopj/android-async-http#846]
hi,all:
   I want use StringEntry to post json to remote server,but the charles catch json is not legal json
![a73b5c97-91b0-4a83-8a18-22b840158e2d](https://cloud.githubusercontent.com/assets/1041554/7347137/d88418ea-ed17-11e4-89d5-c84e8b1814f6.png)

my code is:
     
![3ae64c0f-2024-4947-91df-0eb6ea68e34e](https://cloud.githubusercontent.com/assets/1041554/7347148/ffc4c3dc-ed17-11e4-84c2-b1265bb78408.png)

**Comment by linghp** [comment]
I also do this,no problem.You can change "application/json" into "application/json;charset=UTF-8" 
good luck

**Comment by smarek** [comment]
How do you indicate, that the JSON "is not legal" ? Give us more info please.
