### ISSUE TITLE
onProgress - overflow totalBytes

### ISSUE THREAD

**Issue by jonnyn** [loopj/android-async-http#847]
Try to download a big movie file using this
```
handle = httpClient.get(context, movie.getMovieUrl(), new RangeFileAsyncHttpResponseHandler(file) {
            ...

            @Override
            public void onProgress(int downloadedBytes, int totalBytes) {
...
}
```
Content-Length: 2,330,725,695 bytes. Since max int = 2,147,483,647, totalBytes got overflown and return me a negative number.

**Comment by smarek** [comment]
Interesting, never thought of that, thank you, I'll fix that asap

**Comment by jonnyn** [comment]
Just wanted to follow up with on this issue. 
When are you going to address it, could you make it available in a week? Thanks
