### ISSUE TITLE
Is there any way to get values from RequestParams object by passing key?

### ISSUE THREAD

**Issue by jagatappv** [loopj/android-async-http#850]
Hey,

I am using this library.
It really helps me a lot.
Can you tell me how can i get values from RequestParams object by passing key or
Can i get list of key-value pairs?

Thanks

**Comment by onurkoncaoglu** [comment]
RequestParams class has a method which name is getParamsList() return a list but it's protected. You have to turn public it.

**Comment by jagatappv** [comment]
i am using the jar file , is there any way i can access it from  jar?

**Comment by onurkoncaoglu** [comment]
It's not a proper way but you can parse the string of toString() method.
