### ISSUE TITLE
"onSuccess" working properly but in same time shows it does not work properly"was not overriden"

### ISSUE THREAD

**Issue by kamilwlf** [loopj/android-async-http#854]
I wonder what I'm doing wrong.
The code works correctly, the onSuccess is called correctly, but gets in the log message "was not overriden"
My code:
http://paste.ofcode.org/FpCgYKC2UaT6s3vy84P7Hr

In the log you can see that it works. And it displays an error at one time.
Log cat:
http://paste.ofcode.org/9sdjMbxU26vddE7AhkSs4n

**Comment by Dimezis** [comment]
Well, thats obviously because you call super.onSuccess(statusCode, headers, response)

**Comment by smarek** [comment]
@Dimezis that's correct answer, thank you!
