### ISSUE TITLE
HTTP requests happen outside the UI thread. Does it really?

### ISSUE THREAD

**Issue by nickfl** [loopj/android-async-http#855]
Just run simple test with <b>.get(..)</b> and checked how long it takes to return.
In my case it was 1.2 sec!
And looks like as it runs on the Main thread!
I mean, is it not supposed to return right away and continue request in background thread?
Am I doing something wrong?
Here is code.

```
Date date = new Date();
long start = date.getTime();
Log.i(TAG, ".start");
AsyncHttpClient client = new AsyncHttpClient();
client.setConnectTimeout(JSONHelper.ConnectTimeout);
client.setResponseTimeout(JSONHelper.ReadTimeout);
Header [] headers = new Header[]{auth};
client.get(this, url, headers, null, responseHandler);
date = new Date();
long end = date.getTime();
Log.i(TAG, "exit: "+(end-start)); // prints out something like "exit: 1256"
```

**Comment by Dimezis** [comment]
If it was working in UI thread, you would have NetworkOnMainThreadException

**Comment by nickfl** [comment]
![Uploading stack.JPG…]()

**Comment by nickfl** [comment]
I was trying to upload screenshot, but...
Here is as text:
```
05-08 17:53:08.415  31617-31617/com.research.paul.boomapp D/OpenGLRenderer﹕ GL error from OpenGLRenderer: 0x502
05-08 17:53:08.415  31617-31617/com.research.paul.boomapp E/OpenGLRenderer﹕ GL_INVALID_OPERATION

05-08 17:53:13.940  31617-31617/com.research.paul.boomapp I/LoginActivity﹕ checkToken.start
05-08 17:53:15.172  31617-31617/com.research.paul.boomapp I/LoginActivity﹕ checkToken.exit: 1232
05-08 17:53:15.192  31617-31617/com.research.paul.boomapp I/Choreographer﹕ Skipped 76 frames!  The application may be doing too much work on its main thread.

05-08 17:53:15.792  31617-31617/com.research.paul.boomapp V/AsyncHttpResponseHandler﹕ Progress 59 from 174 (34%)
05-08 17:53:15.802  31617-31617/com.research.paul.boomapp I/.checkToken﹕ (200)onSuccess: {"hasRegistered":true,"userName":"11","loginProvider":null}
05-08 17:53:15.802  31617-31617/com.research.paul.boomapp I/LoginActivity﹕ startMainActivity
05-08 17:53:15.872  31617-31617/com.research.paul.boomapp W/ApplicationPackageManager﹕ getCSCPackageItemText()
```
As you may see it is in the main thread.

**Comment by Dimezis** [comment]
It does not work in UI thread, thats all. 
SyncHttpClient does. 
If you want to investigate what operation takes so much time, use some kind of profiler

**Comment by smarek** [comment]
Call you've tried to profile is non-blocking, as it runs on another thread, and yes, callback methods are executed in context (thread) they were created in, that's main feature of this library.

**Comment by nickfl** [comment]
OK,
as Marek asked me to continue discussion on Git here is my observations.
First, as far as I'm not that experienced in Android Studio I did profiling "manually" - added printfs.
Here is piece of code:
```
Date date = new Date();
long start = date.getTime();
Log.i(TAG, "checkToken.start");
        AsyncHttpClient client = new AsyncHttpClient();
date = new Date();
long step = date.getTime();
Log.i(TAG, "checkToken.timeout: " + (step - start));
start = step;
        client.setConnectTimeout(JSONHelper.ConnectTimeout);
        client.setResponseTimeout(JSONHelper.ReadTimeout);
date = new Date();
step = date.getTime();
Log.i(TAG, "checkToken.header: " + (step - start));
start = step;
        Header auth = new Header() {
            @Override
            public String getName() {
                return "Authorization";
            }

            @Override
            public String getValue() {
                return "Bearer "+token;
            }

            @Override
            public HeaderElement[] getElements() throws ParseException {
                return new HeaderElement[0];
            }
        };
        Header [] headers = new Header[]{auth};
date = new Date();
step = date.getTime();
Log.i(TAG, "checkToken.get: " + (step - start));
start = step;
        client.get(this, url, headers, null, responseHandler);
date = new Date();
long end = date.getTime();
Log.i(TAG, "checkToken.exit: "+(end-start));

```
Now the trace:
```
05-09 09:37:30.864      749-749/com.research.paul.boomapp I/LoginActivity﹕ checkToken.start
05-09 09:37:31.354      265-265/? W/EDMNativeHelper﹕ EDMNativeHelperService is published
05-09 09:37:31.454    1291-1291/? D/STATUSBAR-NetworkController﹕ onSignalStrengthsChanged signalStrength=SignalStrength: 99 -1 -1 -1 -1 -1 -1 12 -115 -10 68 -1 2147483647 gsm|lte 0x1 level=1
05-09 09:37:32.045      749-749/com.research.paul.boomapp I/LoginActivity﹕ checkToken.timeout: 1176
05-09 09:37:32.045      749-749/com.research.paul.boomapp I/LoginActivity﹕ checkToken.header: 1
05-09 09:37:32.045      749-749/com.research.paul.boomapp I/LoginActivity﹕ checkToken.get: 1
05-09 09:37:32.055      749-749/com.research.paul.boomapp I/LoginActivity﹕ checkToken.exit: 9
05-09 09:37:32.055      749-749/com.research.paul.boomapp I/Choreographer﹕ Skipped 73 frames!  The application may be doing too much work on its main thread.
05-09 09:37:32.355      265-265/? W/EDMNativeHelper﹕ EDMNativeHelperService is published

```
So, you may see the majority of time (1176 mils) was spent on the line:
<b> AsyncHttpClient client = new AsyncHttpClient();</b>
And I guess that this is why Android complains about <b> too much work on its main thread</b>
So, the major question (on main thread or not) was answered - not on the main thread.
But looks like we have to understand why that line above eats up so much time.
I mean, can I do something about it?
P.S. I debug the app on real device - Galaxy S4.

**Comment by smarek** [comment]
1) From time measure of `.get()` method you can see it's not executed on main thread
2) Log says “The application may be doing too much work on its main thread.”, important is word **may**, it's not clear for Choreographer, from where the number of frames comes from
3) Constructor eats a lot of time, because it initialises everything, from ThreadPool, HttpClient, HttpContext, SchemeRegistry, default values in HttpConnectionParams and request/response interceptors, In my opinion 1176 millis for such isn't much and it's the reason, why it's recommended to create static or class-private instance of AsyncHttpClient and reuse it, instead of creating it again and again for each request
