### ISSUE TITLE
synchronization in async-http

### ISSUE THREAD

**Issue by DXuYang** [loopj/android-async-http#858]
when i used sycn mode in async-http,i catch a unhandled exception：AsyncHttpRequest.java:205，NetWorkOnMainThreadException，how can i fix it?

**Comment by smarek** [comment]
Don't use Synchronous mode in UI Thread, or you will suffer with such exceptions. Use asynchronous way with proper callback or synchronous way from service / background thread / etc..

**Comment by DXuYang** [comment]
i don't understand "synchronous way from service / background thread "，what i want is some steps one by one,if i use service or background thread， actually it's async 。It's not what i want
