### ISSUE TITLE
List params not formatted correctly while generating URL

### ISSUE THREAD

**Issue by prcongithub** [loopj/android-async-http#862]
This code 
https://github.com/loopj/android-async-http/blob/1.4.7/library/src/main/java/com/loopj/android/http/RequestParams.java#L656
 contradicts with the examples mentioned here
http://loopj.com/android-async-http/doc/com/loopj/android/http/RequestParams.html

For ex.
```java
List<String> list = new ArrayList<String>(); // Ordered collection
 list.add("Java");
 list.add("C");
 params.put("languages", list); // url params: "languages[]=Java&languages[]=C"

String[] colors = { "blue", "yellow" }; // Ordered collection
 params.put("colors", colors); // url params: "colors[]=blue&colors[]=yellow"
```

Actually generates the following URL params
```
// url params: "languages[0]=Java&languages[1]=C"
// url params: "colors[0]=blue&languages[1]=yellow"
```

**Comment by prcongithub** [comment]
Anyone?

**Comment by smarek** [comment]
@prcongithub I'm sorry, i'm currently a bit busy, so I'm responding with delay. Have you already solved that or have you confirmed this is issue of library implementation?

**Comment by smarek** [comment]
Yes, sorry for taking so long, i've updated documentation and added sample, which demonstrates how the arrays, sets and maps are handled on RequestParams class, see the linked commits
9aaa6155d256e93f3f835d33d59f9649440f0f4d
527dae40527abbe314dbe0ac236b745e3146ef09
