### ISSUE TITLE
onPreProcessRequest() is not extendable

### ISSUE THREAD

**Issue by evonit** [loopj/android-async-http#864]
I need to inject a job before http-work in the async thread.

OnStart() in the AsyncHttpResponseHandler do work in the main thread.

I know that there is a method, AsyncHttpResponseHandler for the thread work, but it is not extendable!!!

It would be great if you provide a way to inject a user defined function into AsyncHttpResponseHandler()

Thanks

**Comment by smarek** [comment]
You're seeking the `onPreProcessRequest` and `onPostProcessRequest` in class `AsyncHttpRequest`, those are called before and after network work.
