### ISSUE TITLE
Grow heap error

### ISSUE THREAD

**Issue by StigmaKim** [loopj/android-async-http#867]
I'm in trouble with getting image buffer data. with response handler.

Here is my Node.js code and data. I send it to my app using res.send(docs).
```javascript
query.findOne(function(err, docs){
    if(!err){
        console.log(docs);
        res.send(docs);
    }
});
```
```javascript
{ _id: 555ee1f5be40576c28c3e228,
    email: 'hh@hh.h',
    pw: 'aa',
    name: 'jimy',
    phone: '22222222222',
    __v: 0,
    img: 
     { _bsontype: 'Binary',
       sub_type: 0,
       position: 4146282,
       buffer: <Buffer ff d8 ff e1 96 f8 45 78 69 66 00 00 4d 4d 00 2a 00 00...}
}
```

and here is my android app code.
```java
HttpClient.post("getMember/", param, new AsyncHttpResponseHandler() {
    @Override
    public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
        JSONObject obj;
        try {
            obj = new JSONObject(new String(responseBody));

            email_edt.setText(obj.get("email").toString());
            pw_edt.setText(obj.get("pw").toString());
            name_edt.setText(obj.get("name").toString());
            phone_edt.setText(obj.get("phone").toString());
        }
   }
}
```
this code works well at document without img field. 
but when it get response including img buffer data, It takes long time, and fired "OutOfMemory" Error.
I don't parse obj.get("img"), just get response.
document's size is about 4BM, It is not too large, but in my android studio, It looks like that believing it is really really big response. 

It log like below so many times.
```
Grow heap (frag case) to 131.704MB for 38189042-byte allocation
05-29 17:38:51.097  17193-17193/com.capstone.bookkeepingproto2 D/dalvikvm﹕ GC_FOR_ALLOC freed 26910K, 42% free 107442K/183252K, paused 266ms, total 266ms
05-29 17:38:52.177  17193-17193/com.capstone.bookkeepingproto2 D/dalvikvm﹕ GC_FOR_ALLOC freed 8192K, 42% free 107442K/183252K, paused 277ms, total 277ms
05-29 17:38:53.257  17193-17193/com.capstone.bookkeepingproto2 D/dalvikvm﹕ GC_FOR_ALLOC free
```

**Comment by smarek** [comment]
Yes, Image with large size will be troublesome to handle in JSONObject, you should write it directly to file and then parse it from disk.
Also don't be surprised, you're creating String from whole response (including the Image), and then you're passing it through JSONObject which is the least efficient way of handling JSON.

See FileAsyncHttpResponseHandler (which can save the response into file), and Gson/Jackson JSON libraries to handle JSON efficiently.

Also think about not sending large image as JSON base64 encoded string, that should be handled binary in communication.

**Comment by StigmaKim** [comment]
Thanks @smarek 
As you said, I done this work by storing image as a file on server, not as a JSONObject on the MongoDB. 
Through this way, I got perfect result. Thanks your reply.

**Comment by smarek** [comment]
Cool, glad to help you out. FileAsyncHttpResponseHandler should be ie. used for grabbing the image itself and saving it on the disk, without filling up the memory (which is the problem you've struggled with)
