### ISSUE TITLE
new AsyncHttpClient not work in android5.0

### ISSUE THREAD

**Issue by wufenglong** [loopj/android-async-http#870]
Hi，I have a problem,in android 5.0 device,when new  AsyncHttpClient()，the program stop in
ClientConnectionManager cm = createConnectionManager(schemeRegistry, httpParams);
then the program is ANR.

**Comment by smarek** [comment]
I do use the library fine on 5.0 and 5.1 devices, can you fetch us more information? Post here logcat and ANR debug info

**Comment by smarek** [comment]
Also what version of library do you use?
