### ISSUE TITLE
onSuccess(int, Header[], JSONObject) was not overriden, but callback was received

### ISSUE THREAD

**Issue by iDaniel19** [loopj/android-async-http#872]
This is what I get in the console:   

    onSuccess(int, Header[], JSONObject) was not overriden, but callback was received

I verified and the file is uploaded to the server. 

This is my code and the app doesn't complain :

 

    public void uploadImage() {
            //Create a new RequestParams that will send paremeters with our AsyncHttpClient request.
            RequestParams data = new RequestParams();
    
            //Adding our image to the parameters.
            File image = new File(imgPath);
            try {
                data.put("image", image);
            } catch(FileNotFoundException e) {}
            //Create a new AsyncHttpClient request.
            //here we're sending a POST request, the first parameter is the request URL
            // then our RequestParams, in our case data and then a Json response handler.
            AsyncHttpClient client = new AsyncHttpClient();
            client.post(FILE_UPLOAD_URL, data, new JsonHttpResponseHandler() {
                @Override
                public void onSuccess(int statusCode, Header headers[], JSONArray success) {
                    try {
                        JSONObject data = success.getJSONObject(0);
                        String m = data.getString("message");
                        Toast.makeText(UploadPhotoTest.this, m, Toast.LENGTH_LONG).show();
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
                }
            });
        }

And this is what I'm importing if it's relevant :
    
    import com.loopj.android.http.AsyncHttpClient;
    import com.loopj.android.http.JsonHttpResponseHandler;
    import com.loopj.android.http.RequestParams;
    
    import org.apache.http.Header;
    import org.json.JSONArray;
    import org.json.JSONException;
    import org.json.JSONObject;

My problem is that whatever is in OnSuccess never gets executed .. I put a log in the OnSuccess try and catch and nothing gets printed. How can I solve this ?

**Comment by koesie10** [comment]
Your server returns an object, while you have a callback set which receives an array.

**Comment by iDaniel19** [comment]
The server sends an array. I know because I tested it before with something else. You may be right though. How should I change it ? Where can I find a list with all OnSuccess and OnFailure methods ?

**Comment by koesie10** [comment]
They can be found in the [javadoc](http://loopj.com/android-async-http/doc/com/loopj/android/http/JsonHttpResponseHandler.html).

**Comment by iDaniel19** [comment]
Thank you. I'll have a look into that.

**Comment by smarek** [comment]
You are overriding `onSuccess(int statusCode, Header headers[], JSONArray success)` not `onSuccess(int statusCode, Header headers[], JSONObject success)`, that should be our problem

**Comment by kvanadev1gmail** [comment]
My project worked successfully when using android-async-task v 1.3.1, but as it is outdated i shifted to v 1.4.8 my log report is "onSuccess(int, Header[], JSONObject) was not overriden, but callback was received".

**Comment by smarek** [comment]
Yes, that means, you have to implement that specific callback, because it's the one data are passed into.
