### ISSUE TITLE
Uploading byte arrary using this library.

### ISSUE THREAD

**Issue by harry225** [loopj/android-async-http#879]
I am trying to upload large video for that i have converted that file to bytes and divide into chuncks(list of byte array).
Now i want to upload that list of byte array using this library. 

I have tried with this but doesn't work for me
params.put("soundtrack", new ByteArrayInputStream(myByteArray));

How can I upload bytes using this library?

**Comment by smarek** [comment]
Essentially, you don't want to use ByteArrayInputStream, uploading the file should be done by MultipartHttpEntity, through `RequestParams` it's usage is done via one of methods

  - `put(String key, File file)`
  - `put(String key, String customFileName, File file)`
  - `put(String key, File file, String contentType)`
  - `put(String key, File file, String contentType, String customFileName)`
