### ISSUE TITLE
When I download file, how to stop download and resume down ?

### ISSUE THREAD

**Issue by ruijun** [loopj/android-async-http#880]
When I download file, how to stop download and resume down ?

**Comment by smarek** [comment]
You can use `RangeFileAsyncHttpResponseHandler`, which will download rest of the file, if the server supports resuming download.

**Comment by ruijun** [comment]
@smarek Thanks.I have another question, How to achieve breakpoint resume upload in android-async-http?

**Comment by smarek** [comment]
Answered in your other question
