### ISSUE TITLE
Why FileAsyncHttpResponseHandler constructor must not point to directory ?

### ISSUE THREAD

**Issue by ruijun** [loopj/android-async-http#882]
Why FileAsyncHttpResponseHandler constructor must not point to directory ?

**Comment by smarek** [comment]
@ruijun currently constructor takes as argument File object to store the file into, I think you want the library to be able to extract the name of resource from URL and save the it into specified directory. If that's correct, it should be possible to add this function in next release.

**Comment by ruijun** [comment]
You are right, thank you !! I have another question：the library will support rename the same file automatically?

**Comment by smarek** [comment]
It probably will, I'm thinking of it like this:

```java
// currently available, will create temporary file
public FileAsyncHttpResponseHandler(Context context);
// currently available, if the file is directory, will create new file with name of last URL segment
// if the file already exists will create file with pattern "my file.ext" => "my file (1).ext" => "my file (2).ext"
public FileAsyncHttpResponseHandler(File targetFile);
// currently available, will append the data to file, if it already exists
// will append the output to file of name of last URL segment if it already exists
public FileAsyncHttpResponseHandler(File targetFile, boolean append);
```

What do you think?

**Comment by ruijun** [comment]
I'm thinking of it like this:
public FileAsyncHttpResponseHandler(File targetFile, boolean isAutoRename){

}

**Comment by smarek** [comment]
I've implemented this feature. See the library change commit https://github.com/loopj/android-async-http/commit/f39b23f35aec071b813e610c4c734517937543f4  
And see the Directory Sample, which demonstrates the function https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/DirectorySample.java

Basically constructor got one more argument `boolean renameTargetFileIfExists`
Full constructor is now
> public FileAsyncHttpResponseHandler(File file, boolean append, boolean renameTargetFileIfExists)

Behavior:
  - If the first argument is directory, it won't fail on assert, but will create file within given directory from request URL
  - If second argument is true, will rewrite target file (also for filename taken from request URL)
  - If third argument is true, will try to find filename which is not taken, and will write the response into it
  - If both second and third arguments are true, will find new name for file, not overwriting the already existing one

**Comment by ruijun** [comment]
@smarek Thanks.When can we use android-async-http 1.4.8 release ?

**Comment by smarek** [comment]
I've put 1.4.8 snapshot on maven snapshot repository (see the main README for setup instructions), and I plan to release 1.4.8 in matter of days (depends on how many responses I'll gather from testing and closed/answered tickets, afterall it's been a while, since that many changes occurred to the project.
