### ISSUE TITLE
Doc clarification

### ISSUE THREAD

**Issue by kjkrum** [loopj/android-async-http#884]
The docs for `RequestHandle#cancel(boolean)` state:

> After this method returns, subsequent calls to isDone() will always return true. Subsequent calls to isCancelled() will always return true if this method returned true.

If `cancel` returns false, will subsequent calls to `isDone()` still return true?  It seems like they should not, but the docs suggest they would.

**Comment by smarek** [comment]
I've updated documentation on said method. For record `isDone()` may return true if request got cancelled other way or if the request completed normally.
