### ISSUE TITLE
How to upload single file  for non-multipart forms ?

### ISSUE THREAD

**Issue by ruijun** [loopj/android-async-http#888]
@loopj 

  Hello,   I want to upload single file  for non-multipart forms, how can I do this?

**Comment by smarek** [comment]
@ruijun it's not possible to upload File if you're not using Multipart content-type.
You can read up on documentation here: https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/RequestParams.java#L138
