### ISSUE TITLE
Upload multiple files array

### ISSUE THREAD

**Issue by jandrop** [loopj/android-async-http#889]
Hi, 
I have an array of files, on server side i have two php files one with a form test:

upload_form.php
```html
<!DOCTYPE html>
<html>
    <body>
        <form action="upload_images.php" method="post" enctype="multipart/form-data">
            Select file to upload:
            <input type="file" name="file_array[]" multiple>
            <input type="submit" value="Upload all files">
        </form>
    </body>
</html>
```
and another with php upload
```html
<?php
$name_array = $_FILES["file_array"]["name"];
$tmp_name_array = $_FILES["file_array"]["tmp_name"];
$type_array = $_FILES['file_array']['type'];
$size_array = $_FILES['file_array']['size'];
$error_array = $_FILES['file_array']['error'];

for ($i = 0; $i < count($tmp_name_array); $i++) {
    if (move_uploaded_file($tmp_name_array[$i], "images/" . $name_array[$i])) {
        echo $name_array[$i] . " upload is complete <br>";
    }
    else {
        echo "move_uploaded_file function failed for " . $name_array[$i] . "<br>";
    }
}
?>
```
It works correctly, i can upload multiple files on my server selecting multiple images.

On android I have an app with a picker who fills an array of Files
I'm using AsyncHttp to upload this array like this:

private void uploadImages(ArrayList<File> files) {

        RequestParams params = new RequestParams();
        for (File f : files) {
            try {
                params.put("file_array[]", f);
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }

        AsyncHttpClient client = new AsyncHttpClient();
        client.post("http://xxx.xxx.xxx.xxx/upload_images.php", params, new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                String response = new String(responseBody);
                Log.i(TAG, response);
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {

            }
        });
    }

but this doest't work only upload last file in the array.

**Comment by PaperHS** [comment]
RequestParams.put() is a HashMap.put,your code will override file_array[] and at last get only one.
you can do like this: params.put("file_array", files);
but I think there is a Bug,U have to do :params.put("what_ever", File); (a real file).it will change your post to mutipart/form-data.

**Comment by maxtac** [comment]
Hello.
I Have a similar Problem

I add all the file to parameters with the following code
<pre><code>
for(MyFile file: getListFile()) {
    try {
        numFileAdded++;
        params.put("uploaded_file" + numFileAdded, new File(mDirectory, file.getFileName()),"text/xml");
    }
    catch (FileNotFoundException e) {
        e.printStackTrace();
    }
    catch (IOException e) {
        e.printStackTrace();
    }
}
</code></pre>
and then i Send all Parameter with the following code
<pre><code>
AsyncHttpClient client = new AsyncHttpClient();
client.post ......
</code></pre>

My problem is that from my php script I do not receive all the files added to the Parameters
Infact, I get all the files in the queue, until I get a  "truncated" file, and after this I do not receive any other.

Can you help me?

**Comment by jandrop** [comment]
Finally i solve this with asyncTask, i have created a method inside the asyncTask class called uploadFile(File f)
this method is called in doInBackGround with a loop 
```java
@Override
    protected Void doInBackground(Void... params) {

        for (File file : files) {
            uploadFile(file);
            subidas++;
            publishProgress((int) ((subidas * 100) / total));
        }

        return null;
    }
```
I call the AsyncTask with 
```java
UploadImages ui = new UploadImages(getActivity(), files);
ui.setOnImageListener(this);
```

my php script:
```php

include_once "funCreateThumb.php";
$uploaddir = "images/";
$uploadfile = $uploaddir . basename($_FILES['uploaded_file']['name']);
$filename = $_FILES['uploaded_file']['name'];

echo '<pre>';
if (move_uploaded_file($_FILES['uploaded_file']['tmp_name'], $uploadfile)) {
    echo "El archivo es válido y fue cargado exitosamente.\n";

   // make a thumb of the file
    createThumbnail($filename);

}
else {
    echo "¡Posible ataque de carga de archivos!\n";
}

print "</pre>";
?>
'''

**Comment by xfans** [comment]
In old version RequestParams use map save params,so same key not support.
In new version you can use:
```File[] files = { new File("pic.jpg"), new File("pic1.jpg") }; // Ordered collection
params.put("files", files); // url params: "files[]=pic.jpg&amp;files[]=pic1.jpg"```
 upload files.
see:RequestParams.java

**Comment by smarek** [comment]
I'm going to close this discussion with example which is provided for this use-case.
https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/FilesSample.java

**Comment by DevrajJha** [comment]
File[] files = lst.toArray(new File[lst.size()]);

        try {
            loginCerendentail.put("media[]", files);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
