### ISSUE TITLE
AsyncHttpResponseHandler﹕ User-space exception detected!

### ISSUE THREAD

**Issue by ahmtbrk** [loopj/android-async-http#891]
Hi all.
I am sending request this url
http://gsgazeteler.com/apps/panel/api/arsiv?date=2015-06-19&date2=2015-06-20
and give an error in onsuccess during the build string process.

My code ->
HttpClient.get(String.format(HttpClient.URL_NEWSPAPERS, formattedCurrentDate, formattedNextDate).trim(), null, new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                String str = new String(responseBody);
                MyLog.log(str);
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                error.printStackTrace();
            }
        });

Error : E/AsyncHttpResponseHandler﹕ User-space exception detected!
    java.lang.NullPointerException: Attempt to get length of null array

Please help me

**Comment by gaobq** [comment]
hi I think your requestParams is null cause ths exception ; 
you should change HttpClient.get(str,null,new AsyncHttpResponseHandler());
to  HttpClient.get(str,new AsyncHttpResponseHandler());

**Comment by ahmtbrk** [comment]
@gaobq thanks for solution.
I fixed this problem.

**Comment by CnkGn** [comment]
@gaobq I encountered the same problem. try this solution but not working. how can i fix?

**Comment by elpoisterio** [comment]
I get user exception detected when i try to use toast method in onFailure. Does anyone has a solution for this one.

**Comment by neerajakshid** [comment]
I am getting this error in the onfailure method. Does anyone has  a solution? Thanks in advance..

**Comment by elpoisterio** [comment]
@neerajakshid can you post the snippet of your onfailure method ?

**Comment by ashishmlogicsol** [comment]
client.post(getApplicationContext(), Connection.PLANLIST_SERVICE, entity, "application/json", new TextHttpResponseHandler() {
            @Override
            public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                if (responseString != null) {
                    Toast.makeText(getApplicationContext(), "Fail to load data", Toast.LENGTH_LONG).show();
                }
                function.dismiss();
            }

            @Override
            public void onSuccess(int statusCode, Header[] headers, String responseString) {
                if (statusCode == 200 && responseString != null) {
                    //Log.e("Plan_onSuccess", responseString);
                    try {
                        JSONObject json = new JSONObject(responseString);
                        int success = json.getInt(Connection.TAG_SUCCESS);
                        if (success == 1) {
                            JSONArray currlist = json.getJSONArray(Connection.Tag_plandata);
                            for (int i = 0; i < currlist.length(); i++) {
                                JSONObject c = currlist.getJSONObject(i);
                                PlanModel obj = new PlanModel();
                                obj.setPlan_id(c.getString(Connection.Tag_plan_id).trim());
                                obj.setPlan_name(c.getString(Connection.Tag_plan_name).trim());
                                obj.setPlan_desc(c.getString(Connection.Tag_plan_desc).trim());
                                obj.setPlan_price(c.getString(Connection.Tag_plan_price).trim());
                                obj.setCreated_datetime(c.getString(Connection.Tag_created_datetime).trim());
                                obj.setCreated_by(c.getString(Connection.Tag_created_by).trim());
                           
                                
                                obj.setStatus(c.getString(Connection.Tag_status).trim());
                              
                                obj.setPlanpkgdata(c.getJSONArray(Connection.Tag_planpkgdata));

                               /* obj.setSlider_pic1(c.getString(Connection.Tag_plan_slider1));
                                obj.setSlider_pic2(c.getString(Connection.Tag_plan_slider2));
                                obj.setSlider_pic3(c.getString(Connection.Tag_plan_slider3));
                                obj.setSlider_pic4(c.getString(Connection.Tag_plan_slider4));
                                obj.setSlider_pic5(c.getString(Connection.Tag_plan_slider5));*/

                                PlanArraylist.add(obj);

                               
                             Sqlite_Dbaa.insert_plan(c.getString(Connection.Tag_plan_id).trim(),
                                        c.getString(Connection.Tag_plan_name).trim(),
                                        c.getString(Connection.Tag_plan_desc).trim(),
                                        c.getString(Connection.Tag_plan_price).trim(),
                                        c.getString(Connection.Tag_created_datetime).trim(),
                                        c.getString(Connection.Tag_created_by).trim(),
                                        c.getString(Connection.Tag_status).trim());
                        
                            }
                            Sqlite_Dbaa.close();
                        }
                        if (PlanArraylist.size() > 0) {
                            PlanAdapter adapter = new PlanAdapter(PlanActivity.this, PlanArraylist);
                            recyclerViewPlan.setAdapter(adapter);
                        }
                        function.dismiss();
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
                }
            }
        });


Getting Error:
User-space exception detected!
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'long android.database.sqlite.SQLiteDatabase.insert(java.lang.String, java.lang.String, android.content.ContentValues)' on a null object reference
                                                                     at mls.com.shop.Dblocal.DbOperation.insert_plan(DbOperation.java:81)
                                                                     at mls.com.shop.Activity.PlanActivity$2.onSuccess(PlanActivity.java:220)
                                                                     at com.loopj.android.http.TextHttpResponseHandler.onSuccess(TextHttpResponseHandler.java:118)
                                                                     at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
                                                                     at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


Any solution???
