### ISSUE TITLE
Extra chars when use setUseJsonStreamer

### ISSUE THREAD

**Issue by titanseason** [loopj/android-async-http#892]
when I user RequestParams#setUseJsonStreamer(true) to post json data to server, extra chars were put before and after the json
(poor English)

When I fetch the http requst, the request is like this:
I don't know why there is extra char '58' before the json, and extra char '0' after the json 

POST http://xxx/v2/user/login HTTP/1.1
Transfer-Encoding: chunked
Content-Type: application/json
Host: xxx
Connection: Keep-Alive
Accept-Encoding: gzip

58
{"user":"test04","pwd":"test04","devtk":"64ADD49C5E8D027065C9F05E9C238A63","_elapsed":1}
0

**Comment by smarek** [comment]
@titanseason How did you debug this data? Have you solved the problem since this issue is 3 weeks old?

**Comment by titanseason** [comment]
I rewrite method JsonStreamerEntity#getContentLength() ,return json.toString().length() rather than -1.
It works well if there are no stream/file parameters, if there are stream/file parameters, this might cause OutOfMemeray Error

**Comment by titanseason** [comment]
@smarek You can see how to fetch http data using fiddler here.
http://www.cantoni.org/2013/11/06/capture-android-web-traffic-fiddler
