### ISSUE TITLE
Thx your contribution !  What a helpful project.But I had a problem

### ISSUE THREAD

**Issue by CodeLead** [loopj/android-async-http#893]
I got a failure in android-22 , but  android-16 not. The code down there.
     

               
                                       HttpUtil.post(mContext,createAccountUrl, createAccountParams, new JsonHttpResponseHandler() {
                                           @Override
                                           public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                                               System.out.println(statusCode);
                                               try {
                                                   if (response.getString("status").equals("400")) {
                                                       applyRotation(0, 0, -90);
                                                       index = 1;
                                                       etRegisterMail.setText("");
                                                       etRegisterName.setText("");
                                                       etRegisterPassword.setText("");
                                                       ivAvator.setImageResource(R.drawable.logo);
                                                   } else {
                                                       Toast.makeText(Login.this, response.getString("status"), Toast.LENGTH_SHORT).show();
                                                   }
                                               } catch (JSONException e) {
                                                   e.printStackTrace();
                                               }
                                           }

                                           @Override
                                           public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {
                                      
       //                                                System.out.println("fail" + statusCode);
                                              
                                           }

                                           @Override
                                           public void onFinish() {
                                               super.onFinish();
                                           }
                                       });

**Comment by smarek** [comment]
@CodeLead and what failure? Closing until you provide us with more information
