### ISSUE TITLE
CloudFlare free plan SSL handshake exception (1.4.7)

### ISSUE THREAD

**Issue by Saren-Arterius** [loopj/android-async-http#894]
It happens on my phones, **Android 4.2** (Xperia C) **5.0.2** (HTC M9) whenever AsyncHttpClient make a request toward a **CloudFlare free plan** protected server with **SSL on**. 

In this case one of the example is (https://cf-hkgpx.wtako.net).

I will be very happy to see a fix, but it's also OK to see a workaround that ignores SSL check, since I am requesting a foreign API that does not require any means of security. (But there is a 301...)

How I instantiate a AsyncHttpClient object

    asyncClient = new AsyncHttpClient(true, 80, 443);
    asyncClient.setCookieStore(getCookieStore(ctx));
    asyncClient.setUserAgent(MiscUtils.getUserAgent());
    asyncClient.setEnableRedirects(true);
    asyncClient.setMaxRetriesAndTimeout(0, 0);

The stacktrace.

    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ javax.net.ssl.SSLHandshakeException: Handshake failed
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:598)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:560)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.io.SocketInputBuffer.<init>(SocketInputBuffer.java:70)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.SocketHttpClientConnection.createSessionInputBuffer(SocketHttpClientConnection.java:89)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.createSessionInputBuffer(DefaultClientConnection.java:170)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.SocketHttpClientConnection.bind(SocketHttpClientConnection.java:112)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.openCompleted(DefaultClientConnection.java:129)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:172)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:372)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:519)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:148)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:179)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:108)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x557540cf10: Failure in SSL library, usually a protocol error
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:765 0x7f9f719358:0x00000000)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
    06-26 22:24:15.025  28687-13229/net.wtako.dathkg W/System.err﹕ ... 21 more

**Comment by smarek** [comment]
@Saren-Arterius It's not about number of retries or whatever, it's problem of used SSL implementation on actual device. To completely ignore SSL security you can use alternative constructor, see the documentation on it:
https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L177

**Comment by Saren-Arterius** [comment]
@smarek Note that I am using `asyncClient = new AsyncHttpClient(true, 80, 443);`, the first paramater fixNoHttpResponseException is true, which means I am already using the alternative constructor you have mentioned. Still, I am having this problem.

**Comment by smarek** [comment]
@Saren-Arterius still it's not something we could fix, as the issue appears in underlying SSL implementation (`external/openssl/ssl/s23_clnt.c:765 0x7f9f719358:0x00000000`), seems like 

For reference read up on these links:
https://groups.google.com/forum/#!topic/android-developers/9mSJEmp7FYU
https://developer.android.com/about/versions/android-5.0-changes.html#ssl
https://github.com/square/okhttp/issues/1582

**Comment by HipsterWhale** [comment]
I'm facing this issue on a CloufFlare site (Android 6), how can I fix it ?

**Comment by littletanker** [comment]
@Saren-Arterius hi, i have the same problem with https  useing CloudFlare , do you have any solution ?

**Comment by Saren-Arterius** [comment]
@littletanker Yes, switch to Volley pretty much solves this problem.

**Comment by littletanker** [comment]
@Saren-Arterius  but  i can access anthore https request except CloudFlare , can you tell me what's the problem with asynchttp?

**Comment by Saren-Arterius** [comment]
@littletanker This library has no SNI support, and CloudFlare free SSL uses it. [https://github.com/loopj/android-async-http/issues/894#issuecomment-120717774]

**Comment by littletanker** [comment]
@Saren-Arterius  tks for your reply!

**Comment by dev01-adroitinfosol** [comment]
Here is the solution for you, This can be applied when you are using server for development purpose.

public SSLContext getSslContext() {

    TrustManager[] byPassTrustManagers = new TrustManager[] { new X509TrustManager() {
        public X509Certificate[] getAcceptedIssuers() {
            return new X509Certificate[0];
        }

        public void checkClientTrusted(X509Certificate[] chain, String authType) {
        }

        public void checkServerTrusted(X509Certificate[] chain, String authType) {
        }
    } };

    SSLContext sslContext=null;

    try {
        sslContext = SSLContext.getInstance("TLS");
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
    try {
        sslContext.init(null, byPassTrustManagers, new SecureRandom());
    } catch (KeyManagementException e) {
        e.printStackTrace();
    }

    return sslContext;

}

 AsyncHttpClient client = new AsyncHttpClient();

 client.setSSLSocketFactory(
            new SSLSocketFactory(getSslContext(),
            SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER));

**Comment by metrey** [comment]
Even with last comment was not solve the issue. How to bypass the certificate verify for any host with cloudflare ssl? Or we have to wait SNI supports to fix? Or need to replace the library? Or leave cloudflare to use our own certificate?....

**Comment by Saren-Arterius** [comment]
@metrey Just replace the library, works really fine.

**Comment by metrey** [comment]
@Saren-Arterius Yes, finally https://github.com/amitshekhariitbhu/Fast-Android-Networking solved the problem and work just fine as before.
