### ISSUE TITLE
SaxAsyncHttpResponseHandler - onFailure falls back to onSuccess

### ISSUE THREAD

**Issue by czechnology** [loopj/android-async-http#895]
Unless I'm very mistaken, I don't think this is an intended behaviour and line 147 should point to `onFailure`.

[SaxAsyncHttpResponseHandler:144-148](https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/SaxAsyncHttpResponseHandler.java#L147):
```java
    @Override
    public void onFailure(int statusCode, Header[] headers,
                          byte[] responseBody, Throwable error) {
        onSuccess(statusCode, headers, handler);
    }
```

---

On a related note - what would be the correct way to stop the SAX processing? Throwing an Exception does the trick but afterwards goes to `onSuccess()`. Can I force it to go to `onFailure()`?

**Comment by smarek** [comment]
Thank you for noticing, I've fixed that in ddf6f83b7854c8bcbbe8ed234498ae32cd7b96a5
