### ISSUE TITLE
Is android-asynct-http coupled with UI thread?

### ISSUE THREAD

**Issue by muraliandroid** [loopj/android-async-http#896]
I want to use this awesome library for my server request in my application to do some work on map. My need is I want to make server request for every 2 minutes without block user interaction on the screen while server requesting process happening and in the onSuccess call back I'll do some work on the map.
How can I use this library for my need?

**Comment by gaobq** [comment]
http request should not in UI thread ,you can see simple like this:
final Activity ctx = this;
        FutureTask<RequestHandle> future = new FutureTask<>(new Callable<RequestHandle>() {
            public RequestHandle call() {
                Log.d(LOG_TAG, "Executing GET request on background thread");
                return client.get(ctx, URL, headers, null, responseHandler);
            }
        });

        executor.execute(future);

this request is not in UI Thread;

as you need to request per 2 min ,you just use java.util.concurrent.ScheduledExecutorService to do this

**Comment by smarek** [comment]
OT discussion, see the https://github.com/loopj/android-async-http/blob/master/CONTRIBUTING.md for proper way of using Github issues

**Comment by miladheydari** [comment]
any one can more explain and sample for me?
