### ISSUE TITLE
Check for internet availability

### ISSUE THREAD

**Issue by vinod-jaiswal18** [loopj/android-async-http#904]
Hey,

I was thinking to use this library for one of project and this question came in my mind. Does this library checks for internet connection before making a Http network request?
If not, what are other people using for checking this?

Thanks,
Vinod

**Comment by smarek** [comment]
It does not and will not, and use a Android documentation or stackoverflow.com to lookup solution for your problem, in case it's not problem of library.

**Comment by vinod-jaiswal18** [comment]
@smarek ,
Thanks.
