### ISSUE TITLE
Why is it always wrong when i call 'AsyncHttpClient.get(url,params ,handler)'?stauscode :500

### ISSUE THREAD

**Issue by xfshipan** [loopj/android-async-http#905]
AsyncHttpClient client = new AsyncHttpClient();
        RequestParams params = new RequestParams();
        params.put("app","mobile");
        params.put("type", "mobile");
        params.add("controller", "content");
        params.add("action", "category");
        client.get("http://mapi.univs.cn/mobile/index.php", params, new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                System.out.println("success");
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                System.out.println("failure");
            }
        });

http://mapi.univs.cn/mobile/index.php?app=mobile&type=mobile&controller=content&action=category
If i access this link by web broswer,it can response me.i don't know why

**Comment by gaobq** [comment]
could you change
params.put("app","mobile");
 params.put("type", "mobile");
 to params.add()...

and use client.post replace cilent.get()?
