### ISSUE TITLE
Request stuck in between on closing the app.

### ISSUE THREAD

**Issue by programmergauravgupta** [loopj/android-async-http#906]
I am using version 1.4.6 for uploading videos to server. Everything is working fine except for one case i.e while uploading if I closes the app then it stuck in onProgress() method it never finishes. I am initiating request from within a service. Please help me to solve the issue.

**Comment by smarek** [comment]
Do you have custom implementation of `onProgress` method or do you just watch default output in LogCat ?

**Comment by programmergauravgupta** [comment]
I tried in all way using default implementation, using custom implementation, using custom implementation with default as well(Using super.onProgress()). In all ways it always hangs up when I kill my app.

**Comment by smarek** [comment]
super.onProgress does nothing really, how do you know it "hangs up in onProgress method"? How can you tell?

**Comment by programmergauravgupta** [comment]
I am managing progress through notification. When I upload video without closing the app it uploads successfully. But when I close the app in between then notification progress and logcat stops there also video doesn't get uploaded. It never calls either onSuccess or onFailure.

**Comment by smarek** [comment]
@programmergauravgupta well I guess you have problem in your implementation, and when the app is closed, the IntentService (probably) get's killed with it. Does the service run in another thread, context and is running after the app closes or not?
