### ISSUE TITLE
Which resource jar from Meaven  can I see the real source code?

### ISSUE THREAD

**Issue by MIkeeJY** [loopj/android-async-http#909]
If I only add 1.4.8.jar,I can't see the source code,what sould I do? Help me plz...
Develop tools is Eclipse...

**Comment by smarek** [comment]
@MIkeeJY this is not general issues forum, also use Maven for dependency tracking, or download all the jars from the maven (there are jars for source, binary and javadoc). Questions like this belong to stackoverflow.com

**Comment by MIkeeJY** [comment]
Thx man,I've already solved it
