### ISSUE TITLE
requestparams always be encoded

### ISSUE THREAD

**Issue by greatflag** [loopj/android-async-http#910]
The method getUrlWithQueryString(boolean shouldEncodeUrl, String url, RequestParams params) in AsyncHttpClient has "String paramString = params.getParamString().trim();".It uses URLEncodedUtils to format params. When I do search by ElasticSearch's rule like "q='form=10&size=20'", it will return nothing.

**Comment by smarek** [comment]
Well then disable it, you can, through `AsyncHttpClient.setURLEncodingEnabled(boolean enabled)`
https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L1428
