### ISSUE TITLE
An AsyncHttpResponseHandler Error 

### ISSUE THREAD

**Issue by W16Tsi** [loopj/android-async-http#912]
Hi all !   

   I developed an Android APP by Android Studio, which is almost finished.

   My app works normally when I RUN the app in Android Studio, but when I build an APK and installed it to my cell phone , the app crashed when I log in.

   The error info is as follow:
```
29413-29413/? E/AsyncHttpResponseHandler﹕ User-space exception detected!
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
........
07-29 17:42:04.458  29413-29413/? D/AndroidRuntime﹕ Shutting down VM
07-29 17:42:04.468  29413-29413/? E/a﹕ java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
........

     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
```
Thanks.

**Comment by smarek** [comment]
Hi, from first line of LogCat read `User-space exception detected!` This means, the problem is in your implementation of callback method, and you have to find out which one. Search for `toArray()` in your code, this is not problem of library in my opinion.
