### ISSUE TITLE
Image upload problem

### ISSUE THREAD

**Issue by ahmtbrk** [loopj/android-async-http#914]
Hi guys
I have tried image upload via asynchttp 1.4.7 but server give an error.

```
org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found
```

Previously when i used 1.4.3 version file upload worked successfully.
My code ->
```
MimeTypeMap map = MimeTypeMap.getSingleton();
        String ext = MimeTypeMap.getFileExtensionFromUrl(imageFile.toURI().toString());
        String mimeType = map.getMimeTypeFromExtension(ext);
        RequestParams params = new RequestParams();
        try {
            params.put(PARAMETER_PHOTO, imageFile, mimeType);
            params.put(PARAMETER_COORDINATOR_IEEE_ADDRESS, coordinatorIeeeAddress);
        } catch (FileNotFoundException e) {
            MyLog.log(e);
        }
        return mClient.post(mContext, getAbsoluteUrl(UPLOAD_HOME_PHOTO), null, params, MULTI_PART_FORM_DATA, asyncResponseHandler);
```
Please help me

**Comment by smarek** [comment]
If you're upgrading the library, could you please test directly with 1.4.8? That's the only one we're supporting at the time. Thank you

**Comment by ahmtbrk** [comment]
Hi @smarek 
I do changes in library.because my requests are work with server session.if session expire when send request, i use silent login in backend for new session.so i do to update library too costly for me :/

**Comment by smarek** [comment]
What changes? Can you post up `git diff` of library repository? I'm sorry, but we cannot support custom modified libraries ...

**Comment by ahmtbrk** [comment]
@smarek Just i added get a new sesssion and sleep request until get a new session features for my project needs

**Comment by smarek** [comment]
I understand, but you're modifying the library, if you're able to modify the library, you're able to do the whole job, we cannot do the "fix my modified library" work instead of you.

**Comment by ahmtbrk** [comment]
@smarek i understand.
Thanks a lot for help.
I will try update library version.
I will write result next time at here
Good works

**Comment by ahmtbrk** [comment]
@smarek Hello again.
I updated library to latest version 1.4.8(and not modified).
But server gave same error.
Please help nme

**Comment by smarek** [comment]
Can you look into LogCat if the Content-Type was overriden or not? Because If you put the RequestParams with File params and Content-Type into `.post(...)` method, they may clash.

**Comment by smarek** [comment]
Also look on the Sample implementation od file upload https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/FilesSample.java

**Comment by ahmtbrk** [comment]
@smarek Thanks a lot for help
I found solution for this problem. I updated upload method like the following lines

public RequestHandle uploadProfilePhoto(File imageFile, ResponseHandler asyncResponseHandler) {
        MimeTypeMap map = MimeTypeMap.getSingleton();
        String ext = MimeTypeMap.getFileExtensionFromUrl(imageFile.toURI().toString());
        String mimeType = map.getMimeTypeFromExtension(ext);
        RequestParams params = new RequestParams();
        try {
            params.put(PARAMETER_FILE, imageFile, mimeType);
            params.setHttpEntityIsRepeatable(true);
            params.setUseJsonStreamer(false);
        } catch (FileNotFoundException e) {
            MyLog.log(e);
        }
        return mClient.post(mContext, getAbsoluteUrlForBase(UPLOAD_PROFILE_PHOTO), params, asyncResponseHandler);
    }

Good works!

**Comment by smarek** [comment]
You're welcome, thank you for posting back the solution, that will help other users of library!
