### ISSUE TITLE
Changes in URL encoding intended? / How to pass an encoded URL in an URL

### ISSUE THREAD

**Issue by asco33** [loopj/android-async-http#915]
Hi there, 
I noticed a change in the URL encoding from version 1.4.6 upwards (it's also mentioned in the 1.4.7 changelog: https://github.com/loopj/android-async-http/blob/1.4.7/CHANGELOG.md): 

What I want to to is pass an URL as a parameter within an URL. 

The URL I want to pass looks like: 

     mycompany://app/list?geoid=10809162000&etype=1&esr=2&roomi=2&rooma=2

I encode it with: 

     url = URLEncoder.encode(url, "utf-8");

making it look like: 

    mycompany%3A%2F%2Fapp%2Flist%3Fgeoid%3D10809162000%26etype%3D1%26esr%3D2%26roomi%3D2%26rooma%3D2

and ultimately making a GET request with the encoded URL like: 

    https://api.mycompany.de/filters/mapped?webUri=mycompany%3A%2F%2Fapp%2Flist%3Fgeoid%3D10809162000%26etype%3D1%26esr%3D2%26roomi%3D2%26rooma%3D2

This works fine with 1.4.6 and breaks when upgrading to 1.4.7 or 1.4.8, obviously because of a change in the way the library handles URL encoding. 

Passing the URL unencoded didn't help. 

Unfortunately I don't have access to the server to check how the passed URL argument looks when arriving there. 

So when using >= 1.4.7, how can I pass my encoded URL?

**Comment by smarek** [comment]
have you tried disabling library provided URL encoding feature? Use the [`setURLEncodingEnabled(boolean enabled)`](https://github.com/loopj/android-async-http/blob/1.4.7/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L1363)

**Comment by asco33** [comment]
Aaah, that was exactly what I was looking for, thanks very much!

**Comment by smarek** [comment]
You're welcome!
