### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hatted** [loopj/android-async-http#916]
Today I found your library and try it.  It's 1.4.8 and I got error 
```
Error:(53, 9) error: cannot access AsyncHttpClient
bad class file: /Users/hatted/AndroidStudioProjects/yan.com/Yin/app/libs/android-async-http-1.4.8.jar(com/loopj/android/http/AsyncHttpClient.class)
unable to access file: null
Please remove or make sure it appears in the correct subdirectory of the classpath.
```
but when I use 1.4.7 I got no problem.

**Comment by smarek** [comment]
How do you add the library to your project?

**Comment by hatted** [comment]
Manually copy the jar to the libs folder in the Android Studio.

**Comment by smarek** [comment]
Well, download the library again please, I don't see any problem with JARs neither from github repository (https://github.com/loopj/android-async-http/tree/master/releases) or the Maven repository (https://repo1.maven.org/maven2/com/loopj/android/android-async-http/1.4.8/)

Also download the 1.4.8 and use that, we don't support older versions.

**Comment by hatted** [comment]
Yes, that's the zip file I download from GitHub.  and I also tried the one from http://loopj.com/android-async-http/
<img width="572" alt="screen shot 2015-08-05 at 02 13 09" src="https://cloud.githubusercontent.com/assets/5671197/9068732/c17a99c8-3b17-11e5-8a56-b5eb885b1dc4.png">

**Comment by smarek** [comment]
Can't you use Maven dependency management? Is that Android Studio and Gradle project?

**Comment by hatted** [comment]
Yes, I am using Android Studio 1.3.
Do you mean I should add it from the Project Structure?
<img width="1139" alt="screen shot 2015-08-05 at 02 22 17" src="https://cloud.githubusercontent.com/assets/5671197/9068917/dec2e822-3b18-11e5-9424-165f126b2e03.png">
Since I just copy and paste your 1.4.7.jar to the libs folder, so I think it should works for 1.4.8.jar
