### ISSUE TITLE
Timeout of toast？

### ISSUE THREAD

**Issue by asawalker** [loopj/android-async-http#917]
When the AsyncHttpClient request timeout,it will toast "Connect to 123.xx.xx.xx timeout".
Where to change the message?

**Comment by smarek** [comment]
Library itself doesn't generate any Toast messages, it's your application implementation, we can do nothing about that.

**Comment by asawalker** [comment]
Thanks for you answer.
Do you have the specification for  "statusCode" of onSuccess or onFailure?
What's the status code of request timeout?

**Comment by smarek** [comment]
Well, statusCode is HTTP Status Line (see the sheet here: http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html )

In both onSuccess and onFailure is the same.

However if the request fails to contact the server or retrieve response, statusCode is always 0 (so network problem, server problem, timeout problem). You have to make decision based on returned Throwable in onFailure

**Comment by asawalker** [comment]
Thank you very much！
