### ISSUE TITLE
How to retry if failed?

### ISSUE THREAD

**Issue by theaidorus** [loopj/android-async-http#921]
Hi, I know that I can retry if some exception is raised by:

        client.allowRetryExceptionClass(IOException.class);
        client.allowRetryExceptionClass(SocketTimeoutException.class);
        client.allowRetryExceptionClass(ConnectTimeoutException.class);
        client.allowRetryExceptionClass(UnknownHostException.class);
        client.allowRetryExceptionClass(ConnectionPoolTimeoutException.class);

However, how can i retry the request if the request is failed? I am talking about both get and post.

Thanks

**Comment by LittlePanpc** [comment]
You can re-send your request on `onFailure` of `ResponseHandlerInterface`

**Comment by rogerg9999** [comment]
handler.postDelayed( new Runnable...
    run(){
       ResendRequest()
    },  DELAY_TIME)
