### ISSUE TITLE
HEAD request downloads body

### ISSUE THREAD

**Issue by ioerrorle** [loopj/android-async-http#922]
I'm using this code:
```java
downloader.head(myUrl, new AsyncHttpResponseHandler() {
                @Override
                public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                    for (Header header : headers) {
                        if (header.getName().equals("Content-Length")){
                            Log.d("FileSize", header.getValue());
                        }
                    }
                }
                @Override
                public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                }
            });
```
`responseBody` is `null` as expected when done, but in a fact client dowloads it and i can see it in logs:
`Progress 2546211 from 11563942 (22%)`

**Comment by smarek** [comment]
After some testing, this seems like a problem of server or the way the request is formed.
I've added HeadSample to sample application and tried with several file sources, and every time I got response of size **0**, so really only headers were downloaded.

You can try running the sample application HeadSample on your resources and see if the response is different. See the sample code: a8bb7506c59c13ab0535d474269c24e530146e72
