### ISSUE TITLE
If I send a request from a fragment, how can I cancel this corresponding request when onStop?

### ISSUE THREAD

**Issue by whmsysu** [loopj/android-async-http#923]
I try to use an independent async http client in my project, but when I send a request from fragment, how can I cancel this specific request when the fragment is onStop?

**Comment by smarek** [comment]
You can cancel request using several methods.
- Get the RequestHandle from `.get()` or other methods on AsyncHttpClient, and call `cancel()` on that
- Mark your request with TAG and cancel by TAG from any code
- Cancel requests paired with Context (ie. with your Activity)

Consult sample implementations for details, see: https://github.com/loopj/android-async-http/tree/master/sample/src/main/java/com/loopj/android/http/sample

**Comment by whmsysu** [comment]
Thanks, man.
