### ISSUE TITLE
how can i download gzip resource from remote server.

### ISSUE THREAD

**Issue by webwalker** [loopj/android-async-http#924]
when i download .js file as below:
http://static.sq0.ymatou.com/js/appwap.2015052201.js

error comes:
![qq 20150818110137](https://cloud.githubusercontent.com/assets/3665580/9321641/bfef57a4-459b-11e5-821c-5e8b5cb344d7.png)

what can i do, thanks

**Comment by webwalker** [comment]
my code：
AsyncHttpUtil.get(this, url, new BinaryHttpResponseHandler(AsyncHttpUtil.mAllowedContentTypes) {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] binaryData) {
                int i = 0;
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] binaryData, Throwable error) {
                error.printStackTrace();
            }
        });

**Comment by smarek** [comment]
EOFException means that the stream you were trying to read out was ended prematurely. Your code looks good to me. Are you sure the connection wasn't interrupted by other code of yours or by the server?

**Comment by smarek** [comment]
Closing in favor of #932
