### ISSUE TITLE
Can not support SDK23,can't find org.apache.http.Header

### ISSUE THREAD

**Issue by Modificator** [loopj/android-async-http#925]
http://developer.android.com/sdk/api_diff/23/changes.html

**Comment by smarek** [comment]
duplicate of #830

**Comment by Modificator** [comment]
How to get it

**Comment by Maheshws** [comment]
temporary fix, add this line to gradle:
compile "org.apache.httpcomponents:httpcore:4.3.2"

**Comment by iriki** [comment]
Or just use 

android {
    useLibrary 'org.apache.http.legacy'
}

**Comment by smarek** [comment]
Don't use `org.apache.http` packaged classes, use `cz.msebera.android.httpclient` package, which is used by this library since 1.4.9 version
