### ISSUE TITLE
Can't be compiled when Android SDK is 6.0+

### ISSUE THREAD

**Issue by LittlePanpc** [loopj/android-async-http#926]
Take a first look at here:

http://developer.android.com/sdk/api_diff/23/changes.html?utm_campaign=m-developer-launch&utm_source=dac&utm_medium=blog

Apache packages in Android Pre-Marshmallow are removed since Android 6.0. Theoretically and factually, android-async-http can't be compiled if SDK level is 23+. I have tested this, it is true.

So, what android-async-http will do in Android 6.0+?

**Comment by Maheshws** [comment]
As pointed in other issues it will be fixed in version 1.5.0, which will be a standalone version.

temporary fix, add this line to gradle:
compile "org.apache.httpcomponents:httpcore:4.3.2"

**Comment by smarek** [comment]
Thanks for report, and thanks for temp fix @Maheshws , please continue in disussion in #830
