### ISSUE TITLE
org.apache.http.Header is missing in android M

### ISSUE THREAD

**Issue by luminousman** [loopj/android-async-http#927]

**Comment by luminousman** [comment]
![capture](https://cloud.githubusercontent.com/assets/1277011/9327471/b252a57e-45be-11e5-85df-388f9615dd02.PNG)

**Comment by luminousman** [comment]
https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by smarek** [comment]
Closing as dupe of #830
