### ISSUE TITLE
android 6.0 not work

### ISSUE THREAD

**Issue by BoxuanJia** [loopj/android-async-http#929]
Apache not support.

**Comment by jandrop** [comment]
Same problem here, meanwhile we'll have using the api 22

**Comment by TheNephilim88** [comment]
Duplicate of #927

**Comment by empitechathu** [comment]
+1

**Comment by Maheshws** [comment]
Temporary fix, add this line to gradle:
compile "org.apache.httpcomponents:httpcore:4.3.2"

Issue will be fixed in v1.5.0 as it will be stand alone version.

And before creating new issues please check if similar issue is addressed or not.

**Comment by BoxuanJia** [comment]
Thanks.
1.
android {
    useLibrary 'org.apache.http.legacy'
}
Although the editor will complain, but can be run directly.
2.
dependencies {
    compile 'org.apache.httpcomponents:httpcore:4.4.1'
}
not error

I chose the first one
