### ISSUE TITLE
cookie bug

### ISSUE THREAD

**Issue by zhongjixiuxing** [loopj/android-async-http#930]
HI guys :
   here has a cookie bug, when my cookie Expires is "Sat, 19-Sep-2015 14:39:37 GMT", follow is error information ：

 Invalid cookie header: "Set-Cookie: cuid="jLjjym5xXIgnOy5+xMs/yw=="; Version=1; Max-Age=2592000; Expires=Sat, 19-Sep-2015 14:39:37 GMT; Path=/". Unable to parse expires attribute: Sat
![image](https://cloud.githubusercontent.com/assets/8935235/9386883/37b932f0-4790-11e5-968f-c7ed7c9f4bff.png)

**Comment by smarek** [comment]
I consider this closed with 1.4.9 using upstream 4.3.3 HttpClient, which implements fix for https://issues.apache.org/jira/browse/HTTPCLIENT-1077 which is directly related to lower versions (or non-upstream versions) of HttpClient
