### ISSUE TITLE
Basic Authentication for Get is not working 

### ISSUE THREAD

**Issue by empitechathu** [loopj/android-async-http#936]
Basic authentication for the get is not working .. always return Error "Headers:null"

String uri = 'my.domain.com/' + 'login';

AsyncHttpClient client = new AsyncHttpClient();
client.setBasicAuth("name", "password");

client.get(uri, new JsonHttpResponseHandler() { ... });

this is the code i am using and its not working at all

**Comment by smarek** [comment]
Without further info, I'm not able to help you.
Also try Sample application and it's [`Http401AuthSample`](https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/Http401AuthSample.java) which implements HTTP Basic Auth flow.
