### ISSUE TITLE
How to deal with java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by hush881025** [loopj/android-async-http#939]
when i use the library to make to request,but the server cause java.net.SocketTimeoutException,if I want to deal with it by myself , but  which method where be called?

can not connect terminal net  onFailure
 java.net.SocketTimeoutException

 can not connect terminal net  onFailure
org.apache.http.conn.ConnectTimeoutException: Connect to *** timed out

**Comment by qq2653203** [comment]
when i use my company's wifi i got the same problem

**Comment by 275288698** [comment]
i think u can set the var DEFAULT_SOCKET_TIMEOUT to a bigger number in class AsyncHttpClient

**Comment by hush881025** [comment]
thanks

**Comment by smarek** [comment]
SocketTimeoutException will be handled by library and callback will be received in onFailure method
