### ISSUE TITLE
onFailure not getting called - onFailure(...) was not overriden, but callback was receiced

### ISSUE THREAD

**Issue by MrDarpan** [loopj/android-async-http#944]
onFailure not getting called in my code, I have tried all three methods..

W/JsonHttpRH﹕ onFailure(int, Header[], String, Throwable) was not overriden, but callback was received

```
    private void get() {
        //Request parameters
        RequestParams params = new RequestParams();
        params.put("key", API_KEY);

       MyRESTClient.get("/posts/", null, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                //some code
            }

            @Override
            public void onProgress(long bytesWritten, long totalSize) {
                mLoaderProgress.setText((long) 100 * bytesWritten / totalSize + "Loading...");
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {
                super.onFailure(statusCode, headers, throwable, errorResponse);
                Log.d("Error----> ", ""+statusCode+" ------ "+ errorResponse);
            }
        });

    }
```

**Comment by 275288698** [comment]
u need overwritter the function :
   /**
     * Fired when a request fails to complete, override to handle in your own code
     * @param error the underlying cause of the failure
     * @param content the response body, if any
     */
    public void onFailure(Throwable error, String content) {
        // By default, call the deprecated onFailure(Throwable) for compatibility
        onFailure(error);
    }

**Comment by MrDarpan** [comment]
I tried your above function but still I get below message, and no log is generated...

W/JsonHttpRH﹕ onFailure(int, Header[], String, Throwable) was not overriden, but callback was received

**Comment by MrDarpan** [comment]
I think I am overriding wrong method,

Below is  correct one and worked..

```@Override
            public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                super.onFailure(statusCode, headers, responseString, throwable);
                Log.d("Failed: ", ""+statusCode);
                Log.d("Error : ", "" + throwable);
            }

**Comment by smarek** [comment]
Yes, watch the LogCat if you're using the *ResponseHandler class correctly, it shows important warnings and errors there.

**Comment by nhiepphong** [comment]
Hi Bro,

I have a error.

D/Failed:: 500
07-04 08:49:22.544 10043-10043/com.nhiepphong.NameCard D/Error :: cz.msebera.android.httpclient.client.HttpResponseException: Internal Server Error
07-04 08:49:22.857 10043-10043/com.nhiepphong.NameCard W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-04 08:49:23.118 10043-10043/com.nhiepphong.NameCard I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
07-04 08:49:23.358 10043-10043/com.nhiepphong.NameCard I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@854cfc1 time:50872411

Can you help me ?
