### ISSUE TITLE
Google Map Directions Api Response

### ISSUE THREAD

**Issue by javagc** [loopj/android-async-http#949]
Hi, thanks for this project. It is great. I am trying to use google map directions api, normally api link is 

https://maps.googleapis.com/maps/api/directions/json?destination=42.22255953253769,43.083742037415504&origin=42.22255953253769,43.083742037415504

and it is working correctly from browser,

my code is

 RequestParams params = new RequestParams();

  params.add("origin", "42.22255953253769,43.083742037415504");
  params.add("destination", "42.22255953253769,43.083742037415504");

  AsyncHttpClient asyncHttpClient=new AsyncHttpClient();
  asyncHttpClient.get("https://maps.googleapis.com/maps/api/directions/json", params, new TextHttpResponseHandler() {
                            @Override
                            public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                            }

                            @Override
                            public void onSuccess(int statusCode, Header[] headers, String responseString) {
                            }
                        });
responce is 

���������������Vێ�0}�WX~�V٤i�}�zI�U�R�V�V�N�,��MV��~Yp]�@�����{��4��B��ғ���>�\脒3�Ċu]?L�&tjh��5�6(q���Y�=�:xY�2Z_�x�;�d��*bm�����*�j�ĩ���?�Q>C���"}��`m|-!���J8<�����l���)�7�����j�\�-���@�Bf�㟋w��M=���G�
Ą���f>;]���~�V�C�rV�-�����΄J�Ư&)zJ"�ʧdd�f��>zl��R�K1*�!"
�c
��x�I`S��wp��!�d�R��A�!��~.}��d��9=R��YT���<0�e�����i�F�y���}�c::z�P%c�XSG��;��Y��B��D��+�UN}���@c�C.�z{7CitH?o�>����q���nZA���פ�|��}ۙ���7��e~�;̿�X����Tf�2���ߓ�>XC+I��ް�ٔ�\��ɱ�J�+Uq��7o�er�|�*l�v	����

when I try other android client, it is working. maybe I need additional parameters or not

**Comment by smarek** [comment]
This is duplicate #932 
I have fixed it temporarily in latest 1.4.9-SNAPSHOT
Easy workaround is to disable GZIP support using this solution https://github.com/loopj/android-async-http/issues/932#issuecomment-134549073

**Comment by javagc** [comment]
OH! thank you man! you save my day

**Comment by smarek** [comment]
You're welcome :smiley:

**Comment by clq123clq** [comment]
very good，I meet this  problem and waste a day to search it.Now you help me solve it,very thanks
