### ISSUE TITLE
find a download file bug

### ISSUE THREAD

**Issue by taosimple** [loopj/android-async-http#951]
I use ```RangeFileAsyncHttpResponseHandler``` to downloading a file , when i shut down the network(WIFI and mobile network) ,at device nexus5 android 5.1.1  the method ```public void onSuccess(int statusCode, Header[] headers, File file)``` is callback and ```statusCode == 200``` ,but on another device 4.2.2 is ok the method ```public void onFailure(int statusCode, Header[] headers, Throwable throwable, File file)``` is normal callback
ps: android-async-http sdk is 1.4.8

**Comment by smarek** [comment]
This is possible outcome, question is, what data is returned? Specifically is the file download completed (or the specified range) or not?

**Comment by taosimple** [comment]
when i shut down the network , the file downloading is not completed
