### ISSUE TITLE
Download not canceable

### ISSUE THREAD

**Issue by JamesCullum** [loopj/android-async-http#952]
I use this code to initiate a download
`client.get(realdownload, new FileAsyncHttpResponseHandler(cachefile) {`
having `onProgress`.

If the user presses "Cancel" i want to stop the whole Download and the ResponseHandler, i tried using `client.cancelAllRequests(true)` but onProgress still fires the rest of the download, except that it's unusually faster than before.

Please implement a possibility to abort a download.

**Comment by smarek** [comment]
In fact you've successfully aborted the request (and there are multiple ways to abort the specific request or all requests), have you looked into the file what is the final content, if you cancel the request while it's running? What callbacks do you get after canceling it? See the Sample application for reference on how to properly cancel requests.

https://github.com/loopj/android-async-http/tree/master/sample/src/main/java/com/loopj/android/http/sample

**Comment by JamesCullum** [comment]
Your reference link is quite abstract, please point it directly to the method you're refering to.
All callbacks like onProgress / onSuccess execute like a successfull download, as i said i do get the onProgress - Callback in a high speed for every couple bytes it loaded (or skipped, who knows).
As i delete the file when canceling the download (as the cancelling doesnt work) i can not tell if the file would be existing / corrupt.

**Comment by smarek** [comment]
@JamesCullum yes, because you have to put some effort to solve the problem, we're here to deal with specific library problems. on the other hand, `who knows` statement is quite abstract to me, it's your use-case and application, so *you should know*

**Comment by htooaunghlaing** [comment]
How to cancel specific download process, because i have parallel download process

**Comment by smarek** [comment]
abstract code could be like this:
```
RequestHandle handle = AsyncHttpClientInstance.get(...);
handle.cancel();
```
This principle is demonstrated in sample https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/CancelRequestHandleSample.java

Or you can put TAG on specific request and cancel the request by TAG
which is shown here: https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/CancelRequestByTagSample.java
