### ISSUE TITLE
Frequently failing to download with 403 status code

### ISSUE THREAD

**Issue by bluemix** [loopj/android-async-http#953]
Sometimes when I use FileAsyncHttpResponseHandler, the file gets downloaded, but, most of the time, it fails with 403 status code. I am using the library version of 1.4.8.
I've used another library (https://github.com/scruffyfox/AsyncHttpClient), and didn't get the 403 status code problem. I just wanted to inform you about this issue.

**Comment by smarek** [comment]
Well this information is useless, without knowing how you do use the library or what is the cause for server response. 403 means forbidden, so I guess you're talking about authorization issues? Please update us with more info. Thanks
