### ISSUE TITLE
AsyncHttpResponseHandler the method onFailure or onSuccess never called

### ISSUE THREAD

**Issue by zmpcwl** [loopj/android-async-http#954]
when i send request and the server response a  String {"sq":1441872636840,"result":0,"data":"xx"} encode by DES, but the instance of  AsyncHttpResponseHandler's method onFailure or onSuccess never called.so,how can i receive the response.
PS：logs show the server had responsed
version 1.4.8

**Comment by smarek** [comment]
Show us some code, about how you place the request through the library.

**Comment by cqtddt** [comment]
Hello,smarek,can you tell me the reason of method onFailure or onSuccess never called? and, can you tell me  what situations  appears in of this issue?  Thank you for your answer!

**Comment by cqtddt** [comment]
zmpcwl ,can you tell me  what situations appears in of this issue in your project?  Thank you for your answer!
