### ISSUE TITLE
AsyncHttpClient in loop

### ISSUE THREAD

**Issue by dominicsavb** [loopj/android-async-http#955]
how is the best implementation?

I use AsyncHttpClient in loop like this
```
for (int i = 0; i <= 1000; i++) {\
AsyncHttpClient client = new AsyncHttpClient();
client.get("http;//......, new AsyncHttpResponseHandler() {
});
}
```
when I use wifi, it is finished ok with 1000 success... server log has 1000 request....

but when I use mobile data... it is finished with less than 1000 success... and server log has less than 1000 request too..... 

how is the best implementation AsyncHttpClient in loop? 

Thank you before....

**Comment by dominicsavb** [comment]
in mobile data case... 

client 1000 request to server but not server not get 1000 request...

why?

**Comment by smarek** [comment]
Is there any info about number of requests / spawned threads in ExecutorService impl in LogCat?

**Comment by smarek** [comment]
Best for your case could be setting ThreadPool/ExecutorService implementation from default `Executors.newCachedThreadPool()` to something different, maybe `Executors.newSingleThreadExecutor()` would be more suitable for such high number of requests on mobile network

You can pass your own ExecutorService choice through `AsyncHttpClient.setThreadPool(ExecutorService)` method

**Comment by dominicsavb** [comment]
How to implement it?

Thank you for your help

**Comment by dominicsavb** [comment]
Ok. I already implement it....

but how to know the executor service is finished?

Thank you
