### ISSUE TITLE
How can i know the progress of the upload (post)?

### ISSUE THREAD

**Issue by march1993** [loopj/android-async-http#956]
It seems that `onProgress' only shows the download progess?

**Comment by smarek** [comment]
Yes, this is known feature, closing as duplicate of #239

**Comment by march1993** [comment]
public void onProgress(long bytesWritten, long totalSize) {
    // Progress notification
    if(totalSize > 4096) {
        Log.d("now: ", bytesWritten.toString();
    }
}
but i get no log

**Comment by smarek** [comment]
Again, yes, there is no library provided upload onProgress, just download.

**Comment by march1993** [comment]
so sad
