### ISSUE TITLE
Retry handler not working correctly

### ISSUE THREAD

**Issue by vinod-jaiswal18** [loopj/android-async-http#958]
I am trying to implement retry with the following parameters:

1. Max Retry Counter: 5 times
2. Sleep timer between each request: 5000 ms
3. Response timeout: 10000 ms

My code for this implementation is:

client.setMaxRetriesAndTimeout(5, 5000);
client.setResponseTimeout(10000);

But the code is not working, as it should.

My question is, 
Is my implementation correct? Help me where I am going wrong?

**Comment by smarek** [comment]
Request is not repeated 5 times, it's tried maximum of 5 times to finish successfully, then the library will give up. For more info see the javadocs of mentioned methods.
