### ISSUE TITLE
Method does not override method from its superclass

### ISSUE THREAD

**Issue by cynephoba** [loopj/android-async-http#959]
Hi,

I'm trying to implement the example you have on this page: http://loopj.com/android-async-http/ (about the static HTTP class)

This is the code that I have:
```java
MyHttpClient.get("&type=login", params, new JsonHttpResponseHandler() {
			@Override
			public void onStart() {
				/** Show the loading dialog */
				bus.post(true);
			}
			@Override
			public void onSuccess(int i, Header[] headers, JSONObject obj) {

			}

			@Override
			public void onFailure(int i, Header[] headers, JSONObject o, Throwable throwable) {
				bus.post(false); //Hide the progress dialog if its visible
				MyHttpClient.failureHandlerMethod(i, headers, o, throwable); //stock handler.
			}
		});
```

However on the `@Override` annotation, i'm getting an error: "Method does not override method from its superclass".

Is there no onFailure method for the JsonHttpResponseHandler? Or should I use the `AsyncHttpResponseHandler` method and attempt to cast the byte array to a JSONObject? (all results from the website come in the form of a JSONObject).

Here is the code from my static class:

```java
public class MyHttpClient {

	private static final String BASE_URL = "http://url.com";

	private static AsyncHttpClient client = new AsyncHttpClient();

	public static void get(String url, RequestParams params, AsyncHttpResponseHandler responseHandler) {
		client.get(getAbsoluteUrl(url), params, responseHandler);
	}


	public static void post(String url, RequestParams params, AsyncHttpResponseHandler responseHandler) {
		client.post(getAbsoluteUrl(url, false), params, responseHandler);
	}
```

I'm using version 1.4.9-SNAPSHOT and have cz.msebera.android:httpclient:4.3.3 included.

**Comment by offmadisonave** [comment]
+1 I ran into this myself just now, though I'm using 1.4.8.  Compile SDK 23, Build Tools 23.0.1

**Comment by emaddoma** [comment]
I ran into this myself just now, though I'm using 1.4.8. Compile SDK 23, Build Tools 23.0.1

**Comment by smarek** [comment]
There are in fact three callbacks in JsonHttpResponseHandler, however your implementation missed all three signatures.
For reference, in current version (1.4.9-SNAPSHOT)

```java
@Override
public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {}
@Override
public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONArray errorResponse) {}
@Override
public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {}
```

In your case, change the signature from `int, Header[], JSONObject, Throwable)` to `int, Header[], Throwable, JSONObject`

Also note that JsonHttpResponseHandler will be deprecated with this or next release, and should be replaced by using BaseJsonHttpResponseHandler for correct deserialization using other JSON implementation than default Android one

**Comment by cynephoba** [comment]
Hi,

Im trying to implement it using the BaseJsonHttpResponseHandler like you suggested, however i'm running into the same problem.

``` java
@Override
public void onSuccess(int statusCode, Header[] headers, String rawJsonResponse, JsonObject response) {
```
This gives me the same issue as before, where it doesn't override the base class. Looking at the source code, this should be correct (unless i'm messing up with the changing of JSON_TYPE)

**Comment by smarek** [comment]
is it again `Method does not override method from its superclass` ? If so, you should learn to code man, there is nothing wrong with the library, since your first problem was too solved by looking into documentation, sources and using the IDE correctly.

Also put here some of your sources and stacktraces if they happen, so it's possible for me to help you.

Last thing, generally, if the issue is not issue of the library (or at least hint, it could be), do ask on StackOverflow.com or elsewhere, you're wasting my time asking for basic programming tips here.

**Comment by cynephoba** [comment]
Same error. I asked a second time because the solution you proposed to future proof the application did not work, as your documentation isn't very clear. If you dont wish to help that's fine i shall go elsewhere.

**Comment by smarek** [comment]
You're missing the point, you should override the methods, there is no way I could solve this for you and this is not issue of library, if you cannot simply override an interface or abstract class, yes, go ask elsewhere. This is not about library documentation, we expect the developers to think at least a bit.
And I wish to help you, but I cannot teach you programming, that's not the purpose of this issue tracking system.

**Comment by Ronanb3** [comment]
I am surprised by this comment. Try to understand or just don't answer instead of saying that someone doesn't know how to code. Every one started one day.
My guess is that you are using the wrong library. The error message is misleading. It show Header[] only and not the difference between org.apache.http.Header and cz.msebera.android.httpclient.Header.
Try using cz.msebera.android.httpclient.Header.
