### ISSUE TITLE
GZIP - What I am doing wrong? on 1.4.9

### ISSUE THREAD

**Issue by toni1727** [loopj/android-async-http#964]
I have read this issue: https://github.com/loopj/android-async-http/issues/641

I don't want deactivate the Gzip Encoding.

This is my PHP file:

    <?php header('Content-Type: text/html; charset=UTF-8');

    ob_start("ob_gzhandler");
    $json = array();
    $json['Result'][] = array("Result"=>"Hello World");
    echo json_encode($json);

this is how I make the call:

		AsyncHttpClient client = new AsyncHttpClient();
        client.setSSLSocketFactory(MySSLSocketFactory.getFixedSocketFactory());
		client.post(server_url_https, params, new AsyncHttpResponseHandler() {
		    @Override
            public void onSuccess(int statusCode, cz.msebera.android.httpclient.Header[] headers, byte[] responseBody) {
			result = new String(responseBody, "UTF-8"); 
			}
			@Override
            public void onFailure(int statusCode, cz.msebera.android.httpclient.Header[] headers, byte[] responseBody, Throwable error) {
			}
		}

and I get the same weird response:

![gzip](https://cloud.githubusercontent.com/assets/11811056/9980753/8fcff3da-5fa4-11e5-9d8d-7c3b210603b2.jpg)

What I am doing wrong? I thought that this was solved in 1.4.9

Thank you very much.

**Comment by smarek** [comment]
Fix was introduced with #932 and commit dc184805534a66076b995f2c6f6373b13aeada76
Which fixed the issue for me in testing environment where I could previously reproduce the problem.

However I don't see you sending out Content-Encoding header with gzip within

**Comment by toni1727** [comment]
This is the header:

![header](https://cloud.githubusercontent.com/assets/11811056/9980831/e511bede-5fa7-11e5-9f95-b91f367cb1b4.jpg)

**Comment by smarek** [comment]
Do you have the android-async-http library from Maven or included as source? I'd like to have you put some debug code in AsyncHttpClient, specifically into `isInputStreamGZIPCompressed`

Or if you can but a breakpoint there and find out what is content of `byte[] signature` and `int streamHeader` near the **return** from method, because this seems weird to me.

Thanks

**Comment by toni1727** [comment]
dependencies {
    compile 'com.loopj.android:android-async-http:1.4.9'
}

If you tell me the file and the line where I have to put the breakpoint, I put and I show you the values.

**Comment by smarek** [comment]
`com.loopj.android.http.AsyncHttpClient` function `isInputStreamGZIPCompressed`, line cca 385

**Comment by toni1727** [comment]
![break](https://cloud.githubusercontent.com/assets/11811056/9980937/fa0b22da-5fac-11e5-81e8-59bde858cc20.jpg)

**Comment by smarek** [comment]
That seems to be the problem, Signature `0x10 0x10` does not match the GZip compression signature, which is `0x8b 0x1f`, are you sure you are using Gzip and not Deflate compression?

**Comment by toni1727** [comment]
I solved the problem. 

The problem was the PHP file.

echo gzencode(json_encode($json), 9);

and remove "?>" at the end of the php files.

In this way, the Signature is right.

Thank you very much.

**Comment by smarek** [comment]
No problem, glad to be of any help !
