### ISSUE TITLE
post JSON Object allongside files with multipart form data

### ISSUE THREAD

**Issue by njgarcia** [loopj/android-async-http#965]
Hi, I need to make a POST request and send two types of content in the same request:

- a JSON object with some data (application/json)
- some files (Multipart form data)

I can post files with RequestParams, but I can't add a JSON object to it.

I can post the JSON Object with a String entity, but I can't attach files to it!

How can I achieve this?

**Comment by smarek** [comment]
This is multipart scenario, you put String as one part and Files as other parts and send it. Use Either upstream MultipartEntity or use RequestParams, add files, add Json as String and post.

**Comment by njgarcia** [comment]
The problem with request params is that when I try to add the JSON as string, I must set a "key" value, but I need to send it without a key, I don't know if you understand what I mean

**Comment by smarek** [comment]
I understand, but in that case you just want to send files, one file with JSON and more files with other content, because you can't mix up JSON-only (StringEntity) request and include other content (neither form values or files etc...)
