### ISSUE TITLE
Invalid URL transformation after version 1.4.7

### ISSUE THREAD

**Issue by divyenduz** [loopj/android-async-http#966]
Our API has endpoints like

`<endpoint>/get_data/<slug>`
Where slug = `<sportname>%2f<title>`
for eg. **football%2fronaldo-scores-a-goal**
`%2f is html form of /`

The library was working for us up to version 1.4.6. BUT after upgrading to version 1.4.7 the slug gets auto converted to
**football/ronaldo-scores-a-goal**

So, something got triggered in version 1.4.7 converting %2f to /
I am trying to figure out the same by reading the commits in tag 1.4.7 
BTW this link is not working (https://github.com/loopj/android-async-http/commits1.4.7)

Also, we will need a API to disable this transformation. If that can't be done, I will need to maintain a fork of this project as a upstream.

As well, kudos for the good work.
Thanks

**Comment by smarek** [comment]
Version 1.4.7 changelog states, **Fixed URL encoding feature, that was breaking whole URL, not just path and query parts**, which is issue #691 and related commit b3e15c3d1d51e3faf74336d8c82860e022f6bfc8

If you don't want the URL to be automatically encoded, and possibly fixed if it contains errors, call `setURLEncodingEnabled(false)` on `AsyncHttpClient` instance, see the source for reference:
https://github.com/loopj/android-async-http/blob/b3e15c3d1d51e3faf74336d8c82860e022f6bfc8/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L1214

**Comment by divyenduz** [comment]
Thanks
