### ISSUE TITLE
getHttpClient().getParams() deprecated

### ISSUE THREAD

**Issue by captainbupt** [loopj/android-async-http#969]
I have updated the library and I found this function is deprecated. I just want to know what is the substitution for this function. I'm using like below:

       client.cancelRequests(context, true);
       // when cancel requesst, the redirection will be shut down too. So, open the redirection again.
       client.getHttpClient().getParams().setParameter(ClientPNames.ALLOW_CIRCULAR_REDIRECTS, true);

**Comment by smarek** [comment]
It is deprecated by upstream, no need to switch code now.
Also to allow circular redirects, I'd suggest you to use official API `AsyncHttpClient.setEnableRedirects(final boolean enableRedirects, final boolean enableRelativeRedirects, final boolean enableCircularRedirects)`

Which will shield you from deprecation messages for now.

Code: https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L591
