### ISSUE TITLE
Sending JSON objects

### ISSUE THREAD

**Issue by IshanPunchihewa** [loopj/android-async-http#970]
I want to send the following code 
```java
RequestParams params = new RequestParams();
        params.add("action", "login");
        params.add("user_name", username);
        params.add("user_pwd", password);
        params.add("gcm_id", sharedPreferences.getString(TwofeetConstants.DEVICE_ID,null));
```
as a JSON string to the server

like this 

```java
			JSONObject	 obj = new JSONObject();		 
			 try 
			 {
				obj.put("action", "login"); 
				obj.put("user_name", etUserName.getText().toString());
				obj.put("user_pwd", etPassword.getText().toString());
				obj.put("gcm_id", urls[0]);
				
			} catch (JSONException e) {
				e.printStackTrace();
			}
			return lk.infoseek.twofeet.JSONParser.POSTDATA(Constants.POST_USERDATA_URL, obj);
```
how to do this.. thanks in advance

**Comment by smarek** [comment]
Try simply calling `params.setUseJsonStreamer(true);` to send the data as Json string

**Comment by IshanPunchihewa** [comment]
I am totally new to this library.. so bare with me if i ask anythig stupid 

following is the updated code

  RequestParams params = new RequestParams();
        params.setUseJsonStreamer(true);
        params.add("action", "login");
        params.add("user_name", username);
        params.add("user_pwd", password);
        params.add("gcm_id", sharedPreferences.getString(TwofeetConstants.DEVICE_ID,null));

   try {
            api.apiCall(TwofeetConstants.POST_USERDATA_URL, params, new OnApiFinishedListener() {
=============================================================

but i keep getting this error
onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
    org.json.JSONException: Response cannot be parsed as JSON data
            at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:157)
     
i printed the params and i got
action=login&gcm_id=358639060235903&user_name=Hasunika&user_pwd=123

this doesn't seem like a JSON String..

**Comment by smarek** [comment]
Two things, you printed params, but they are sent in JSON, this should be checked on server side, or post the data to `https://httpbin.org/post` which will return them back to you, so you can check the request is fine.

Second, response you've got from server is apparently not a JSON data, there is no need to use JsonHttpResponseHandler, if you're not expecting JSON data to come back as response.

**Comment by matejhacin** [comment]
I have similiar problem and I can't figure out how to solve it. I need to send this JSON to API.

    {
        "firstName":"frwferfwg",
        "lastName":"wergwerg",
        "address":{
                "address1":"wergwerg",
                "zipCode":"ergee",
                "city":"wgergwerg",
                "country":"SI"},
        "gsm":"+38631123123",
        "email" : "ergwergwerg@gmail.com",
        "password" : "12345678"
    }

I've been trying to post it like this:

    RequestParams requestParams = new RequestParams();
    requestParams.put("firstName", newUser.getFirstName());
    requestParams.put("lastName", newUser.getLastName());
    requestParams.put("email", newUser.getEmail());
    requestParams.put("password", newUser.getPassword());
    requestParams.put("address.address1", newUser.getAcAddress().getAddress1());
    requestParams.put("address.zipCode", newUser.getAcAddress().getZipCode());
    requestParams.put("address.city", newUser.getAcAddress().getCity());
    requestParams.put("address.country", newUser.getAcAddress().getCountry());
    requestParams.put("gsm", newUser.getGsm());

Which used to work but doesn't anymore. It doesn't recognize the address.address1, address.zipCode, address.city, address.country on server side. So I need to find a different way to do it.

I've also tried creating JSONObject with "address1", "zipCode", "city", "country" and putting it to RequestParams under key "address" but that doesn't work either.

Also tried using `params.setUseJsonStreamer(true);` but that also returns error. I've Googled other ways to post JSON using this library but all I could find was `StringEntity` which is deprecated.

Any help would be greatly appreciated.

**Comment by IshanPunchihewa** [comment]
http://stackoverflow.com/questions/13052036/posting-json-xml-using-android-async-http-loopj

that one worked for me.. give it a try

**Comment by matejhacin** [comment]
This is where the problem is for me. `StringEntity entity = new StringEntity(jsonParams.toString());`.

`StringEntity` is now deprecated. How do I do it now?

**Comment by smarek** [comment]
@matejhacin StringEntity is not deprecated, only one of the constructors seems deprecated to me from documentation. In both cases, deprecated doesn't mean it won't work, so I wouldn't worry about it now.

**Comment by matejhacin** [comment]
@smarek I just realized where the problem was. I was using older version of async http library (1.4.5) which still relied on Apache library, which is no longer used in Android.

I now updated async http to the newest version 1.4.9 and now it works with `StringEntity` from `cz.msebera.android.httpclient package`.

**Comment by smarek** [comment]
:)) Cool, @matejhacin glad to know you've found solution
