### ISSUE TITLE
1.4.9 + proguard : not called onSuccess, onFailure

### ISSUE THREAD

**Issue by asamaru7** [loopj/android-async-http#975]
I am sorry. my english is not good.

I use 1.4.9.
proguard off : work.
proguard on : onSuccess, onFailure not called.

my proguard.
```
-optimizationpasses 5
-repackageclasses ''
-allowaccessmodification
-overloadaggressively
-verbose
```

but I add ```-keep class com.loopj.android.http.HttpGet { *; }``` to proguard. this is work(onSuccess, onFailure called).

**Comment by divyenduz** [comment]
Where to add this, Just CHANGELOG.md or somewhere else as well ? I can take this one up.

**Comment by smarek** [comment]
See the comment in #976 please

**Comment by asamaru7** [comment]
@smarek 

for android 4.0.4

```
-keep class cz.msebera.android.httpclient.HttpResponse { *; }
-keep class com.loopj.android.http.HttpGet { *; }
-keep class com.loopj.android.http.HttpDelete { *; }
```

**Comment by divyenduz** [comment]
@smarek : Is CHANGELOG.md the right file to put this ? Because this can turn into a long list ?

**Comment by htooaunghlaing** [comment]
@smarek 
now , i m facing with this
The type cz.msebera.android.httpclient.HttpResponse cannot be resolved. It is indirectly referenced from required .class files..i changed from 1.4.4 to 1.4.9

**Comment by smarek** [comment]
I've just provided https://github.com/loopj/android-async-http/commit/ff9633e3ac00b8aa864570abc640f4bcabf6a5a5

So the default rules are known and if you can, USE MAVEN DEPENDENCY MANAGEMENT, I'm really sick of all issues related to devs not able to use JAR distributions because dependencies are missing.
