### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by wirasto** [loopj/android-async-http#977]
Why need resolve hostname since I use ip address?

```
java.net.UnknownHostException: Unable to resolve host "myhostname": No address associated with hostname
```

I tried other library and work fine :(

**Comment by smarek** [comment]
How do you use the library? Show us code please.

**Comment by wirasto** [comment]
```java
AsyncHttpClient client = new AsyncHttpClient();
client.get("http://<ip_address>/api/test", new JsonHttpResponseHandler() {
.....
.....
});
```

I found the solution but strange :)  "Cellular data" must be On

**Comment by smarek** [comment]
That's strange, well we should add an IP address use-case to our samples, to make sure it works properly. Could it be that your DNS on wifi / tethering setting was not picking up on the IP address correctly?

**Comment by wirasto** [comment]
I think my network is fine. 
Like I said, other library (volley) work fine.

**Comment by smarek** [comment]
Have you tried defining your HttpUriRequest in meaning of these SO threads?
https://stackoverflow.com/questions/18766705/unable-to-resolve-host-url-no-address-associated-with-hostname
https://stackoverflow.com/questions/9350732/android-unable-to-resolve-host

**Comment by qianjin** [comment]
I use ip address in url and find 'host' in header has auto set the ip address by these code in AsyncHttpClient :
```
 httpClient.addRequestInterceptor(new HttpRequestInterceptor() {
            @Override
            public void process(final HttpRequest request, final HttpContext context) throws HttpException, IOException {
                AuthState authState = (AuthState) context.getAttribute(ClientContext.TARGET_AUTH_STATE);
                CredentialsProvider credsProvider = (CredentialsProvider) context.getAttribute(
                        ClientContext.CREDS_PROVIDER);
                HttpHost targetHost = (HttpHost) context.getAttribute(ExecutionContext.HTTP_TARGET_HOST);

                if (authState.getAuthScheme() == null) {
                    AuthScope authScope = new AuthScope(targetHost.getHostName(), targetHost.getPort());
                    Credentials creds = credsProvider.getCredentials(authScope);
                    if (creds != null) {
                        authState.setAuthScheme(new BasicScheme());
                        authState.setCredentials(creds);
                    }
                }
            }
        }, 0);
```

I need to set host in header then my server can know this request,so I do this in my project:

```
  client.getHttpContext().setAttribute(ClientContext.TARGET_AUTH_STATE,"test");
  client.addHeader("Host", "xxxhost.com");
```

then the url whit ip address request success 

Are there  other ways to set host it ?

Version 1.4.9

**Comment by wirasto** [comment]
@smarek what do you mean? I only try example from this url http://loopj.com/android-async-http/.

**Comment by smarek** [comment]
@wirasto there are samples of implementation provided along with the library in repository, https://github.com/loopj/android-async-http/tree/master/sample/src/main/java/com/loopj/android/http/sample

These can be built and installed on device, so you can test if your device is behaving correctly or if the library has any issues with that particular device.

**Comment by victorbucutea** [comment]
I have the exact same problem. I don't see how the example code might help. I'm running the application on my mobile phone and the server is on my laptop so I need to use the IP adress. Somehow the API resolves the IP address to a hostname and tries to contact it.

**Comment by WiRight** [comment]
Hey there!
I have the same problem!
But, if i try use remote url (my hosting), all be ok
But in other way, using local address (nginx web server with yii2), a have error "Unable to resolve host "yii.hostname.local": No address associated with hostname"
In my hosts file have a line about it (linux mint 18)
Thx
