### ISSUE TITLE
Please provide a full example for Persistent cookie store

### ISSUE THREAD

**Issue by acrolink** [loopj/android-async-http#978]
I need to store a cookie after successful login to a remote Rest server. Basically, I would like to reuse this cookie in future communications between my app and the remote server, even after exiting the app.

My question is how to use the store to save session information and then re-use in a future request. 

I can retrieve the session id and token value from the server at login and actually I think I can store them in Shared preferences for future use, but I feel that the Persistent cookie store is the right and more correct solution.

Thanks.

**Comment by acrolink** [comment]
I have looked around on the internet and I still cannot understand how to save a cookie upon authentication (first time) and use it again to access RESTful server endpoints at later time even after application restart / device restart.

**Comment by smarek** [comment]
Sample of PersistentCookieStore was always available in Sample application implementation, see here: https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/PersistentCookiesSample.java

**Comment by acrolink** [comment]
I have managed to store and use a cookie after initial authentication with remote server. Subsequent Restful GET requests are allowed (meaning that the remote server identifies those requests as authenticated). However, if I close the app and launch it again, I have to login again to the remote server, meaning that the cookie got lost somehow between application's restart. Any idea what might be causing this? Thanks.

**Comment by smarek** [comment]
Is the cookie lost or does the auth session expire on backend?

**Comment by acrolink** [comment]
I start the application and login. The cookie seems to get stored since I am able to retrieve data from the server from protected URL's (that require authentication). However, if I exit the app and start it again I will need to login again, otherwise I would receive a 403 error.

**Comment by smarek** [comment]
Does your server set any special flags to cookies? Like temporary, special path or anything? Because PersistentCookieStore works for me in such cases

**Comment by acrolink** [comment]
@smarek Thank you. It might be that I am doing something wrong, or that something is missing. Here is my code:

```
package link.acro.cookie;

import java.security.NoSuchAlgorithmException;

import javax.net.ssl.SSLContext;

import org.json.JSONException;
import org.json.JSONObject;

import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.JsonHttpResponseHandler;
import com.loopj.android.http.PersistentCookieStore;
import com.loopj.android.http.RequestParams;

import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import cz.msebera.android.httpclient.Header;
import cz.msebera.android.httpclient.conn.ssl.SSLConnectionSocketFactory;
import cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory;


public class MainActivity extends Activity {
	
	public static AsyncHttpClient Client = new AsyncHttpClient();
	public static PersistentCookieStore myCookieStore;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		myCookieStore = new PersistentCookieStore(this);
		Client.setCookieStore(myCookieStore);
		
		
	}

	// Login method

	public void login(View v) {
		
		// ALLOW_ALL_HOSTNAME_VERIFIER
		SSLSocketFactory sf = null;
		
    	try {
			sf = new SSLSocketFactory(
					SSLContext.getDefault(),
					SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
		} catch (NoSuchAlgorithmException e1) {
			e1.printStackTrace();
		}
   
    
    	Client.setSSLSocketFactory(sf);
    	 
		Client.addHeader("Content-Type", "application/json");

		RequestParams params = new RequestParams();
		params.setUseJsonStreamer(true);
		params.put("username", "***");
		params.put("password", "***");
	
		
		Client.post("https://www.myserver.net/rest/user/login", params, new JsonHttpResponseHandler() {         
		    @Override
		    public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
		    	
		    	String r = response.toString();
		    	String token = "";
				
		    	JSONObject jsonObj = null;
				 try {
					jsonObj = new JSONObject(r);
					token = jsonObj.getString("token");
				} catch (JSONException e1) {
					e1.printStackTrace();
				}
				 
				 // Store authentication token to SharedPreferences to be used in subsequent requests
				 SharedPreferences sharedPref = contextOfApplication.getSharedPreferences("LOGIN_DATA", Context.MODE_PRIVATE);
				 SharedPreferences.Editor editor = sharedPref.edit();
				 editor.putString("TOKEN", token);
				 editor.commit();
		    	
		    	 Log.d("Response", token);  	
		    }

		        public void onFailure(int statusCode, Header[] headers, String res, Throwable t) {
				Log.d("Response", String.valueOf(statusCode));  
		        }
		});
		
	}
	
	// Get data that requires authentication

	public void get(View v) {
		
		// ALLOW_ALL_HOSTNAME_VERIFIER
		SSLSocketFactory sf = null;
    	try {
			sf = new SSLSocketFactory(
					SSLContext.getDefault(),
					SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
		} catch (NoSuchAlgorithmException e1) {

			e1.printStackTrace();
		}
   
    
    	 Client.setSSLSocketFactory(sf);

		 Client.addHeader("Content-Type", "application/json");
		
		// Get previously stored authentication token
		 SharedPreferences sharedPref = contextOfApplication.getSharedPreferences("LOGIN_DATA", Context.MODE_PRIVATE);
		 
		 String token = sharedPref.getString("TOKEN", "");
		 Client.addHeader("X-CSRF-Token", token);
		 Log.d("SAVEDTOKEN", token);
		
		Client.get("https://www.myserver.net/json", new JsonHttpResponseHandler() {         
		    @Override
		    public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
		    	
		    	String r = response.toString();
		    	
		    	Log.d("Response", r);
		    	
		    }

		        public void onFailure(int statusCode, Header[] headers, String res, Throwable t) {
		            // called when response HTTP status is "4XX" (eg. 401, 403, 404)
		        	
		        	Log.d("Response", String.valueOf(statusCode));
	}
		});	
	}
}

```

**Comment by pkyad** [comment]
@acrolink  Did you solve this issue yet ?. I am facing the same .

**Comment by acrolink** [comment]
@pkyad 

Cannot truly remember what worked but I am pretty sure the important thing here, as I review my working code 👍, is to pass the same `context` variable to the HTTP function on the first request (let us say the login request) and all subsequent ones. Foe example in POST operation:

```
Client = new AsyncHttpClient();
Client .post(mContext, url, jsonParams, new AsyncHttpResponseHandler() {
...
}
```

You need to pass the same `mContext` to the function making the login for example and all other functions communicating with the server.
