### ISSUE TITLE
String Entity not working anymore

### ISSUE THREAD

**Issue by IshanPunchihewa** [loopj/android-async-http#979]
i update the library to the new version but i am having trouble importing import org.apache.http.entity.StringEntity; to my project since i am using

 JSONObject jsonParams = new JSONObject();
        StringEntity entity;
       

        try {
            jsonParams.put("action", "login");
            jsonParams.put("user_name", username);
            jsonParams.put("user_pwd", password);
            jsonParams.put("gcm_id", sharedPreferences.getString(TwofeetConstants.DEVICE_ID, null));
            entity = new StringEntity(jsonParams.toString());

            api.apiCall(this, TwofeetConstants.POST_USERDATA_URL, entity, new OnApiFinishedListener() {

}

**Comment by vyshas** [comment]
Yes same here ,StringEntity not imported

**Comment by smarek** [comment]
yes, don't use `org.apache.http.entity.StringEntity` but use `cz.msebera.android.httpclient.entity.StringEntity` this is due to repackaged classes so there is no clash on runtime in Android (neither in old or new versions)
