### ISSUE TITLE
How to keep not confused.

### ISSUE THREAD

**Issue by Jacky-Xu** [loopj/android-async-http#980]
HI, Loopj：
In proguard,I write -keep class com.loopj.android.http.** { *; } , but the app crash.How to keep not confused.

**Comment by smarek** [comment]
First, post a stacktrace of crash, second, try to explain your situation, "how to keep not confused" is ambiguous sentence

**Comment by Jacky-Xu** [comment]
this is crash information:
---------------UserInformation----------------
name:0_20150930165425
model:SM-N9008V
os_version:4.4.2
versionCode:1
versionName:1.0
-------------------------------------------------
----------------Exception----------------
  ClassName:com.a.a.a.f
-----------------------------------------
  FileName:null
-----------------------------------------
  LineNumber:324
-----------------------------------------
  MethodName:a
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:com.a.a.a.f
-----------------------------------------
  FileName:null
-----------------------------------------
  LineNumber:415
-----------------------------------------
  MethodName:a
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:com.a.a.a.f$a
-----------------------------------------
  FileName:null
-----------------------------------------
  LineNumber:195
-----------------------------------------
  MethodName:handleMessage
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:android.os.Handler
-----------------------------------------
  FileName:Handler.java
-----------------------------------------
  LineNumber:102
-----------------------------------------
  MethodName:dispatchMessage
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:android.os.Looper
-----------------------------------------
  FileName:Looper.java
-----------------------------------------
  LineNumber:157
-----------------------------------------
  MethodName:loop
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:android.app.ActivityThread
-----------------------------------------
  FileName:ActivityThread.java
-----------------------------------------
  LineNumber:5335
-----------------------------------------
  MethodName:main
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:java.lang.reflect.Method
-----------------------------------------
  FileName:Method.java
-----------------------------------------
  LineNumber:-2
-----------------------------------------
  MethodName:invokeNative
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:java.lang.reflect.Method
-----------------------------------------
  FileName:Method.java
-----------------------------------------
  LineNumber:515
-----------------------------------------
  MethodName:invoke
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:com.android.internal.os.ZygoteInit$MethodAndArgsCaller
-----------------------------------------
  FileName:ZygoteInit.java
-----------------------------------------
  LineNumber:1265
-----------------------------------------
  MethodName:run
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:com.android.internal.os.ZygoteInit
-----------------------------------------
  FileName:ZygoteInit.java
-----------------------------------------
  LineNumber:1081
-----------------------------------------
  MethodName:main
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
----------------Exception----------------
  ClassName:dalvik.system.NativeStart
-----------------------------------------
  FileName:NativeStart.java
-----------------------------------------
  LineNumber:-2
-----------------------------------------
  MethodName:main
-----------------------------------------
  Description:java.lang.RuntimeException: java.lang.NullPointerException
-------------------end-------------------
now, if  i  don't  write  -keep class com.loopj.android.http.** { *; } in proguard,Will not  carsh occur.

**Comment by Jacky-Xu** [comment]
I found that the program crashes occur in the release,in the debug,Will not carsh occur。How can I solve this problem.

**Comment by smarek** [comment]
Well, `-keep class com.loopj.android.http.** { *; }` might be correct solution, stick to that
