### ISSUE TITLE
Only Android project support?

### ISSUE THREAD

**Issue by yangboz** [loopj/android-async-http#981]
Maven project include 
```Java
<dependency>
	<groupId>com.loopj.android</groupId>
	<artifactId>android-async-http</artifactId>
	<version>1.4.8</version>
</dependency>
```

While compiling throws:

```Java
[ERROR]ServiceImpl.java:[78,71] package cz.msebera.android.httpclient does not exist
[ERROR]ServiceImpl.java:[92,71] package cz.msebera.android.httpclient does not exist
[ERROR]ServiceImpl.java:[76,36] cannot access android.content.Context
  class file for android.content.Context not found
```

**Comment by smarek** [comment]
Hello, thanks for report, this is strange to me, can you inspect if the dependency includes sub-dependencies? Or you can manually add dependency on `cz.msebera.android:httpclient` maven artifact, see the possible versions here: https://github.com/smarek/httpclient-android/releases
And see the appropriate `build.gradle` of this library, for correct version, eg. `4.3.6` now with 1.4.9 version of library, here: https://github.com/loopj/android-async-http/blob/master/library/build.gradle#L27
