### ISSUE TITLE
Having issues with comodo ssl

### ISSUE THREAD

**Issue by swacedigital** [loopj/android-async-http#982]
Hey, we are moving our backend to a server which is using comodo ssl. I am responsible for the Android application and have been using async-http-client without any issues until now.

I am getting the standard 'SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.'.
After som research i found out that comodo ssl are using the "TLS 1.2" protocol (am i right?). Can it be that this isn't accepted?

I ended up, accepting all SSL certificates but would like to fix this. Do anyone have an idea of what the problem might be?
By the way, I have checked the ssl connection with multiple SSL tools to see if its correctly configured, and what I can see, it is all green.

**Comment by smarek** [comment]
Hello, use https://www.ssllabs.com/ssltest/analyze.html to test if your SSL certificate is deployed correctly.
Mentioned issue means you don't have local trust chain of the certificate, which is not related to used protocol (SSL2/SSL3/TLS1/TLS1.1/TLS1.2) but to certificate itself.
The device has to be able to verify the chain (trusting the CA and intermediate certificate),  or you have to provide your own TrustManager to validate server provided certificate yourself.

**Comment by smarek** [comment]
Also if you could provide me with URL to server, I could test if the service is accessible

**Comment by swacedigital** [comment]
@smarek I've sent you a PM

**Comment by smarek** [comment]
I've tested, SSL looks properly deployed, it's trusted in browser, however not trusted in my device also.
The solution is to provide your custom TrustManager and KeyManager to SSLConext, see the pattern already used in `MySSLSocketFactory` provided by library, https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/MySSLSocketFactory.java

Use `public AsyncHttpClient(SchemeRegistry schemeRegistry)` constructor and provide your own SchemeRegistry instance which provides your own SSLSocketFactory, which validates the SSL trust-chain correctly.

**Comment by swacedigital** [comment]
Thanks for your help. It seems it was a SNI problem all along.

**Comment by pegaltier** [comment]
Dear Smarek,

i have the same problem. The URL to server is : https://www.hotel-reseau-social.fr

@smarek Could you help me check if my certificate is valid ?
@swacedigital Could you give me your custom implementation of MySSLSocketFactory which validates the SSL trust-chain correctly.

Thanks

**Comment by pegaltier** [comment]
I also clarifies that my certificate is kind of DV: Domain validated

**Comment by Sumituppal-delhivery** [comment]
I am facing same problem .please share if you have the solution .

**Comment by metrey** [comment]
The same issue with cloudflair that use Comodo SSL; all solutions attempt not work
