### ISSUE TITLE
JSON and multipart mixed Request

### ISSUE THREAD

**Issue by njgarcia** [loopj/android-async-http#983]
Hi, i'm trying to make a request with some JSON data and a file, it looks like this: 

METHOD: post

HEADERS:

Authorization   Basic d2Vic2VydmljZTpyM05hdTE3Rw==

Content-Type    multipart/form-data;boundary=xxxxxxxx

BODY:

--xxxxxxxx

Content-Disposition: form-data; name="jsonFile"
Content-Type: application/json

{"model":"Premium","deviceLongitude":4.79337638,"pseudo":"nickname","deviceLatitude":45.7671507,"year":"2005","email":"email@mail.com","deviceLocale":"fr_FR","title":"my picture"}

--xxxxxxxx

Content-Disposition: form-data; name="imgName"
Content-Type: image/jpeg

//Image data array

/9j/4AAQSkZJRgABAQAAAQABAAD/4QBYRXhpZgAATU0AKgAAAAgAAgESAAMAAAAB
AAEAAIdpAAQAAAABAAAAJgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAB4KAD
AAQAAAABAAACgAAAAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQH/wAARCAKAAeADAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAA
AAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF
--xxxxxxxx

How can I accomplish this request with loopj?

**Comment by smarek** [comment]
method to use is here: https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/RequestParams.java#L283

Well, as simple as it can get is to use RequestParams, like this:
```java
RequestParams rp = new RequestParams();
// using method put(String key, File file, String contentType, String customFileName)
rp.put("jsonFile", new File("path/to/json/file"), "application/json", "jsonFile");
rp.put("imgName", new File("path/to/img/file"), "image/jpeg", "imgName");
AsyncHttpClient ahc = new AsyncHttpClient();
ahc.post(this /* context */, URL, rp /* request params instance */, responseHandler);
```
