### ISSUE TITLE
1.4.9 post json object,response 400 bad request

### ISSUE THREAD

**Issue by mobileloft** [loopj/android-async-http#984]
1.params:
params.put("arg1","test");
params.setUseJsonStreamer(true);
params.setElapsedFieldInJsonStreamer(null);

and response 400 bad request

but google's volley is ok.

**Comment by ysy950803** [comment]
Please tell me how to solve it.

**Comment by sendtion** [comment]
I have encountered this problem.This is why?

**Comment by ysy950803** [comment]
@sendtion If you want to post json object as a string, you can look at this:
`client.post(context, url, new StringEntity(json, "UTF-8"), CONTENT_TYPE_JSON, responseHandler);`
