### ISSUE TITLE
SSLProtocolException

### ISSUE THREAD

**Issue by csechuan** [loopj/android-async-http#985]
I am having this issue when switch to CloudFlare. It should be the signature algorithm differences. CF using `SHA256withECDSA`. Any workaround?

```
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x53371710: Failure in SSL library, usually a protocol error

SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error (external/openssl/ssl/s23_clnt.c:741 0x4176976a:0x00000000)
```

**Comment by smarek** [comment]
ECDSA may be problem with Android devices, see the capabilities of different versions of Android in providing ECDSA ciphers and combinations. https://www.ssllabs.com/ssltest/clients.html

Also test your backend URL with https://www.ssllabs.com/ssltest/analyze.html
Which should tell you if the ssl algorithm chain is properly configured, and if there is correct fallback for different Android version.

**Comment by jagatappv** [comment]
I'm trying to call api with URL with https

and i'm getting similar error

Here is my log:

 javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb98d0440: Failure in SSL library, usually a protocol error
                                             error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x9dd99d4d:0x00000000)

Can you give me any work around?

Thanks
