### ISSUE TITLE
Parameter not send when upload image

### ISSUE THREAD

**Issue by fahmihidayah** [loopj/android-async-http#986]
I uploaded image with parameter but server didnt found any parameter that I sent before. just the image.

         RequestParams parameter = new RequestParams();
       
        String par[] = {"image_1", "image_2", "image_3", "image_4", "image_5"};
        for (int i = 0; i < par.length; i++) {
            String parItm = par[i];
            File file = new File(userImageList.get(i).path);
            if(file.exists()){
                try {
                    String path = userImageList.get(i).path;
                    parameter.put(parItm, file, "image/jpg", parItm);
                    images = images + parItm + ",";
                    CommonUtilities.log(TAG, "image paramter " + images);
                } catch (FileNotFoundException e) {
                    CommonUtilities.log(TAG, "file not found");
                }
            }
        }
        if(images.contains(",")){
            images = images.substring(0, images.length() - 1);
        }
        parameter.put("images", images);
        parameter.put("lat", "" + location.getLatitude());
        parameter.put("lng", "" + location.getLongitude());

        parameter.setForceMultipartEntityContentType(true);
        parameter.setAutoCloseInputStreams(true);

Did I make a mistake?

**Comment by smarek** [comment]
I don't know, follow the example of sending multiple files, and be happy.
https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/FilesSample.java
