### ISSUE TITLE
I sometimes get an array in onSuccess when I'm not supposed to

### ISSUE THREAD

**Issue by matejhacin** [loopj/android-async-http#987]
Here's my code:

        client.removeAllHeaders();
        client.addHeader("Authorization", "Bearer " + acUser.getToken());

        client.get(context, (stagingEnabled ? API_BASE_STAGING_URL : API_BASE_URL) + ENDPOINT_RESERVATION_ACTIVE, new TextHttpResponseHandler() {
            @Override
            public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                Log.i(TAG, "failure: " + responseString);
                if (responseHandler != null)
                    responseHandler.onFailure(statusCode, createFailureMessage(statusCode, responseString));
            }

            @Override
            public void onSuccess(int statusCode, Header[] headers, String responseString) {
                final ACReservation acReservation = gson.fromJson(responseString, ACReservation.class);

                if (responseHandler != null)
                    responseHandler.onSuccess(acReservation);
            }
        });

I have a very weird issue and I'm not completely sure if it's an Android client issue or backend issue.

This code above works most of the time. But sometimes, it'll just randomly return onSuccess array. It's hard to explain so [check out this screenshot to see what I mean](http://puu.sh/kCKIh/7268ded63b.png).

As you can see, first 6+ requests were fine and then suddenly it randomly wrapped the json response with [ ].

And this also randomly happens when I should get an onFailure. I'll sometimes get onFailure 10 times in a row (like I'm supposed to) and then suddenly onSuccess and the responseString is "[]". Empty array.

I know this totally sounds like an API issue. Yeah, anyone with the right mind would instantly think it's a backend issue. I also did. But there's no way I could recreate this with Postman or the iOS client. This only happens here on Android. I also talked to the backend team and they are clueless about why this could be happening.

**Comment by smarek** [comment]
Interesting, I'll take your claim, that this is not an backend issue, as you correctly pointed out, that was my first idea. However, if you're using TextHttpResponseHandler there is no way, library would modify JSON response as in your screenshot. It would be only possible if the library itself took care of contained JSON and tried to encode/decode it.

Do you use in your application different ResponseHandler than what you've posted here?

**Comment by matejhacin** [comment]
No, I use this exact TextHttpResponseHandler since I want to get plain JSON from my request (as you can see from my screenshot). I don't use any other handlers.

I still feel like this is a backend issue but I tried really hard to recreate it outside the Android application and I was unsuccessful.
