### ISSUE TITLE
request failure with reason：failed to connect to localhost/127.0.0.1

### ISSUE THREAD

**Issue by GavinKwok0113** [loopj/android-async-http#990]
request url is not localhost,but get a error with:failed to connect to localhost/127.0.0.1 (port 8002) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)

**Comment by smarek** [comment]
`Connection Refused` is quite clear to me, what is the problem? Did you check the port is opened on the interface and that you're able to connect to it from telnet or something similar? It's not problem of requesting IP or port obviously. You can of course step through processing, but I don't see anything that's wrong with library in this case.

**Comment by GavinKwok0113** [comment]
I switch to v1.4.8 and everything is ok...

**Comment by lvleo** [comment]
Me too,I switch v1.4.9 to v1.4.8 and everything is ok.Is the reason of change org.apache.http.Header?

**Comment by lvleo** [comment]
Me too,I switch v1.4.9 to v1.4.8 and everything is ok,hope next version can solve this issue

**Comment by zhangxy1219** [comment]
Also find this problem when I used an IP that starts with "192.168." as host in url parameter.
Switch to v1.4.8 and it works fine.
Hope this can be solved in next version.

**Comment by GypsyLife** [comment]
I got same problem.

**Comment by zvaehn** [comment]
same on v1.4.9

**Comment by GypsyLife** [comment]
same problem

**Comment by sergii-frost** [comment]
Facing same issue with v1.4.9 --> cannot use `super(true, 80, 443)` to skip SSL validation.
Works fine on v1.4.8

**Comment by sendtion** [comment]
I got same problem on 1.4.9

**Comment by sumknot** [comment]
got same issue on 1.4.9, @GavinKwok0113 's answer saves me a bunch of time

**Comment by farzadnadiri** [comment]
same on v1.4.9
