### ISSUE TITLE
issue with Payu money

### ISSUE THREAD

**Issue by Sushil21** [loopj/android-async-http#993]
Hi,

i am using loopj lib (android-async-http-1.4.2.jar) in my android project but after integrating with PayU Money sdk my project showing some conflicts because PayU Money also using loopj lib in their sdk('com.loopj.android:android-async-http:1.4.6').so i have tried to remove my loopj lib and used it from PayU sdk. everything is working well but there is one more issue the override method of version 1.4.2 has changed in 1.4.6 .

Problem: I want to use version 1.4.2 override method in 1.4.6 please suggest me any solution.

version 1.4.6 method
```java
@Override
    public void onSuccess(int statusCode, Header[] headers, byte[] response) {
        // called when response HTTP status is "200 OK"
    }

    @Override
    public void onFailure(int statusCode, Header[] headers, byte[] errorResponse, Throwable e) {
        // called when response HTTP status is "4XX" (eg. 401, 403, 404)
    }
```
version 1.4.2 methods
```java
                    @Override
                    public void onFinish() {
                        super.onFinish();
                    
                    }

                    @Override
                    public void onSuccess(String s) {
                        super.onSuccess(s);
                 }
```

**Comment by smarek** [comment]
`onFinish` is not successor of `onFailure` method
Also you're overriding bad AsyncHttpResponseHandler, if you're receiving `byte[]` it's not TextAsyncHttpResponseHandler which returns Strings
