### ISSUE TITLE
Two-way(mutual) ssl authentication using AsyncHttpClient

### ISSUE THREAD

**Issue by vinod-jaiswal18** [loopj/android-async-http#994]
hello,

I am trying to achieve 2-way ssl authentication using AsyncHttpClient.
Can't find any sample code for this to continue.
Kindly help me with this, it's been like almost one week I am stuck into this.

Thanks.

**Comment by vinod-jaiswal18** [comment]
I have seen a similar issue #377 , but its not resolved.

**Comment by smarek** [comment]
Well don't open up new issue then and comment or help on the older one.
