### ISSUE TITLE
https handshake not working with loopj async 1.4.9. (not a self signed certificate)

### ISSUE THREAD

**Issue by Opvolger** [loopj/android-async-http#995]
The tool works fine on mij machine with http. even on my api controller with https on xmpp apache (than with MySSLSocktetFactory self-sign-cert. problem). 
But when i'm connecting to my real api on the internet "api.opelkadettcclub.nl" a get a error. Even when i use the MySSLSocketFactory. http is working fine but https will not connect.

A normal call in Android is no problem (see example code)

Example code:

    private class asyncnativeandroid extends AsyncTask<String, Void, String> {

        @Override
        protected String doInBackground(String... params) {
            try {
                URL url = new URL("https://api.opelkadettcclub.nl/api/KadettC/Alive");
                final HttpsURLConnection conn = (HttpsURLConnection) url.openConnection();
                conn.connect();
                final InputStream in = conn.getInputStream();
                Log.d("OKCCNL", "Oke https sync android classic call");
            } catch (Exception e) {
                e.printStackTrace();
                Log.d("OKCCNL", "Error https sync android classic call");
            }
            return null;
        }
    }

    private void Test()
    {
        AsyncHttpClient client = new AsyncHttpClient();

        new asyncnativeandroid().execute();

        client.get("http://api.opelkadettcclub.nl/api/KadettC/Alive", new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                Log.d("OKCCNL", "Oke http async");
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                Log.d("OKCCNL", "Error http async");
            }
        });
        
        client.get("https://api.opelkadettcclub.nl/api/KadettC/Alive", new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                Log.d("OKCCNL", "Oke https async");
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                Log.d("OKCCNL", "Error https async");
            }
        });

        client.get("https://www.google.com", new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                Log.d("OKCCNL","Oke https google async");
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                Log.d("OKCCNL","Error https google async");
            }
        });
    }

Response:

    10-23 23:39:43.991 20965-20965/nl.opelkadettcclub.app.okccnlmobapp D/OKCCNL: Error https async
    10-23 23:39:44.007 20965-20965/nl.opelkadettcclub.app.okccnlmobapp D/OKCCNL: Oke http async
    10-23 23:39:44.555 20965-21070/nl.opelkadettcclub.app.okccnlmobapp D/OKCCNL: Oke https sync android classic call
    10-23 23:39:45.051 20965-20965/nl.opelkadettcclub.app.okccnlmobapp D/OKCCNL: Oke https google async

Gradle:

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 23
        buildToolsVersion '23.0.1'
        defaultConfig {
            applicationId "nl.opelkadettcclub.app.okccnlmobapp"
            // Min versie 9 anders werkt https met cookies niet, ga geen 2 protocollen ondersteunen
            minSdkVersion 9
            targetSdkVersion 23
            //2 09 (API) 1.(0)0.15
            versionCode 20910016
            versionName '1.0.16'
        }
        productFlavors {
        }
    }

    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile 'com.google.code.gson:gson:2.3.1'
        compile 'com.android.support:support-v4:23.0.1'
        compile 'com.android.support:appcompat-v7:23.0.1'
        compile 'com.android.support:gridlayout-v7:23.0.1'
        compile 'com.android.support:recyclerview-v7:23.0.1'
        compile 'com.android.support:recyclerview-v7:23.0.1'
        compile 'com.android.support:cardview-v7:23.0.1'
        compile 'com.android.support:palette-v7:23.0.1'
        compile 'com.loopj.android:android-async-http:1.4.9'
    }

Call stack:

    10-13 19:57:17.335 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err: javax.net.ssl.SSLException: Connection closed by peer
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
    10-13 19:57:17.339 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    10-13 19:57:17.343 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.lang.Thread.run(Thread.java:841)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err: javax.net.ssl.SSLException: Connection closed by peer
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
    10-13 19:57:17.347 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    10-13 19:57:17.351 1284-1721/nl.opelkadettcclub.app.okccnlmobapp W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by Opvolger** [comment]
I have my hosting service changed all most all settings
like Cipher Suites and i have a working SSL 2 handshake. But still i get a error when i make a call using this packages.

What is wrong with my provider settings or what is wrong with this code?

https://www.ssllabs.com/ssltest/analyze.html?d=www.opelkadettcclub.nl
or
https://www.ssllabs.com/ssltest/analyze.html?d=api.opelkadettcclub.nl

makes no difference, all the same error as above.

**Comment by Opvolger** [comment]
HttpsURLConnection makes a different handshake request then the async protocol.
There are less extension used.
there is no server_name and SessionTicket TLS in the request. ?!?

I am very new in SSL, so i have to google everything and read a lot. This is all i found out now. (with WireShark)

**Comment by Opvolger** [comment]
I have found the solution:
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

in my gradle file. But why it is not working on JAVA 1.8?

**Comment by smarek** [comment]
I'm sorry @Opvolger I haven't been available for quite a time now, and I couldn't help you with this issue.
Nice finding that you need JDK 1.7 compatibility to be set, we do that in our library, maybe that's the reason? Also SSL works changed in every major java release.

My first guess would be that by default the project is using 1.6 compaibility, because highest for Android provided is 1.7 compatibility, 1.8 is not available so far, if I understand the current situation correctly

**Comment by romansolo** [comment]
I also had this issue. In my case it happened because TLSv1 support was disabled on the server due to security reasons. And on Android 4.1.+ support of TLS 1.1 and TLS 1.2 is available but disabled by default as described here https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/.
As a solution I have implemented my own SSLSocketFactory where support of both TLS 1.1 and TLS 1.2 can be enabled.

`@Override
    public Socket createSocket(Socket socket, String host, int port, boolean autoClose) throws IOException {
        return enableTLSOnSocket(sslContext.getSocketFactory().createSocket(socket, host, port, autoClose));
    }

    @Override
    public Socket createSocket() throws IOException {
        return enableTLSOnSocket(sslContext.getSocketFactory().createSocket());
    }

    private Socket enableTLSOnSocket(Socket socket) {
        if(socket != null && (socket instanceof SSLSocket)) {
            ((SSLSocket)socket).setEnabledProtocols(new String[] {"TLSv1.1", "TLSv1.2"});
        }
        return socket;
    }`

**Comment by bb1690** [comment]
I am facing the same issue, I have written the SSLSocketFactory but client.setSSLSocketFactory() needs cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory so i am not able to set my socketfactory  as it extends to javax.net.ssl.SSLSocketFactory . Can some one suggest any alternative .

**Comment by cyberformed** [comment]
Its not working.

**Comment by sidpal7747** [comment]
I am facing the same issue **javax.net.ssl.SSLException: Connection closed by peer**. Please tell me how do I update the TLS version from 1.0 to 1.2?
