### ISSUE TITLE
HttpEntity Issue not working in AsynchttpClient

### ISSUE THREAD

**Issue by Anand-Krish** [loopj/android-async-http#996]
I am using this Entity in apache for post type like this "postRequest.setentity(Entity)". I just needs to know how to use "Entity"  in Asynchttpclient.
1) for DefaultHttpclient:
```java
HttpPost postRequest = new HttpPost(requestURL);
		postRequest.addHeader("Content-Type", "application/json");
		postRequest.addHeader("Authorization", "key=" + GlobalDefines.API_KEY);
		postRequest.setEntity(new StringEntity(this.theObject.POSTString,HTTP.UTF_8));
```
2) For Synchttpclient I have use Entity like this.
```java
SyncHttpClient sync=new SyncHttpClient(schemeRegistry);
sync.post(getactivity(), url, (new StringEntity(this.theObject.POSTString,HTTP.UTF_8), "application/json", new AsyncHttpResponseHandler());
```
But I am getting a null response for this Executuion in OnFailure(). Can any one suggest me the right way to set Entity in Asynchttpclient.

**Comment by smarek** [comment]
Well you haven't posted StackTrace, which is crucial for us to debug any problem, Closing until you provide it
